### ISSUE TITLE
Wrong type shown in runtime call for assetConversionApi

### ISSUE THREAD

**Issue by nuel77** [polkadot-js/apps#10080]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [x] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

We have installed `pallet-asset-tx-payment` pallet on our chain with the only difference being the type of asset. AssetHub is using `XcmV3Multilocation` as the asset type but as Enum as defined [here](https://github.com/Polkadex-Substrate/Polkadex/blob/c4fb57e94db244c65c69f28af98523bfc258db71/runtimes/mainnet/src/lib.rs#L1639) in our chain.  The polkadot.js UI still shows the type as `XcmV3Multilocation` which is incorrect.

<img width="1438" alt="image" src="https://github.com/polkadot-js/apps/assets/50878033/4c0567d5-2372-4904-a7d6-cb771b23c021">
Is this bug in the UI or do we have to define/override this type somewhere? if so it would be very helpful where if anyone can give some pointers on how to show this correctly.

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment]
These are all hard-coded in the API repo (once metadata v15 is available broadly, it will be changed since that version of the format does actually supply the runtime types inside the metadata. On the currently-active metadata v14 this is not the case)

As anything with the API is is completely configurable, so you can inject your own types for any definition - including the runtime calls. (And the apps repo makes this available on a per-chain basis inside apps-config so chains can add their own additions)
