### ISSUE TITLE
Pre-sale tokens cannot be claimed: "TypeError: message should be a Buffer"

### ISSUE THREAD

**Issue by Juanma0x** [polkadot-js/apps#10115]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

The DOT from the token pre-sale cannot be claimed due to a "TypeError: message should be a Buffer" error encountered on https://polkadot.js.org/apps/#/claims. Consequently, the "Confirm" button remains disabled.

![image](https://github.com/polkadot-js/apps/assets/120041850/4085ef1a-b8a0-41a0-837b-487b7f7003aa)

* **What is the motivation for changing the behavior?**

The tokens from the pre-sale should be claimable from https://polkadot.js.org/apps/#/claims, considering it was mentioned that there's no expiration date for claiming them.

FAQ in https://claims.polkadot.network/
>There is no deadline to claim. Now that the Polkadot network is live, the claiming process will work indefinitely.

**Note**: Is there an alternative to https://polkadot.js.org/apps/#/claims to claim the tokens?

* **Please tell us about your environment:**
MacOS.
Firefox 120.0.1
Chrome 120.0.6099.109

**Comment by jacogr** [comment]
I will remove the functionality if not working - sadly there are no test-cases to check any changes to the feature, so it is not something that is fixable. (PRs always welcome if you have test-cases)

**Comment by Juanma0x** [comment]
Are there any alternative methods available to claim the pre-sale tokens apart from the function in Polkadot-JS UI?

Thanks, Jaco.

**Comment by jacogr** [comment]
It _may_ work with the PR that has been merged/deployed in 0.133.2-34-x, but there is absolutely no way of completely verifying it - the above HACK forces a `Buffer` module into the browser context which is what it seems to be complaining about. 

If it does not yield positive results, the next step would just be do remove it completely as non-working since there is just no infrastructure available to test through this to see what is up in the various steps.

Sadly, I have no idea around any claiming functionality and where it may be available at this point in time :(

**Comment by Juanma0x** [comment]
The hack works!

At least one user has managed to claim their DOT, and I'm waiting for others to do the same. Thank you, Jaco, for dedicating your time to investigating and solving this issue.
