### ISSUE TITLE
Apps `Settings > Metadata` breaks

### ISSUE THREAD

**Issue by al3mart** [polkadot-js/apps#10334]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When loading Paseo's app tab Settings > Metadata the application breaks and shows the following error:
`code length overflow. (116316>18672)`

One of the elements that tab shows is `color`, defined for Paseo here: https://github.com/polkadot-js/apps/blob/69197a4a8f35e9ea42c5c15b0e28469943998f4c/packages/apps-config/src/endpoints/testingRelayPaseo.ts#L67

I wonder if the background image included in there could be the cause of that tab breaking.

Thanks to @ltfschoen for reporting <3

**Comment by TarikGul** [comment]
Seems as if this is coming from: https://github.com/polkadot-js/ui/blob/master/packages/react-qr/src/qrcode.ts, and https://github.com/polkadot-js/ui/blob/master/packages/react-qr/src/Display.tsx#L37-L46

I don't know how deep this issue is, but I'll continuing looking into it (Could be a small fix or not). No promises on how fast though, there are things currently higher in the queue.

**Comment by al3mart** [comment]
Metadata would generate something like

`{"chainType":"substrate","color":"#FFFFFF","decimals":0,"genesisHash":"","prefix":0,"title":"","unit":"UNIT"}`

Where in Paseo's case `color` is a huge background image. That must be the reason. Unfortunate as it looks great haha.
Will try to generate something smaller and resubmit something.

**Comment by al3mart** [comment]
Closed by https://github.com/polkadot-js/apps/pull/10390
