### ISSUE TITLE
Make dev phrase easily accessible

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#1033]
Make dev phrase easily accessible from generate account screen. And make some big warning when it is been used.

The phrase is `bottom drive obey lake curtain smoke basket hold race lonely fit walk`

https://github.com/paritytech/substrate/blob/4999397966afa193f57c2ce72974313485b1b6d3/core/primitives/src/crypto.rs#L29

Or just allow me to add account by URI format

**Comment by jacogr** [comment]
It is just a UI enhancement - fromUri already caters for empty derived phrases, https://github.com/polkadot-js/common/blob/master/packages/keyring/src/index.ts#L155

I purposefully did not enable it on the UI as a start, since people will get it wrong. 

(A warning is not enough, a couple of weeks ago I even noticed that the “Alice” ed25519 has tokens on Alex)

Can be discussed around dev only chains, with an option (or even an explicit setting to have the option)

**Comment by xlc** [comment]
An option in settings page to toggle dev features?

**Comment by jacogr** [comment]
Yes, that is what I am thinking. And then probably just allow an empty phrase or explicitly have another dev toggle in accounts.
