### ISSUE TITLE
Improvements with Contracts UI

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#1037]
After using the contracts UI for a bit, here are some suggested improvements:

- [ ] When you purge a chain, remove the history of contracts from the UI.

Right now, if you make a bunch of contracts, and then start over, all the stale data persists. Wondering if there is a clever way to clear that data if we detect the chain has restarted or changed.

- [ ] When uploading some code with `code` tab, only switch to `instance` as that is the natural flow. Right now it switches to `code` if that tab is available.

- [ ] Let the user make a call with 0 value.

Probably more suggestions to come :)

**Comment by jacogr** [comment]
Issue 1 is a bit problematic, since we cannot detect a purged chain. Having said that, there is an issue logged for proper management of stored info (edit, forget), I think there a “clear all” could be helpful. 

Aware of that one. It flows nicely the first time around and then never again. Certainly a gremlin That should be addressed. 

Issue 3 - stupid oversight/check, it should be fixed.

**Comment by jacogr** [comment]
Marked small/bug only for point #2 & #3. (Will ref for the first item)
