### ISSUE TITLE
Why is Staking tab gone in westend? 

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#10388]
despite the fact that the pallets are all still there? 

I think given that the apps is already transforming into a developer console, and that the staking in westend is an important piece of testing ground, I do want to state interest in bringing it back. Possibly it can be hidden as a button, but if you go to a certain URL it should still be there.

**Comment by TarikGul** [comment]
So I have it fixed locally and will push something up soon, basically the issue is that the storage queries had breaking changes in staking, specifically in this case the rename from `claimedRewards` to `legacyClaimedRewards`.

The real headache here is ensuring we support both future and past runtimes that may or may not have the changes.

**Comment by kianenigma** [comment]
Okay, what we can note here is how we can make these breaking changes easier for you? 

I know exactly the PR that moved `claimedRewards` to `LegacyClaimedRewards`. I am sure it had had good prdoc/description on what eg. you should be doing to keep up to date. cc @Ank4n @rossbulat 

thanks for the update in any case, and let us know if you need any particular assistance with this.

**Comment by rossbulat** [comment]
Do we have any metrics on how many users still use staking on Polkadot JS Apps? I suspect it might not be the best utilisation of time to maintain the Staking page when the staking dashboard offers a more enhanced UX.

There is the advantage of supporting any chain - but Staking Dashboard could also go in this direction by supporting custom endpoints, only show the community page if data exists for that chain, etc. I think this would be more conducive than maintaining the JS Apps staking tab - time and effort that could be better spent on the API, documentation, etc.

**Comment by Ank4n** [comment]
> So I have it fixed locally and will push something up soon, basically the issue is that the storage queries had breaking changes in staking, specifically in this case the rename from `claimedRewards` to `legacyClaimedRewards`.
> 
> The real headache here is ensuring we support both future and past runtimes that may or may not have the changes.

Let me know if I could be of help. Tbh I didn't think that renaming of `claimedRewards` to `legacyClaimedRewards` would be breaking PJS but good to remember for future.

**Comment by TarikGul** [comment]
> Okay, what we can note here is how we can make these breaking changes easier for you?

Thanks, much appreciated. So far for the exposures I fixed the derives downstream already in the API, so those should be updated in apps already. There was a few more residual issues as well with some storage calls, but I am sure I'll be able to sort it out. Really the toughest portion of any general upstream changes are maintaining that support across present and future runtimes (Depending how far behind Kusama and Polkadot are). 

> Do we have any metrics on how many users still use staking on Polkadot JS Apps?

AFAIK we dont.

> There is the advantage of supporting any chain - but Staking Dashboard could also go in this direction by supporting custom endpoints, only show the community page if data exists for that chain, etc. I think this would be more conducive than maintaining the JS Apps staking tab - time and effort that could be better spent on the API, documentation, etc.

I definitely agree with this whole sentiment. The staking dashboard is a top tier experience, and any effort directed towards improvements there is time well spent 🙏. I think generally since the main idea here is "maintenance", I'll just make sure things continue to be supported without an arduous amount of time sunk into improvements.

**Comment by kianenigma** [comment]
> Do we have any metrics on how many users still use staking on Polkadot JS Apps? I suspect it might not be the best utilisation of time to maintain the Staking page when the staking dashboard offers a more enhanced UX.

I think for developer/debugging purposes, the tab should be there, 100% agree with two banners: 

1. as a normal user, go to staking.polkadot.network
2. this banner pleaseeeeee https://github.com/polkadot-js/apps/issues/7902
