### ISSUE TITLE
Users should not be allowed to select the same account for stash and controller

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1074]
As discussed with some of you, having `controller` === `stash` when bonding funds is not only dangerous but also annoying when testing and not paying attention to the warning.

We should prevent users from selecting the same account for `stash` and `controller` in the bonding modal.

**Comment by jacogr** [comment]
The whole idea behind only warning is that we just want to provide the info, not play dad. However, since staking is nowhere close to simple, not against the idea of playing cop and disallowing these completely - the 99.9% won't be affected and the 0.1% can still do it elsewhere.

Related to https://github.com/polkadot-js/apps/issues/926 - these are some other really problematic cases. (Mostly as found by @kwingram25 as he was going through)

**Comment by jacogr** [comment]
The warnings were added here - https://github.com/polkadot-js/apps/pull/963

**Comment by chevdor** [comment]
The 'bad' choice is the dangerous one unfortunately. 

By default, bonding on Account X will propose X as controller.

If you make it quick and confirm, your account will be locked: once your stash is bonded, your controller (the same account) will no longer be able to 'control' anything any more since no more tx will be possible.

**Comment by Stefie** [comment]
We have the same `<InputAddress>` component behaviour when setting a session key.

Maybe we should add a warning? error there as well?

<img width="710" alt="Screenshot 2019-05-10 at 15 07 42" src="https://user-images.githubusercontent.com/125398/57529536-74b52400-7335-11e9-82ae-25aae9b7a767.png">
