### ISSUE TITLE
Nominator drop-down is blank

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1109]
![image](https://user-images.githubusercontent.com/1424473/57381486-51f70400-71ab-11e9-9629-29e76252aa02.png)

**Comment by Stefie** [comment]
That should work with the latest master and the fixed v4 API. It was one of the things that were broken because of the missing linked map support. The screenshot is from the latest master.
![Screenshot 2019-05-08 at 16 23 03](https://user-images.githubusercontent.com/125398/57382664-a1d6ca80-71ad-11e9-9576-678192ccaf71.png)

**Comment by jacogr** [comment]
It is V3 that is broken, like on Alex. This one is exactly the same issue as reported in https://github.com/polkadot-js/apps/issues/1109

(V4 was fixed, V3 was broken - so the roles between the 2 have been swapped)

@amaurymartiny is looking

**Comment by jacogr** [comment]
@Stefie Check against Alex.

**Comment by Stefie** [comment]
> V4 was fixed, V3 was broken - so the roles between the 2 have been swapped

Ah, damned, ok... The same is probably true for https://github.com/polkadot-js/apps/issues/1108, then.

**Comment by jacogr** [comment]
Yes, meant to link that issue above (instead of recursively linking to this one) - the issue is the same for both.

**Comment by jacogr** [comment]
Closed in #1110
