### ISSUE TITLE
Hide `Root` extrinsics from the normal Extrinsics UI

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#1146]
If the Polkadot UI knows that a function requires `Root` origin to call, then it does not make sense to show such functions to the user in the Extrinsics UI. They should only show up in the `Proposals` callable function selector.

**Comment by jacogr** [comment]
It doesn’t. The metadata interface does not expose any of this information.

**Comment by xlc** [comment]
Does it make sense to have metadata expose this information?

**Comment by jacogr** [comment]
It can to a certain extend. Metadata v0 (first version) did have origin - which allowed you to filter out root (it was used that way with the conversion for the poc-2 version where we had private/public). It is however only a part of the puzzle -

1. It means you won't see these, and (hopefully) know it needs root, i.e. consensus.setCode - https://github.com/paritytech/substrate/blob/master/srml/consensus/src/lib.rs#L317

2. This means that these will be assumed a public since it has origin, i.e. balances.transfer - https://github.com/paritytech/substrate/blob/master/srml/balances/src/lib.rs#L346

3. And then you get these, which is not valid for either, but it has an origin that should be set to inherent, i.e. timestamp.set - https://github.com/paritytech/substrate/blob/master/srml/timestamp/src/lib.rs#L223

So the existence/absence of origin is not enough, but it can get to _something_ just based on the params. I certainly would not advocate bringing the `origin` parameter back into play, since it never gets encoded/decoded which is the intent of the method parameters, i.e. guiding encoding/decoding. Having to ignore this all over middleware is not a good experience. The addition of a flag/enum on the method could help, but between signer/root/inherent, not sure that all the info can actually be extracted reliably. Parts obviously can (root vs the rest) and may be worth it if somebody is every bored and reworking metadata generation.

The apps UI is the only place that I certainly deem this enum/flag useful - at the same time won't go to bat for the addition of the information since it is assumed that developers that use extrinsics in this way know what they are doing. (For all the rest there should be simple-to-follow UIs)
