### ISSUE TITLE
Brainstorming Account overview

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#1164]
_Originally posted by @nczhu in https://github.com/polkadot-js/apps/issues/1044#issuecomment-492266132_

Caught up with @Tbaut on this last week. Put some of what we brainstormed down to Sketch. Keen to hear your feedback on this, in light of providing a more beginner-friendly UI for upcoming testnet(s).

This 1st draft adds:
- Users can see breakdown of their balances. I.e. what is free (available to spend vs lock vs vesting) vs what is reserved. 
- Users can edit inline, per Jaco's comment above
- Users can see `tags` they set
- Users see an empty state if there aren't accounts, related to #1006 

## Empty State
![1  Accounts: empty state](https://user-images.githubusercontent.com/23445933/57706471-1a360380-7666-11e9-844b-864c841a4afc.png)

## Account Overview: Mock 1
![2  Accounts: overview](https://user-images.githubusercontent.com/23445933/57706459-1609e600-7666-11e9-9bb1-51bcee2b1286.png)

## Account Overview: Mock 2
![3  Accounts: overview 2](https://user-images.githubusercontent.com/23445933/57706484-1e622100-7666-11e9-964c-35c8dde82e4c.png)

Can also feedback within the image here: https://sketch.cloud/s/VKWv8

**Comment by Tbaut** [comment]
So many good ideas!

I like the footer with "restore my accounts".
I like the empty card with + to add an account, I was originally thinking of a button at the top but that's better. We'll move away from the tabs soon I guess. Creation and Restoration could be in a modal, edit would be inline (the name, working on this now in https://github.com/polkadot-js/apps/pull/1163). Vanity can be moved in tools.

I thought recently about adding automatically tags to accounts `stash`, `controller`, `session`, this is not really related to the account overview but that'd surely help. We definitely need to show them in the account overview.

Bonding doesn't belong here IMO, we shouldn't mix things too much. Here it's about having an overview. We could think about a short and expanded view to have more info on a specific account. 

What's missing and I'm not entirely sure where it would fit best (in an expanded view?) is backup, `change password` and `forget`

The look and feel of the mockups will obviously be a little different since we're trying to stick to semantic UI for now at least.

**Comment by jacogr** [comment]
The empty + was what I had in mind as well. (However first need to actually see it, specifically moved away from this in Ethereum since it was just unwieldly.) The square cards fit in with what is there, there is just not enough for the long cards (additionally, it we cannot immediately fit it into `AddressSummary` would steer completely clear since just layout doesn't add any additional functional value while adding maintenance burden.

Agree with not having staking anywhere close to this - as it stands we are not coping on RPC after the staking introduction, so would not like to add anything to the mix as it stands.

**Comment by Tbaut** [comment]
The one thing that I see problematic with this "empty +" as the 1st item of the list is that creating accounts doesn't happen too often. This "empty +" remains in the way though. Having it in the end of the list makes it less intrusive, but could end up being hidden for someone with many accounts. Although this person after having created so many accounts will most probably know where to find it :)

**Comment by jacogr** [comment]
So played around a tiny bit - I think we would be better off with a layout like we have in staking.

On the left:

- icon
- name
- accountId
- accountIndex
- tags
- available balance (i.e. can be spent)

On the right:

- all balances broken down
- ability to unlock balances
- crypto type (this is useful, since we will probably continue to have a different type for sessions)
- buttons such as forget (trash icon) & backup

**Comment by Tbaut** [comment]
Based on the feedbacks and talks, we'll move toward something like this short term. And we can make it better :) (add filters, hide the right part and make it expandable..)
I want to start working on the staking process asap.
![image](https://user-images.githubusercontent.com/33178835/57851476-f2b77600-77e0-11e9-8ca5-090a454e510b.png)
![image](https://user-images.githubusercontent.com/33178835/57851848-e41d8e80-77e1-11e9-8a1d-71b1a4c18aed.png)

Also @nczhu proposed to use the word `redeemable` instead of `unlockable` which is as long but probably much better :)

**Comment by jacogr** [comment]
We have #1044 as well - which one should we close/combine? (i.e. prefer actionable tickets, these look like duplication of efforts)

**Comment by Tbaut** [comment]
https://github.com/polkadot-js/apps/issues/1044 is definitely an actionable ticket closed by https://github.com/polkadot-js/apps/pull/1163. This one still has things like the + button, the welcome screen. But feel free to close if you think there's no more discussion to have.

**Comment by jacogr** [comment]
The issue is that the welcome screen conflicts with the initial on-boarding - so don't want to do the same thing in 2 places. (One or the other, not both, prefer to keep things streamlined. Not convinced about the on-boarding anyway, it feels like duplication and doing work on that, which having gaps with needed functionality is also a waste, or rather, not the best place to put effort)

As for the + there are a couple of things that should be done on anything that resembles an address -

- when not available, "+" - so anything can be added (i.e. on staking)
- any address (no mini) has a "receive" mini button (quick send)
- any account has a "send" mini button (quick send)

Have not logged any of those atm since they are not really actionable, i.e. the other stuff needs to be in place first.

**Comment by Tbaut** [comment]
closing as we're now close to what is described here functionality-wise, minus the cat picture.
We can hopefully get some better design in the future with a designer :crossed_fingers:
