### ISSUE TITLE
Add deposit and withdraw buttons to staking page

### ISSUE THREAD

**Issue by asmodat** [polkadot-js/apps#1187]
Issue 

When entering https://polkadot.js.org/apps/#/staking/actions the page doesn't give you options to transfer or withdraw funds from accounts viable there (like those used for bonding, validating and so on).

This poses threat to users where they have to copy addresses from which they want to deposit or withdraw funds and then go to transfer tab https://polkadot.js.org/apps/#/transfer. Because users have to remember axxount names to make tx it causes a confusion and it is also painful for to switch between tabs to do simple operations like transfer.

Please add deposit and withdraw buttons to the /staking/actions account tiles so all is on one page.

**Comment by jacogr** [comment]
Can investigate it after these pre-requisites -

- https://github.com/polkadot-js/apps/issues/1182 - "send from" & "send to" modals form addresses/accounts - removal of transfer app
- https://github.com/polkadot-js/apps/issues/958 - staking rework into "bundle of accounts" with actions instead of "per account" as currently

Marking a P5 until the above deps are in, especially the second needs has the largest impact.

**Comment by jacogr** [comment]
The use case should actually be catered for now after the recent reworks on addresses, accounts and transfer (staking page rework for an action-centered approach is next up) 

The transfer link now opens as a modal while on any page, so while on staking you can make a transfer without having to swap pages.

**Comment by jacogr** [comment]
Closing. With the transfer links & deposit/send buttons the user doesn't need to leave the screen. (Trying . anything more than make the "transfer" even more intuitive, i.e. adding extra buttons will detract from the way the "bundle actions" work)
