### ISSUE TITLE
UX proposal - Address Input

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#1203]
`[rossbulat: polkadot JS milestone 1 proposals]`

#### Goal
UX Elements to fill voids in Polkadot form management and general design across packages.

#### Nature of Work
Iterative form development 

#### Specifications
- [x] All elements are designed to be responsive for all screen sizes
- [x] All elements are structural components; all can be `ui-app` components to be imported elsewhere in apps
- [x] `styled-components` styling comes first, least reliance on external styles to prevent bloat
- [x] Designed to be fully typed with generic typing where appropriate

#### Discussion Goals
Positive consensus for each element, additions or amendments where agreed upon. Where one does not support an element, offer an alternative solution.

## Address Input `AddressInput`
A account selection element that allows searching for account + filter local stored accounts with the name or address of the account.

<img width="1033" alt="AddressInput" src="https://user-images.githubusercontent.com/13929023/58312922-8ec32c00-7e36-11e9-8e34-c43212561608.png">

#### Justification
Cannot rely on local storage addresses only. Current textbox designs do not facilitate an address icon, and do not allow one to search for an additional address.

#### Functional Notes
- Relies on RPC call to retrieve address on chain
- Ability to persist addresses in local storage once successfully retrieved

#### Styling Considerations
- Fits parent container width by default, that width property can overwrite
- Local account list vertically justified to center
- Icon transitions from searching to completed.
- Address fade in as local storage is updated

**Comment by jacogr** [comment]
Questions to help my understanding here: 

1. What do you mean by this - "Relies on RPC call to retrieve address on chain" Which RPC does the node provide to send back addresses?

2. How this this work with the keyring management (which is actually which manages all pairs for accounts, addresses including those from external signers)

**Comment by jacogr** [comment]
@rossbulat Can we please have answers on the 3 questions above?

**Comment by jacogr** [comment]
Ok, so will give my feedback -

- The app doesn't have a server with any back-end, nor do users have accounts on a remote server where details are stored. All accounts are either in localStorage, injected by extensions or (really soon) Parity Signer and other mobile wallets. Substrate/Polkadot doesn't have account management itself, neither is there "RPCs available" to query addresses, e.g. see https://polkadot.js.org/api/METHODS_RPC.html. 

So the remove query aspects are really, well, not applicable since there is no RPCs for any of these, nor intent to add. (This is great in server-managed environments, so can see where the idea originates)

- All accounts are therefore managed by the keyring. The exiting AddressInput provides access to this keyring, allowing you to search it (by searching by address and name and selecting), add any new (by pasting an address, when not found, adds to recent), or select from what is in accounts/addresses.

There are some really pretty UI enhancements suggested here, i.e. applied to transfer we have 

![image](https://user-images.githubusercontent.com/1424473/58469797-86256b00-8140-11e9-870e-1fda1b85a66e.png)

However, as "type-only-remote-query-component", the idea does not quite work out with the realities of where these come from, or what is available to the users. 

(There is certainly a gap once there is native ipfs support, for access for remote information from additional places, i.e. content around proposals, user-specific info, etc. On some chains, e.g. not Polkadot, that is contracts enabled, registries could also come into play, which could make this type of interface for address queries viable)

For now this has no backing support, and no specific need around the existing (or envisioned apps available) so closing. This type of remote queries works really well on other chains with the backing infrastructure, so could very well need to be resurrected.
