### ISSUE TITLE
Toggle Switch Element

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#1205]
`[rossbulat: polkadot JS milestone 1 proposals]`

#### Goal
UX Elements to fill voids in Polkadot form management and general design across packages.

#### Nature of Work
Iterative form development 

#### Specifications
- [x] All elements are designed to be responsive for all screen sizes
- [x] All elements are structural components; all can be `ui-app` components to be imported elsewhere in apps
- [x] `styled-components` styling comes first, least reliance on external styles to prevent bloat
- [x] Designed to be fully typed with generic typing where appropriate

#### Discussion Goals
Positive consensus for each element, additions or amendments where agreed upon. Where one does not support an element, offer an alternative solution.

## UI Toggle Switch `ToggleSwitchMulti`
A toggle switch UI element to replace dropdowns where it is better suited.

<img width="541" alt="SwitchToggle" src="https://user-images.githubusercontent.com/13929023/58313692-5e7c8d00-7e38-11e9-9baa-58ed4cc08537.png">

#### Justification
Simplifies input, where the dropdown alternative a) hides the options and b) requires two interactions instead of 1. Can be used to streamline input and make forms more user friendly. Element is not offered by frameworks like SUI (personal opinion that frameworks bloat the app beyond bootstrapping, would adopt bare-bones approach).

#### Functional Notes
- Selecting items will simply toggle an underlying hidden form value

#### Styling Considerations
- Highlighted active option that will transition to new selections
- Centered content with moderate spacing for optimal readability.

**Comment by jacogr** [comment]
Question: Instead of building own here, why not just simple the toggle option in the semantic buttons? (Always prefer not building anything since anything extra requires maintenance)

**Comment by rossbulat** [comment]
I could not find an SUI equivalent. They have an unlabelled on-off toggle switch, but could not see one where labelled multiple values are used. ([SUI forms page](https://semantic-ui.com/collections/form.html#multiple-select))

**Comment by jacogr** [comment]
Cool, yes, not quite visible, however https://react.semantic-ui.com/elements/button/ (search for toggle) - 2 of them next to each other with opposite states.

**Comment by jacogr** [comment]
So toggle via button is currently used in 2 places -

- settings - https://github.com/polkadot-js/apps/blob/master/packages/app-settings/src/General.tsx#L114
- contracts - however this is being removed/replaced with the same layout as in addresses/accounts (so going away)

Some issues here -

- Styling on these are certainly lacking, since it is not entirely obvious
- For each use it is actually a "build-your-own"

As a minimum, the use in the first should be replaced with something that is obvious & maintainable. (For settings-specific stuff, which I guess was one of the identified areas, it is probably a bit more involved since the data source is external, i.e. not actually part of apps, i.e. UI modes)

Alternatively, the specific WS-endpoint change can be done by an attached button to the input, which is consistent with what we have in the rest of the UI, i.e. where we select units. (Which is a very viable solution here even just for the sake of consistency)

**Comment by jacogr** [comment]
Pull in https://react.semantic-ui.com/modules/checkbox/ with the Toggle styling for the affected area (only settings, contracts is being reworked)
