### ISSUE TITLE
UX Proposal - Slide-out glossary & tooltip

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#1206]
`[rossbulat: polkadot JS milestone 1 proposals]`

#### Goal
UX Elements to fill voids in Polkadot form management and general design across packages.

#### Nature of Work
Iterative form development 

#### Specifications
- [x] All elements are designed to be responsive for all screen sizes
- [x] All elements are structural components; all can be `ui-app` components to be imported elsewhere in apps
- [x] `styled-components` styling comes first, least reliance on external styles to prevent bloat
- [x] Designed to be fully typed with generic typing where appropriate

#### Discussion Goals
Positive consensus for each element, additions or amendments where agreed upon. Where one does not support an element, offer an alternative solution.

## Slide-out Glossary & Tooltip Expansion
Expand glossary and help tooltips with the following enhancements:

1. Theming and styling for better headings, spacing and separation of terms
2. Load via React Suspense
3. Option to filter terms 
4. Replace scrollbar to fade out rather than stay there ([smooth scrollbar](https://www.npmjs.com/package/smooth-scrollbar))
5. API that opens the glossary at a particular term
6. Integrate a glossary link into the tooltip, and / or embed glossary links into text with an underlined style to reflect it is a glossary term.

**Comment by jacogr** [comment]
Not really open to pull in more packages for the sake of doing so. Sure, it is cool, but extra cost in terms of keeping updated and not really React-by-default. But I'm guessing that was optional anyway, since it doesn't add anything new.

Some questions -

- Load - what problem that we currently have are we addressing here specifically? 
- "API that opens the glossary at a particular term" - what do you mean by this? 

I'm a bit hesitant to turn this into something that is not "just a very brief reference" and building a wiki-like "everything is in there" solution. The wiki is there, the in-app help is just the bare minimum to get the initial questions answered. (More content means more work to keep updated and current as the app expands. The idea is not to "define polkadot", but rather to help quide on actions)

**Comment by jacogr** [comment]
Closing, we are not going to go to backend server-based architecture.
