### ISSUE TITLE
Too generic styling for .ui.buttons leads to unwanted behaviour

### ISSUE THREAD

**Issue by Stefie** [polkadot-js/apps#1228]
The styling and hide/show behaviour for the UI buttons inside the address cards is too generic.
It's matching `article .ui.button` which includes all ui-buttons inside the html `<article>` element that are anywhere used in apps. That leads to unwanted behaviour for example in the JS-App.

![uibuttons](https://user-images.githubusercontent.com/125398/58466943-fd580080-813a-11e9-8772-46c1adb8cbe5.gif)

The styling should better be applied to class of the element type instead of the global html element.
`<article class="overview--Account Account__Wrapper"></div>`

**Comment by jacogr** [comment]
Sheiße. Well, moved the specific styling to ui-app/Card (now that we have it). The only issue is we don't have branch protection (since then nobody can merge), so ended up doing this - https://github.com/polkadot-js/apps/commit/734b12e6b6daf733d0e4f432b05a59d783a9e700

Not great, but worse reverting and the PR-ing.

**Comment by Stefie** [comment]
True. Now we only have the color/ grey-scale behaviour left, which also doesn't really makes sense everywhere. 
Could you maybe move this https://github.com/polkadot-js/apps/blob/734b12e6b6daf733d0e4f432b05a59d783a9e700/packages/ui-app/src/styles/app.css#L101 over to `packages/ui-app/src/Card.tsx `, too?

Since it's not urgent could also be as part of https://github.com/polkadot-js/apps/pull/1226

**Comment by jacogr** [comment]
I kept it there for the sake of consistency, had it moved out to Card, then put it back again. It is one of those "beauty is in the eye of the beerholder things", both sides have their benefits and drawbacks. (Not particularly picky either way on it and since it is still visible, doesn't detract too much in the js app)
