### ISSUE TITLE
Staking set session key should allow me pick address from address book

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#1231]
I added the public address of my session key to address book but it is not available on in the set session key dialog.

No reason to require me to add session private key.

**Comment by jacogr** [comment]
Agreed. However, it is tricky. Trying there to help people not shoot themselves in the foot by only allowing selection of accounts, ie. where we know they have access to everything. (And it is still lacking as well since it needs to filter by type as well)

Strangely, I have the exact same requirement myself. Don’t have clear ideas how to allow this explicitly and be strict, yet helpful around valid inputs.

(Here the 0.1% can construct and send via the extrinsic app to get around the UI being “helpful” aka “restrictive”)

**Comment by xlc** [comment]
https://github.com/paritytech/substrate/issues/2369 can help

**Comment by jacogr** [comment]
Closing it atm, not quite up to removing the restrictions at this point. (And since there is a "workaround", it is not pretty, but not a complete showstopper either)

However... need to keep this in mind as we add more external account management, e.g. mobile signers, extension signers, may just want a overall flag that say "hey, this is external, but still an account in cases where it is not injected)
