### ISSUE TITLE
Change democracy votes display to horizontal bar

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#1314]
Display in https://github.com/polkadot-js/apps/pull/1313

**Comment by Stefie** [comment]
Some time this week someone colorblind commented on the current votes display on Riot, saying that is impossible to distinguish between `yes` and `no` because they look alike. 
Maybe we can address that while we're at it by:
- choosing 2 colors with a higher contrast or
- adding labels to the horizontal bars (or both)

**Comment by jacogr** [comment]
Ok, so the idea is exactly that -

```
YAY [========== .      ]
NAY [==============]
```

Not touching the colors.

**Comment by Tbaut** [comment]
As a general idea, I've seen recently something like this (in decred)
![image](https://user-images.githubusercontent.com/33178835/59770927-1a4ea200-92a9-11e9-820c-2ce1eabd3ab7.png)

Although the colors (and contrast) are surely wrong for color blinds, I like the idea to show a threashold for supermajority. This makes it simple to see the negative/positive bias as well.

**Comment by jacogr** [comment]
Happy is somebody tries that out as anothe PR, as it stands, just trying to stem the flood here. So just adding a base barchart without frills and fuss. Nothing special - labelled, better use of available space.
