### ISSUE TITLE
[Error] SyntaxError: Unexpected keyword 'function'

### ISSUE THREAD

**Issue by yuzhiyou1990** [polkadot-js/apps#1362]
![image](https://user-images.githubusercontent.com/3783037/60717740-5cd4d780-9f55-11e9-812f-350e0deba4b0.png)

## Running on iOS10 safari

SyntaxError: Unexpected keyword 'function'
SyntaxError: Cannot declare a let variable twice: 'e'.

**Comment by Stefie** [comment]
Could you give us a little more context? I just checked https://polkadot.js.org/apps/  in Safari Mobile on an actual iPhone 7 it all looks normal to me.
![IMG_4749](https://user-images.githubusercontent.com/125398/60718653-8970fb00-9f25-11e9-8e58-4e657146a00a.PNG)

**Comment by Stefie** [comment]
Are you connected to a ChainX node? I saw this as the original description in your other issue https://github.com/polkadot-js/common/issues/432
```
[Error] SyntaxError: Unexpected keyword 'function'
eval (index.js:1990)
./node_modules/@chainx/account/node_modules/@polkadot/wasm-crypto/wasm_bg.js (index.js:1990)
webpack_require (index.js:20)
```

**Comment by yuzhiyou1990** [comment]
> Could you give us a little more context? I just checked https://polkadot.js.org/apps/ in Safari Mobile on an actual iPhone 7 it all looks normal to me.
> ![IMG_4749](https://user-images.githubusercontent.com/125398/60718653-8970fb00-9f25-11e9-8e58-4e657146a00a.PNG)

It works in iOS11,iOS12, but it's not working in iOS10.

**Comment by jacogr** [comment]
The older-not-working is actually intentional, the config for everything states that we will only support the last 2 versions, i.e. https://github.com/polkadot-js/dev/blob/master/packages/dev/config/babel.js#L23

This will be adjusted sometime after https://github.com/polkadot-js/dev/pull/216 to use the browserlist defaults (as opposed to pinning explicitly to only the last 2 versions), and this may or may not help in this specific case. It will certainly expand support, aka https://github.com/browserslist/browserslist/blob/master/index.js#L451 but it still cuts off.

As it stands, won't make any adjuments for this specifically, since it in intentional. Happy to re-visit the decision if a very large number of people are affected by a specific browser exclusion, but the line for old browser support needs to be drawn somewhere.

**Comment by jacogr** [comment]
Closing, stale. Re-open if still an issue.
