### ISSUE TITLE
Accessability

### ISSUE THREAD

**Issue by alekspickle** [polkadot-js/apps#1598]
Is it a lack of time or some deliberate desicion not to do all confirmations not be able to close without a mouse\touchpad, e.g `Enter` or `Ctrl + Enter`?

There may be a lot of confirmations needed and it would improve tests time.

**Comment by jacogr** [comment]
If you look at the commits across all repos in the polkadot-js family, you should get a feeling for the commits by people and what effort is expended. Would certainly love to improve in this area (there has been some work with regards to `Enter` on some dialogs).

Tl:DR Will certainly accept any PRs in this regard

**Comment by alekspickle** [comment]
@jacogr Sure! I'd appreciate If you could point me out where to start. 
I searched maybe there is ready-to-use form component, but could not find it.

**Comment by jacogr** [comment]
Since I'm actually in the process of setting the next round of bounties (together with the W3F), we can include this (nicely scoped), in the list of bounties as well. That will certainly help a bit apart from the "this scratches my itch".

**Comment by alekspickle** [comment]
@jacogr what should I monitor for this?

**Comment by jacogr** [comment]
I'll link them all through to this issue. (Bitesize chunks, just give me a day or two)

**Comment by jacogr** [comment]
My humble apologies - I have not forgotten about this, but am certainly due an update here. The long and the short of it is: we do have a component that currently does _some_ `onEnter` management. However, it is not quite as extensible and re-usable as we are hoping.

So effectively this really is starting from base principles -

- adding a component that can manage the `onEnter` and `onEsc` (this we don't send from inputs)
- implementing this throughout
- untangle what we have with the existing

To make matters slightly more complex as well, we want to rework what we have with the exiting, since i.e. in the case of `TxComponent` we extend and we need to actually use composition.

All this just a long way of saying -

Yes, this needs to be done. Yes, it is currently slightly more messy than anticipated. So as much as I would love to log something as part of a bounty and get it done, it seems we are not (yet) quite setup right to get this done in a painless fashion.

**Comment by alekspickle** [comment]
Thank you for the update! 
I hardly doubt that I will wait for this bounty alone. :smiley:

**Comment by jacogr** [comment]
Working on untangling all those bits, so it is not dropping off the radar. It needs to get done.

**Comment by lucasvo** [comment]
I opened #3139 which covers not just closing a pane/modal with escape but also by clicking outside of the dialog (a common way to close modals). Adding this comment here as well to make sure it does not get lost.

**Comment by chevdor** [comment]
I will try contributing this one as I indeed saw dialogs where it works and some where it does not.
I don't have the bandwidth to do a PR right now but having a list surely will help fixing those issues quicker.

Here is a list of dialogs NOT closing when pressing Enter:
- [ ] authorize transaction - identity.provideJudgement
- [ ] authorize transaction - identity.requestJudgement (enter seems to queue the transaction though)

**Comment by DemiMarie** [comment]
For security reasons, I believe that Enter alone should not necessarily confirm a transaction.  The reason is that it is far too easy to press Enter too many times by accident.  I would prefer if a different keystroke was required.

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
