### ISSUE TITLE
Allow backup of all JSON/Privatekeys from accounts stored

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#176]
Extension of https://github.com/polkadot-js/apps/issues/74, providing a single button (i.e. "Download All" that allows a user to download a backup all the accounts from local storage that they've created by cycling through each Key/Value pair and generating/saving it to a JSON file

**Comment by jacogr** [comment]
Sometime in the future.

**Comment by jacogr** [comment]
Not 100% on-board with this one, let's first see if the functionality comes up as a requirement and then maybe try to investigate and find a way. (Doing this is any proper way is very messy UI-wise since you have multiple passwords to enter, etc.) And there is a workaround that places the "burden" on the user him/her-self.

Closing, maybe can be re-visited if it is valid user-requirement.
