### ISSUE TITLE
Amount always 0

### ISSUE THREAD

**Issue by iammelea** [polkadot-js/apps#1779]
Hello, here

![Screenshot from 2019-10-27 16-37-25](https://user-images.githubusercontent.com/38863192/67637183-17f3f880-f8d8-11e9-856a-acbdfa630c4e.png)
and here

![Screenshot from 2019-10-27 16-32-22](https://user-images.githubusercontent.com/38863192/67637116-90a68500-f8d7-11e9-9057-95fad276f8bd.png)

![Screenshot from 2019-10-27 15-42-49](https://user-images.githubusercontent.com/38863192/67637119-97cd9300-f8d7-11e9-8174-77da90836f07.png)

one suggestion: this 0 here can do, maybe, people vote Zero unless put one amount, I think that if it was not zero it does not allow you to do the TX and avoid empty votes?

also when you want to transfer the same, if you like to transfer 1 and not delete the 0 can send 10 for the mistake. better if it can be empty or so.

thanks for the UI.
Fan here.

**Comment by jacogr** [comment]
Council now defaults to the max locked value, transfer indicates 0 as an error.

On transfer, it does allow you to send, this is probably not something we will change immediately since the idea is always to guide the user, but we are trying not be overly strict when it is not an invalid transaction, i.e. when rejected by the node, the UI should catch it, for anything else, try and warn around "if this really what you want". 

(Happy to revisit the transfer and only allow explicit values if there is broader user support - as of now, we are a step closer, maybe not perfect)
