### ISSUE TITLE
Extrinsics tab: some descriptions of api displayed at dropdown are not complete.

### ISSUE THREAD

**Issue by CaiYiLiang** [polkadot-js/apps#1839]
![image](https://user-images.githubusercontent.com/14360297/68093352-ac261700-fef9-11e9-9aaa-8897fa94f1a8.png)

![image](https://user-images.githubusercontent.com/14360297/68093359-bf38e700-fef9-11e9-8b14-f2a7925b4232.png)

**Comment by jacogr** [comment]
It is a shortend version since there are quite long - extracted directly from the metadata and node code. To get the full description hover over the (?) - but this only applies to the selected item.

If you have suggestions and PRs implementing them, it would be gladly accepted :) (The same applied to storage, same underlying components, same (?) for full on selected)

**Comment by jacogr** [comment]
Closing.
