### ISSUE TITLE
Active Validator list, last epoch being an active Validator, doesn't reset the era counter of validator

### ISSUE THREAD

**Issue by BCpowerup** [polkadot-js/apps#1867]
This is a display issue, when a validator is in the way out of the Active validator list the display should reset, in this case it keeps displaying the point from the previous era.

![image](https://user-images.githubusercontent.com/22130694/68613323-527e9900-0473-11ea-9f77-d1d32fe7f4fb.png)

**Comment by jacogr** [comment]
Thanks for the report, always appreciated. There has sadly been some refresh issues here in the past, thought all have been caught by now... (These are slightly tricky to grab, just due to being indexed with the current operational set... but anyway...)

Just on the screenshot above - what you circled is the commission, not the points. For the last validator no points display.

**Comment by BCpowerup** [comment]
Yes I did noticed that before the commission was hidden under same circumstances, but now is showing up. Is my pleasure to contribute in anyway I can.

**Comment by jacogr** [comment]
There will be some adjustments on the substrate side, specifically https://github.com/paritytech/substrate/issues/4121 -  once that is available, we will make the required updates to pull from the new storage locations for the mapping

**Comment by jacogr** [comment]
Yay! This is finally fixed on Substrate with the new payout model. :)
