### ISSUE TITLE
Re-lock account after sign/send is completed

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#190]
User to be promted for password again on subsequent sends.

(Obviously not in the case of §isTesting§ accounts)

Needs - `lockAccount()` in keyring (or sign with password, that does it automatically)

**Comment by jacogr** [comment]
First part hasSecretKey -> isLocked, contained in https://github.com/polkadot-js/apps/pull/200

**Comment by ltfschoen** [comment]
I've attempted to address this issue in branch luke-190-relock-account-after-sign-send-completed https://github.com/polkadot-js/apps/compare/luke-190-relock-account-after-sign-send-completed?expand=1. I've updated create.ts so if create a new account and then open the modal to send a transaction it shows the password prompt (since beforehand it didn't prompt the user for the password straight after creating an account). But strangely if I debug just before calling the lockAccount function with `pair.isLocked()` it says the pair isn't locked... And when I run `pair.lock()` in lock.ts (the lockAccount function) to lock it whether it's already locked or not, it generates error         `Uncaught (in promise) Error: bad secret key size` from nacl-fast.js.

**Comment by ltfschoen** [comment]
Refer to comments here: https://github.com/polkadot-js/apps/pull/314#issuecomment-421962234.
This is being actioned in branch jg-account-lock https://github.com/polkadot-js/apps/compare/jg-account-lock?expand=1, so PR luke-190-relock-account-after-sign-send-completed was closed.
This is dependent on settings app where user can defined unlocking strategy https://github.com/polkadot-js/apps/issues/86

**Comment by jacogr** [comment]
Closing this for now until it pops up.
