### ISSUE TITLE
Q: Purpose of Null Component 

### ISSUE THREAD

**Issue by vikiival** [polkadot-js/apps#1938]
I would like to ask what is the purpose of Null type/param? 
It would be maybe better to use no argument instead?

**Comment by jacogr** [comment]
The polkadot-JS API has a specific TypeDef for Null - this is equivalent to en empty Tuple or in the case of Rust enum where some have values and some not (the ones without).

**Comment by vikiival** [comment]
So then for example if I want to call extrinsic 
`consensus.noteOffline(offline)`

offline param can be  [], null or undefined?

**Comment by jacogr** [comment]
The API itself is very lenient in encoding - if the param is a vector, passing in an empty array or undefined would yield the default value for that type, an empty array. 

Well, that is for type encoding according to SCALE. There is checking done on the number of required params for calls. So that may throw it out even if the encoding is equivalent.
