### ISSUE TITLE
fee wil be charged for unsuccessful transaction with amount more than current

### ISSUE THREAD

**Issue by edanilov** [polkadot-js/apps#2189]
1. send 1 KSM from one address to another
2. put to the amount field a number > current amount

fee 0.1 will be charged
the transaction will be unsuccessful (insufficient money)

<img width="311" alt="Screen Shot 2020-01-23 at 13 49 36" src="https://user-images.githubusercontent.com/1274876/73058993-cd1d5900-3ea5-11ea-9ed9-490565ff31d0.png">

**Comment by jacogr** [comment]
This is known. It is up to the use to manage. It is the same reason the "max" was removed - with Substrate 2 the fees are estimates (and needs RPC queries, so it is purposefully not done on any dialogs anymore since it is a DDOS vector). 

It can never be 100% estimated since it is based on network conditions, so it will _always_ fall short.

**Comment by jacogr** [comment]
The same reason why https://github.com/polkadot-js/apps/issues/2177 can never be done correctly.
