### ISSUE TITLE
Changing network while in a tab stays in that tab, even if tab unavailable

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#2249]
E.g. visit the "parachains" tab of a network which has it enabled, switch network to one without it (flaming fir), witness the UI die.

**Comment by jacogr** [comment]
Known issue.

 Sadly more effort (for almost no payoff) than there is time for to fix, so it has been like that for 18 months and will probably stay for the next 18 :( 

There is probably a quick hack, but has not been a priority. 

Any PRs for fixes will be appreciated, but otherwise this will stay so what in the bottom of the pile.

**Comment by jacogr** [comment]
Dying is actually weird-ish atm since the new (2 months) content error handler should make things more graceful and has done some elsewhere.  

Will check that anyway, it is not entirely graceful but is meant to protect against full-blown deaths. (Which is the most ugly part)

**Comment by jacogr** [comment]
Closing it. It now "won't die", which is the worst outcome.
