### ISSUE TITLE
Profit estimation is empty

### ISSUE THREAD

**Issue by philipstanislaus** [polkadot-js/apps#2270]
<img width="1552" alt="Bildschirmfoto 2020-02-11 um 16 38 48" src="https://user-images.githubusercontent.com/6912756/74252159-8a54e100-4ced-11ea-8106-def95090bf59.png">

Steps to reproduce: 

1. Go to http://35.198.185.220/#/staking/returns

**Comment by jacogr** [comment]
Ummm... This is caused by "last reward" being 0. So -

- we have a ubug
- it couldn't query the state at that block (rpc node not running in archive(

**Comment by philipstanislaus** [comment]
@jacogr looked into our settings – we indeed do not run our full node in archive mode. What other implications does that have on the Portal?

**Comment by jacogr** [comment]
So the issue is that the normal prune depth in 256 blocks, so everything after 256 blocks is pruned. To get the last reward, need to go back in the state and find the last era end to grab the event. So in the case of Kusama, this is may be -

![image](https://user-images.githubusercontent.com/1424473/74272768-83d76100-4d0f-11ea-864f-c82982d27be8.png)

3.6k blocks. The only other area that will be affected is this -

![image](https://user-images.githubusercontent.com/1424473/74272838-a0739900-4d0f-11ea-8d22-b8b559120967.png)

Here it goes back around 10 days worth of blocks to graph the end-of-era stuff. 

So with this in mind, it doesn't need to be "complete archive", but greater than normal 256 with around 10 days worth of blocks to have everything show. The only way to get access to some of this info is via state, so it needs to go back - not to the beginning of time, but a recent history.

**Comment by philipstanislaus** [comment]
Awesome, thanks for the detailed answer!
