### ISSUE TITLE
gap of 100 epochs at "validator stats" tab

### ISSUE THREAD

**Issue by illlefr4u** [polkadot-js/apps#2284]
I think it’s a mistake, but maybe i dont understand something.  I have missed 86 epochs (1851 and next one is 1937) in the "Validator stats" tab . I’m also sure that at the epoch 1940 I received rewards about 2.6 ksm, and I saw it in this tab right after i received it (5 min after), but for some reason only 0.153 is currently displayed (unfortunately I did not find how to see exactly my awards as a validator for Polkascan or anywhere else).
to reproduce: my address is DfiSM1qqP11ECaekbA64L2ENcsWEpGk8df8wf1LAfV2sBd4
![miss_eras](https://user-images.githubusercontent.com/21253681/74686048-05673d00-51af-11ea-951d-8d0e668b0228.png)

**Comment by jacogr** [comment]
The staking rewards are undergoing a Substrate overhaul which will allow for recent rewards to be claimed along with seeing the actual rewards per era.

At this point all these are estimated - since the info comes from various sources. And actually, when you drop off, it really inaccurate (something the above aims to address).

**Comment by jacogr** [comment]
Will be reworked in #2289

**Comment by jacogr** [comment]
Closing this. The lazy payouts are live on Kusama - with this the actual graphs are pulled directly from state (so it is a bit slower), but always reflects 100% what is actual hapenning.
