### ISSUE TITLE
How to use FormatBalance?

### ISSUE THREAD

**Issue by waylandc** [polkadot-js/apps#2390]
If I wish to display more detail than the default (unit is M), do I do it with the react-query/FormatBalance component?

Could you show me how to display entire balance without using any M or K units?

**Comment by jacogr** [comment]
`FormatBalance` is not meant to be a "generic" but rather a "consistent" for display in the apps UI. That means that all balances are displayed in those units, so anything above >1M gets displayed in M, otherwise only default. and everywhere it is exactly the same.

If you want a different display, it is best to make your own component, possible using the `@polkadot/util` formatBalance r another solution.
