### ISSUE TITLE
Automatically unstake/unnominate when balance 0

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#244]
After getting slashed, validators and nominators might have 0 Dots. Because of this, it's impossible to unstake/unnominate. It would be great if we can unnominate/unstake any account that has 0 Dots.
![image](https://user-images.githubusercontent.com/33178835/44398983-23b29500-a546-11e8-915a-27e5233cf2c9.png)

**Comment by jacogr** [comment]
Not 100% what you are suggesting - as soon as the balance drops to 0 (or technically the existential amount), it does not have the required fees to send any transactions. Hence clicking "unnominate" (or doing it automagically) is always doomed to fail as soon as the tx hits the node. 

With no available balance no tx can go through since the fees cannot be paid.

So this is the backdrop. It certainly is possible to setup (user-configured rules), i.e. "unstake when the nominated balance drops to <insert value here> amount" (assuming the UI is operational and running at that point in time). 

Is this type of rule setup your suggestion?

**Comment by Tbaut** [comment]
Got it. I actually didn't suggest anything, I was wondering if there was a way to unstake with 0 Dots.

The problem is that I have my accounts stuck in a UI with buttons that "do nothing" obviously because I don't have Dots on it. I have no incentive to add some Dots to unstake as this would only cost money. The only thing that a user can do is to "forget" the account. I guess that's good enough.

**Comment by chevdor** [comment]
I think this should be done in polkadot/substrate itself, not in the UI.
See https://github.com/paritytech/substrate/issues/457

Then the UI should just get notified and refresh what is displayed accordingly.
