### ISSUE TITLE
Querying Balances -> account returns empty result

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#2442]
When submitting the "Chain State" -> "balances" -> "account" query, Apps always returns a struct filled with zeros. Specifically:

```javascript
{
  free: 0,
  reserved: 0,
  miscFrozen: 0,
  feeFrozen: 0
}
```

Apps _does_ display the correct account balances on the "Accounts" tab. This issue is reproducible on Kusama and the node template (and probably other chains).

**Comment by jacogr** [comment]
The "issue" is expected. Balances are not stored in balances.account. It is only used for chains that do not have system.account.

So the apps UI is correct for those chains - the entries are empty on-chain, as expected. It is also correct in displaying the balances since it gets it from the correct storage location.
