### ISSUE TITLE
A Bug about polkadot.js.org/apps/#/extrinsics

### ISSUE THREAD

**Issue by Lawliet-Chan** [polkadot-js/apps#2464]
I met a bug about  polkadotjs/apps.
I  run my  substrate chain successfully(repo: https://github.com/Lawliet-Chan/bhd-chain) and  open https://polkadot.js.org/apps/#/extrinsics.
When I click  'submit transaction' , It returns me an error:
```
1002: Verification Error: Execution(ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature")): RuntimeApi("Execution(ApiError(\"Could not convert parameter `tx` between node and runtime: No such
```
My substrate project has no custom structs or enums. 

![1381585308579_ pic](https://user-images.githubusercontent.com/12938445/77753756-0ff5db80-7065-11ea-9bc2-d5011b002c44.jpg)
![1391585308579_ pic_hd](https://user-images.githubusercontent.com/12938445/77753773-16845300-7065-11ea-8958-c24f1ffbf5f9.jpg)
![1401585308579_ pic](https://user-images.githubusercontent.com/12938445/77753780-1ab07080-7065-11ea-801e-5add89bea01b.jpg)

**Comment by jacogr** [comment]
This is not an API bug. You have used node-template which is not compatible with Substrate master node - since you did that, you need to add the specific types for the customisations your have made.

Specifically, this was done on your project - https://github.com/Lawliet-Chan/bhd-chain/blob/master/runtime/src/lib.rs#L247

Which does not match with the Substrate master node (not node-template) types for the differences.

See this https://polkadot.js.org/api/start/types.extend.html#impact-on-extrinsics
