### ISSUE TITLE
Link to Polkassembly for treasury, motions, proposals or referenda

### ISSUE THREAD

**Issue by Tbaut** [polkadot-js/apps#2531]
Would you accept a PR if we add links to the corresponding treasury, motions, proposals and referenda the same way it's done for Polkascan or Commonwealth?

**Comment by jacogr** [comment]
Yes, there is no horse in this race from a linking perspective.

Having said that, at this point there are 3 (4 with this) will probably need to take a look at the functionality of the actual platforms at some point and where there is competing overlap with apps functionality, would probably remove it. (Honestly have not taken a look at of these in-depth since it is not on my personal user-path, so have no idea apart from "it is there". )
