### ISSUE TITLE
Addresses are not properly cnp-able across the UI

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#264]
Version of the UI: polkadot-js-ui v0.19.51

In the past, I could transfer to any account.
This no longer work if the recipient account is not in your address book.

![image](https://user-images.githubusercontent.com/738724/44596219-ba43b800-a7cb-11e8-96a8-5b0c81ee42b5.png)

**Comment by ltfschoen** [comment]
I've gone through the following steps to reproduce your issue so far.

After I Create Account at http://localhost:3000/#/accounts, it stays at that url but displays that account in the Edit Account tab.

<img width="493" alt="screen shot 2018-08-24 at 10 18 14 pm" src="https://user-images.githubusercontent.com/6226175/44603532-ab6cfd80-a7eb-11e8-9eee-f1fbd66610f0.png">

If I go to Addresses http://localhost:3000/#/addresses. I have no accounts in the address book.

<img width="533" alt="screen shot 2018-08-24 at 10 19 48 pm" src="https://user-images.githubusercontent.com/6226175/44603599-da836f00-a7eb-11e8-9aa4-f71fb4e318c0.png">

Then when we go to Extrinsics http://localhost:3000/#/extrinsics to make a transaction, by default it's configured to transfer 1 DOT of stake from my account to my same account, even if I don't have any DOTs.

<img width="835" alt="screen shot 2018-08-24 at 10 20 24 pm" src="https://user-images.githubusercontent.com/6226175/44603764-73b28580-a7ec-11e8-84e3-65884c1a4837.png">

If I then click on the input field selection box that is displaying my Account Name and Account ID (underneath the label "recipient: AccountId"), I can start entering a custom recipient Account ID, as you have shown.

**Comment by chevdor** [comment]
Try sending 1 DOT to any address that is *not* one of your accounts and *not* in your **Addresses**.

**Comment by jacogr** [comment]
1 DOT won't work - it is less than the existential amount, so you will lose -

1. The 1 DOT tranferred
2. The fee to create an account (I believe - not sure 100% due to #4)
3. The transfer fee
4. However since the balance  of the recipient is <500 (existential amount), it will just be removed, treated as dust.

Transfer test (5k) - https://youtu.be/tFS8dYRB8yQ

**Comment by jacogr** [comment]
Do you possibly have a space before/after the address? 

I don't think we strip those - and 2 mins later I'm certain we don't, i.e. https://github.com/polkadot-js/apps/blob/cf8f2064f88bd79d8ac81251d70e7ab064f6fb38/packages/ui-app/src/InputAddress/index.tsx#L176

**Comment by chevdor** [comment]
I copy paste from storage using a double click on the address, and... oh, look at that:
![image](https://user-images.githubusercontent.com/738724/44615797-f403d580-a842-11e8-9014-943e1fcdbd9d.png)

It seems to be selecting the next index as well. So I don´t have a space when I paste but an extra digit at the end. That explains.

A fix would be to change:
`<div class="ui--Param-text">5FVxKvW1pQUWT85jh7yD7A1ATzBjSVjgDL8HxUXsvZxqfQkx</div>` into
`<div class="ui--Param-text">5FVxKvW1pQUWT85jh7yD7A1ATzBjSVjgDL8HxUXsvZxqfQkx </div>`

Doing so, there is no need to strip the trailing spaces but I am sure there will be cases where it will be an issue so stripping and leading/trailing spaces probably would not hurt.

**Comment by jacogr** [comment]
Yes, I think the `.trim()` needs to be in place - people can copy from anywhere, e.g. chat, mail, etc. 

Additionally, we may want to just look at a mini copy button next to AddressMini and the above rendering.

**Comment by jacogr** [comment]
Summary of top-of-mind issues that would need a look at -

1. AddressInput needs `.trim()` on query inputs
2. Param rendering needs to remove extra space at end (as per @chevdor comment above)
3. (Investigate) adding mini copy button to AddressMini
4. (Possibly) start using AddressMini is Param address rendering
5. (Investigate) using error alerts/messages when things don't match up (instead of just not showing as per original screenshot). Possibilities for errors - (a) address too long, (b) wrong address format/checksum
