### ISSUE TITLE
Confusing voting colors

### ISSUE THREAD

**Issue by chevdor** [polkadot-js/apps#282]
The current colors really tell the user they should click NO.

I know it goes of the current UI track but for this one case, I think a red/green colouring would be better understood.

I can also see people getting confused with the Aye/Nay options so I would propose (also for color blinds) to add icons such as 👍 or 👎  

![image](https://user-images.githubusercontent.com/738724/45081570-c565e480-b0f7-11e8-9a67-dbb6b2f7f616.png)

**Comment by jacogr** [comment]
cc @Tbaut

**Comment by Tbaut** [comment]
What do you think about #64bebe that would look like
![image](https://user-images.githubusercontent.com/33178835/45170212-a3578980-b1ff-11e8-8264-8ebc10dad4e8.png)

**Comment by jacogr** [comment]
That is actually quite nice and green-ish. I think the left <-> right swap helps here as well, closer to what people are generally used to. 

I would stick to "aye" and "nay" for now... it just aligns better network-wide, i.e. polkadash

Q: Did we actually change the graph colours are well? I don't think so, my mistake.

**Comment by chevdor** [comment]
I agree, the color works much better and the swap makes more sense.

**Comment by Tbaut** [comment]
>Did we actually change the graph colours are well? I don't think so, my mistake

I'll make sure to update it in the related PR.

**Comment by jacogr** [comment]
*grumble* I can see I did the democracy stuff fast to make sure we actually have something. So apart from swearing at myself, here are the related lines for the graphs -

https://github.com/polkadot-js/apps/blob/master/packages/app-democracy/src/Referendum.tsx#L22

Sadly no CSS here since the underlying library uses the colours passed-in to render the SVG dynamically. (Which means we probably want to add a comment in the CSS, i.e. "when you change this, look over there as well")
