### ISSUE TITLE
Allow claims using only Polkadot address

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#2838]
Claims transactions do not require a signature from the Polkadot private key. Allow addresses from [My Contacts](https://polkadot.js.org/apps/#/accounts/contacts) to construct and submit claims from Ethereum.

Currently the Claims page does allow you to paste in an address but it stays invisible.

**Comment by jacogr** [comment]
The problem was this was half tested - so had to disable that functionality today’s since there was a flood of reports since attests were broken where the addresses were just pasted.  

So atm, this is a limitation that was mentioned by Logan in the PR, but it is the best of two bad choices that had to be made until it can be properly fixed and completely re-tested.

**Comment by amaurymartiny** [comment]
@jacogr I'm about to make a PR that:

- revert #2830
- if we see that the selected address already preclaimed (attest flow), then:
    - if it's an actual account, then show the "I agree" green box
    - if it's not an account, then show a red box with an error
- and don't change anything in the claimAttest flow

does that sound good to you?

**Comment by jacogr** [comment]
As long as it is properly tested for all scenarios.
