### ISSUE TITLE
Show claims page without owned accounts

### ISSUE THREAD

**Issue by joepetrowski** [polkadot-js/apps#2882]
Since https://github.com/polkadot-js/apps/pull/2848 users can claim with an account in Contacts or pasting the address, but the Claims page only shows if a user has an owned account. Since not everyone will have an owned account, always show the Claims page on the sidebar.

**Comment by jacogr** [comment]
Here - https://github.com/polkadot-js/apps/blob/master/packages/apps-routing/src/claims.ts#L13

May break in horrible ways without.

**Comment by joepetrowski** [comment]
How so? Obviously don't want to break it, but if someone wants to claim to an address, generating a throwaway account just to get the screen seems like an arbitrary hurdle.

Would a better alternative be on the Accounts page have a link to "Claim DOTs to an external address" that takes you to the Claims page, but doesn't display it in the sidebar?

**Comment by jacogr** [comment]
It is "no arbitrary hurdle" - the apps UI was fuly build around the notion that users have accounts and perform actions on those accounts. This applies to everything, including components. `needAccounts` is set anywhere where users deal with anything relating to transactions and/or account dropdowns. 

So that assumption pulls through everywhere. For instance, with an accounts dropdown, you need accounts (it is used here), otherwise it may yield invalid results and even crash.

There is x resources, y time - so assumptions need to be made around things that can actually be tested, verified, maintained and continue to be done.

**Comment by jacogr** [comment]
And notice I said _may_ have issues - it all depends on how it is specifically used and which additional checks are around it.

**Comment by joepetrowski** [comment]
That's fair and I understand that assumption. But a lot of people want to claim to addresses elsewhere so we should either (1) make an option within Apps or (2) say that this is outside the expected use of Apps and make a separate claims site.

**Comment by jacogr** [comment]
Well, it is certainly outside of the "expected use" - hence my comments above. I am not against the idea, hence it is not a "wontfix".

I cannot speak for if there should be a different site or not, that is also outside of the apps realm.

Well tested PRs always welcome. (Which could be as simple to disabling the flag and then re-testing against all possibilities)

**Comment by jacogr** [comment]
Closing this. 

Like any urgent vs important discussion (which is how the next-up it prioritized), this doesn't mean it it won't add value, but rather that it won't get any focus. So the options are to have it sit gathering more dust or just be honest that based on capacity and focus-wise it will not get addressed.

If there is appetite for PRs to move things in the direction intended here, they will always be welcome.
