### ISSUE TITLE
Support proxy setting via accounts (proxy module)

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#2887]
Option in accounts drop-down when proxy module is available. Open dialog to set the proxy for the account for a specific type.

**Comment by jacogr** [comment]
- [x] Signer
- [x] Proxied accounts (external)
- [ ] Setup dialog

**Comment by Tbaut** [comment]
I'm willing to take this on, but I'm unsure what the end result should look like. Should we add a menu to `add proxy` from the right ellipsis one, and then simply let users select the type?

Now I understand what you mean with the display headache, showing account icons for each proxy type is def too much info at once. 

One idea would be to use an `Expandable` "X accounts" and once expanded we show all the accounts with their proxy type (with `AddressMini`)
![image](https://user-images.githubusercontent.com/33178835/87157066-f009c100-c2bd-11ea-9eb2-4b91953c9f69.png)

 I just leaned about `proxy.anonymous` extrinsic, I guess this is out of the question for this issue is it?

**Comment by jacogr** [comment]
The anon proxy should leave for a next round.

So the display is a huge issue -

- we have 3 columns, parent, delegation & proxy
- these are mostly empty
- they take up a lot of space with "something" in at least one

For proxy & delegation, we may actually be able to remove the columns completely and just have a badge indicator and then the management modal will show all and allow update. For these, once set it is relatively stable non-changing information, so doesn't need to be seen "all-the-time". (Additionally the Sidebar can actually show that info, not only fo own accounts, but for all)

**Comment by Tbaut** [comment]
Sounds good, what kind of badge do you think about? A round icon for each badge (I guess a tooltip to explain what they are about is necessary)? Should those badges be in a dedicated column? Clicking on the delegation badge would open the managing modal (we'd use a different modal for delegation and proxy I suppose?)
Lastly, not sure how the modal should look like, we don't have anything in place like this yet do we? Should it present the information, read only, and provide buttons that would fire yet another modal on top to change things.

**Comment by jacogr** [comment]
Nested modals are a no-go (even the signer modal on top of others is actually really bad...)

Modal can just show everything and allow you to edit, submit sends it to the chain. so see it as a current-settings edit. SideBar can have a static/quick view.

Badges are already in place for accounts. One global missing thing (everywhere) is a badge legend per page where they are used, will need to get in since tooltips are exceptionally expensive (hence removed from pages like staking) and without it is really nn-descriptive.

**Comment by Tbaut** [comment]
Ok I had a play through with bagdes, and I guess using a dedicated icon for proxy and delegation could make it distinguinshable.
> One global missing thing (everywhere) is a badge legend per page where they are used, will need to get in since tooltips are exceptionally expensive

I understand it's expensive for super large pages, but I guess it's manageable for account don't you think?
I'll start off by moving the delegation to a badge.
However for proxies, it sounds tricky to show all info about all proxied account for each type (non transfer, governance..) on one modal, all while allowing edition.

**Comment by jacogr** [comment]
For accounts can have badges, however we do have users with 150+ accounts - so generally, I have used hovers in the past (see e.g. multisig) since it is not for _all_ accounts, but a subset. So should be ok.

The showing is not an issue, it is a mapping from type -> account. (If you end up with 10's, which is not the 99.9% usecase, yes, it can be unwieldly)

**Comment by Tbaut** [comment]
One thing I don't get is the meaning of `BalanceOf` in `proxies(AccountId): (Vec<(AccountId,ProxyType)>,BalanceOf)`.

To have a good UX and a good overview with the set of methods we have, I guess it'll require the use of `batch` which is not ideal because it obfuscates what is effectively sent.

This is how I see the UI form the model:
![image](https://user-images.githubusercontent.com/33178835/87666783-8845f100-c769-11ea-8635-2f6736311c9d.png)
- At the top the selected account to add a proxy to.
- below, read-only, the previously defined proxies if any (in my screen it's BOB_STASH for `Governance`). They are read-only but can be removed by clicking on the X, this adds a `proxy.removeProxy` call to the batch.
- Any new proxy can be added (in my screen, it's EVE for `Any`), this adds a `proxy.addProxy` call to the batch.
- Not represented, we can have a "delete proxies" button at the bottom which would trigger a `proxy.removeProxies`

**Comment by jacogr** [comment]
Yeap, batch is the right way to handle these. BalanceOf is the amount on deposit, based on the proxy fees.
