### ISSUE TITLE
Divider in Button Group is being highlighted on hover

### ISSUE THREAD

**Issue by igorline** [polkadot-js/apps#2897]
It looks like there's a button missing as cursor is also changing to a pointer.

![image](https://user-images.githubusercontent.com/1465430/83978941-26dd6780-a90b-11ea-852e-421c01e4898e.png)

Fix should be easy, but I don't know how the divider should look like and act to submit a PR :)

**Comment by jacogr** [comment]
Weird. Not sure how I have _not_ seen that for so long. Would drive my OCD crazy.

It gets auto-added to rows as an element, styling here - https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/Button/Divider.tsx

I would lie if I remember exactly as to why this is auto-added to all buttons row. But it basically should just be invisible (where actually added), and completely removed from https://github.com/polkadot-js/apps/blob/master/packages/react-components/src/Button/Group.tsx#L20 (As I said I cannot recall exacly, but think it had to do with corner rounding, which is not an issue anymore since the rows all have spacing between the buttons now)

**Comment by jacogr** [comment]
100%
