### ISSUE TITLE
Broken claims page on Kusama? 

### ISSUE THREAD

**Issue by joshua-mir** [polkadot-js/apps#2939]
The claims page on Kusama appears to claim that accounts do not have valid claims when according to chainstate, they do.

(verified with a couple of random addresses from https://gist.github.com/joshua-mir/b9c78bd8524cc9db2b1e36d4042aab78), so I assume this applies to all claims.

**Comment by jacogr** [comment]
The runtime upgrade broke it. The claims page detects it as "invalid" and since there is no statement, doesn't show the claims. So indeed, the logic is broken - had the same issue with somebody on CC1 which didn't have a statement. (He got it working through this branch https://github.com/polkadot-js/apps/tree/jg-no-statementKind)

**Comment by jacogr** [comment]
Closed in #2941
