### ISSUE TITLE
Staking payout page is too slow

### ISSUE THREAD

**Issue by kaichaosun** [polkadot-js/apps#2977]
## Why is it slow
From Jaco:
> It has to load the last 84 eras with all validator information and then match on them - so it current does 350 validators with 4 queries each for 84 eras. It is as fast as it can be from a front-end perspective.
> The long and the short of it is that the nominators/validators wanted one single payout - to handle that from a state perspective means you need to get the full history.

## Is it possible to make it better from user perspective? 
Potentially make a 3rd party system to record the payout info and query this API instead of getting the onchain data. Is it make sense, or other solutions?

**Comment by jacogr** [comment]
So the bad news is that as the number of validators increase, it gets worse. So the bump from 275 to 350 basically made it (350/275 = 1.27) 27% slower - not immediate, but 84 eras after the bump it is at the worst.

This is compounded by the fact that the apps UI only ever relies on on-chain data, so it will never had any reliance on centralized 3rd parties. The move is fully towards no hosting, no reliance and IPFS deployments. So out in the ecosystem there is a gap for a centralized service to certainly make this better by using database infrastructure.

For stuff like the payouts there is memory caching done - the amount of data is too big for storage caching in the browser, it blows through the 5MB limit in the browser with even a limited set of eras, which would have aleviated some pain. So there is some (limited) caching if you go to the page and leave and come back, it already has the previous data retrieved. (So per session is is optimal, per fresh session, not at all)

Above I mentioned "in the browser", for the Electron apps the same does not apply since you can have larger filesystem limits - so there is an open item to add a filesystem cache (same as the in-memory, just persisted) to the derive infrastructure (which doesn't only then have an impact with payouts, but actually elsewhere in staking as well).

**Comment by jacogr** [comment]
Closing. Recent changes has been to retrieve a subset of the eras (selectable), which cuts the time by 75% as a default (assuming recently claimed).
