### ISSUE TITLE
[page-contracts]: encoding issues

### ISSUE THREAD

**Issue by akru** [polkadot-js/apps#3037]
**Description**

* Substrate: `2.0.0-rc3`
* Ink!: `latest-v2`
* PolkadotJS/Apps: `v0.47.0-beta.3`

Latest `page-contracts` argument/result codec looks incompatible with latest substrate contracts pallet `2.0.0-rc3`.

```
Call results:
get(): bool 24.06.2020 12:20:38
()
```

I got `()` instead of boolean value. Could you update me a state of support, please.

**Comment by jacogr** [comment]
What are you calling specifically? 

The API/Apps always tracks the types from latest substrate master branch.

**Comment by akru** [comment]
I’ve just tried to repeat smart contract workshop on latest crates substrate.

**Comment by jacogr** [comment]
So which specific call did you make where you got something unexpected?

**Comment by akru** [comment]
It was simple “get()” RPC call to the canonical flipper contract, I got () instead of Boolean.

**Comment by jacogr** [comment]
There could be some issue for the deprecated ABIs, honestly not sure. So why I am saying "deprecated" in because it has been replaced in Substrate with a new updated metadata format. So support is in-progress for that on the API layer which then will filter through to the UI.

So even if there are encoding issues atm, they will not be fixed since it it is throw-away effort at this point.

**Comment by akru** [comment]
Could you explain me please @jacogr, which substrate version is compatible with current contracts page?

**Comment by jacogr** [comment]
You need to use Substrate master which has issues fixed on the RPCs and supports the weight-based upgrades to the gas. Anything less than that will yield various issues that may be UI related and may not be.

For optimal results, I would completely hold off for now since there are various known issues that will not be addressed before the new ABI formats is supported. The contracts API/UI does not get much love atm, apart from the rewrite that was done a couple of weeks ago since it is in a holding pattern for the ABI update.

**Comment by akru** [comment]
Got it, thank you! Looking forward to stabilizing smart contracts features.

**Comment by jacogr** [comment]
O, yes, me too. It is difficult with everything in flux. Quite frustrating from all angles.
