### ISSUE TITLE
Signer event inspection for as_*

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#3072]
Expand the event inspection with some extra indicators (warning/errors) based on the events. For instance, when sending `as_proxy` the `ProxyExecuted` can have `BadOrigin` in the DispatchResult, however the `ExtrinsicSuccess` event does occur.

Same with batches, we can have an interrupted batch, however the overall tx would be ok.

Obviously really don't want to go down a route where each module, all the extrinsics for that modules and all the events for those are inspected, however there are some that can possibly be further interrogated -

- as_batch (util)
- as_derivative (util)
- as_multi/approve_as_multi (multisig)
- as_proxy (proxy)
- as_sudo (sudo)

**Comment by gilescope** [comment]
Incomplete xcm sends I would add to this list.

```
polkadotXcm.Attempted
Execution of an XCM message was attempted. 
XcmV2TraitsOutcome

{
  Incomplete: [
```

It's pretty clear we need a generic solution to this rather than UIs having adhoc lists of things to check for.

Dose this need to an issue in substrate/polkadot or does the UI have enough information in the metadata to deduce generically if things are deeply successful? (I do understand that we can't report on the success or failure on delivery of the xcm message but people will expect errors in sending of the message to be flagged).
