### ISSUE TITLE
Claims page on Polkadot does not continue to attest prompt

### ISSUE THREAD

**Issue by joshua-mir** [polkadot-js/apps#3128]
For accounts with a preclaim on Polkadot, the claims page seems not to allow them to continue to the attestation stage after entering their polkadot address, instead, the button disappears and no prompt displays. 

version: v0.48.0-beta.16

**Comment by jacogr** [comment]
There has been no changes on claims since the initial version. Here would need a re-producible case.

**Comment by joshua-mir** [comment]
originally reported by `13GgPPnTNUjBu8wtYPEPknXicb31NMVxhSdLt8CoEgXD1bTX`

my own video reproduction:
https://youtu.be/AxLSZHdRKVE

(you'll have to trust I've tested this on desktop as well 😅)

**Comment by jacogr** [comment]
It is due to this -

![image](https://user-images.githubusercontent.com/1424473/86536854-39879400-beeb-11ea-9e97-370c814eb003.png)

The associated Ethereum address does not have -

- a statement kind
- a balance (or vested amount)

**Comment by lsaether** [comment]
I'd bet this is because they claimed using the `claimAttest` with the ethereum key directly instead of doing the `attest` from the Polkadot address. That would explain why the preclaims storage is still sticking around but there's no associated claim data. 

AFAICT there's no action to be taken by this account, rather the problem is due to some storage that needs to be cleaned up. At some point it would make sense to scan for all dangling preclaims and clean them up.

**Comment by jacogr** [comment]
I guess this would mean an adjustment to the UI to go through the tree to check owned, check ethereum and check vested/balances and apply another filters in the prompts around these. (As of no it will continue pointing you to attest while it is not valid)
