### ISSUE TITLE
Same-type param queries yields disabled storage

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#324]
This is a variant of https://github.com/polkadot-js/apps/issues/286 

1. Go to Chain state
2. Select staking
3. select bondageOf - it should work
4. now swap to currentNominatorsFor

The button is disabled when it should be enabled.

**Comment by ltfschoen** [comment]
I've taken a quick look. It appears to be because both the keys `bondageOf(who)` and `currentNominatorsFor(who)` require the `param` named `who` of type `AccountId` to be provided, however the value passed to the newState and assigned to state value `params` is `
[ {isValid: false, type: "AccountId", value: undefined} ]`, where isValid is set to false in the newState method because params[0][value] is undefined.
