### ISSUE TITLE
Node Info doesn't work on Kusama

### ISSUE THREAD

**Issue by yangwao** [polkadot-js/apps#3250]
I've just noticed that something has changed in the API of Substrate/Polkadot-JS and **Node Info** doesn't work for us in @kodadot any more. 

The error seems the same on our side as on original Apps https://polkadot.js.org/apps/#/explorer/node

![image](https://user-images.githubusercontent.com/5887929/88173845-9097a380-cc23-11ea-896d-5742745b2ef2.png)

![image](https://user-images.githubusercontent.com/5887929/88173961-bc1a8e00-cc23-11ea-9d97-eae0a3dc9ca5.png)

**Comment by jacogr** [comment]
It is actually expected. Since it is a protected/unsafe API, it needs to be explicitly exposed. Sadly aware of it, however the protected RPCs still appear in rpc_methods, so it is not filtered (until used). Have a local branch that attempts to work around it since the latest updates to the structures, will eventually get around to pushing when there is less chaos.
