### ISSUE TITLE
Making the tipping ux in polkadot.js better

### ISSUE THREAD

**Issue by rrtti** [polkadot-js/apps#3296]
To speed up the process of tipping:

1. adding a "quick tip" button which sends a transaction that tips the existing median amountm the UX would be reduced from three buttons and one text box entry by one button and no text entry. 
2. batch together many such tips so you only need to review one transaction - working as a local txpool you can sign once.

**Comment by jacogr** [comment]
Ok, so the batching has been around for quite some time - I actually thought I had it logged, I don't. Will split it out since it is not really tipping related (although something specific can be done for tipping), but rather it is a general `TxButton` -> queue -> utility.batch operation. (I think the reason it is not logged is that it actually precedes utility.batch)

Will log, link.

**Comment by jacogr** [comment]
Additional point on improving the experience - allow the normal fill-in-tip to auto-populate the median value (that is available now)
