### ISSUE TITLE
Hard coded app-transfer Transfer Size 

### ISSUE THREAD

**Issue by yjkimjunior** [polkadot-js/apps#337]
In `app-transfers/Fees.tsx`

"Based on the actual transaction we should calculate the size. However currently because of the "fully distant" nature of the signer component, we cannot really properly calculate the final size. So count it... and then fix it. (This needs to be sorted)"

Relevant issue: #294

**Comment by ltfschoen** [comment]
Below are my notes based on discussions with @jacogr :

We cannot update the Extrinsics component to use the 'fees' observable because we cannot determine the size of the tx in there yet, until the FIXME for the hardcoding of the size is resolved in the Transfer App (which is already wrong for poc-3) so we can get the final signed size `tx-size-in-bytes` at the moment, where `fee = baseTxFee + (tx-size-in-bytes * feePerByte)`. 
The size is currently hardcoded to 156 in the Transfer App, which assumes only publicKeys and is not the case when we get to poc-3. 
It is used in the Transfer App so the Balance input field is invalid (appears "red" and Submit Transaction button disabled) when the value entered plus fees exceeds the sender's balance.
There is an issue logged that goes through all the fees. Signer needs to have a method exposed that takes all the params as given, encodes the extrinsic and returns the total fee or size.
There is nothing stopping us, it just needs to be done properly. As Signer does not even know in the modal what the final size would be, that would be the first area to fix by showing the fees in there, and then the in the apps, and then maybe Extrinsics if it still has a use.

**Comment by jacogr** [comment]
Should only tackle this after https://github.com/polkadot-js/api/issues/161 since I'm not quite sure yet about the impacts of new codecs and the different extrisics format for poc-3 yet. Getting closer as we muddle through. Theoretically, it _should_ not have too much of an impact since it is still length-drive, so regardless of how we encode, as long as there is a size.

**Comment by jacogr** [comment]
Some parts done in https://github.com/polkadot-js/apps/pull/350

Halfway there... now the signature size is hardcoded, extrinsic size calculated

**Comment by jacogr** [comment]
Rework in #350, closed for "next" to go live with poc-3.
