### ISSUE TITLE
Consider moving notifications to the bottom

### ISSUE THREAD

**Issue by apopiak** [polkadot-js/apps#3439]
When notifications are triggered in polkadot-js apps they often show up on top of UI elements.
I can solve this by closing them, but I need to manually do that in order to interact with the UI.
I would suggest moving the notifications to the bottom of the screen so that the UI elements are free to be interacted with.

**Comment by jacogr** [comment]
Unlikely. It actually started off there. 

The issue is that any tx with more than one even clutters up the display anyway. So effectively the whole left is actually lost atm with popups. So what you are asking for can be done, but it is unlikely to be done since it will not improve the situation and probably make it worse in some respects since the "close all" will not be in a location that is not easily reachable.

With all that said, it has actually been in the back of my mind and very recently from of my mind (alongside https://github.com/polkadot-js/apps/pull/3422) with the idea to condense it completely into 1 somewhere on that bar (or just below) and give a condensed/expandable view. Well, exactly how is not quite fully clear yet, but will prototype what is in my head when there is a gap and see where it leads.

**Comment by jacogr** [comment]
Replaced by https://github.com/polkadot-js/apps/issues/3466
