### ISSUE TITLE
Unable to unstake from validator intentions

### ISSUE THREAD

**Issue by mnugumanova** [polkadot-js/apps#349]
1. Navigate to Extrinsic in poc2 Ui
2. Unstake()
Gas price was deducted and the transaction has been sent
3. Wait till the end of the era
At this point, I would expect my address to disappear from the list of the intentions

Note: Account in question is 5C6vE4nNSRvSG1upbwgMqGnzx4DSvPJRNecYfeahQRPbaLTa

You could probably read from the blockchain history that there are 10 transactions associated with this account. Last 3 were my attempts to unstake.

**Comment by jacogr** [comment]
If the transaction shows up in a block, it means it has been sent to the node and accepted by the validators. At that point, nothing the UI can do to influence or change. 

If you could link to specific block with the transaction, could take a look - the index sent along should be the 0-based index in the validator list.

**Comment by mnugumanova** [comment]
Can you please check if that the case if validator was nominated by someone else? I just tried and it still doesn't work @jacogr

**Comment by jacogr** [comment]
Ok... so, we had a chat about this offline, thanks for that @mnugumanova . 

The issue is making the call via the Extrinsics app and not via the Staking app where all the params has been wrapped into a button. In this case where you manually need to construct with params, the "index" parameter needs to be specified as the index of the validator (0-based) in the intentions list. These calls are tricky when doing it directly, same with the unnominate one, without knowing 100%, there is no way anybody can guess the values.

Seems like the documentation is very outdated in this case :( (It is a good one understanding the inner workings, but in this case I also missed this - we really should clear up the HOWTOs to both show using the staking app and then being clear on how to construct the params in the case of making the call via Extrinsics)

**Comment by mnugumanova** [comment]
@jacogr I've unnominated myself by clicking Staking -> Account Actions -> unnominate.
Here is an odd behavior I see after that:
1. My address is still shown under current list of validators in the staking tab (even after new era started)
2. I no longer have 3 nominators that i used to have before unstake
3. When I query chain state for session.validators I could see myself in the list but not when i query staking.intensions (i believe that is desired behavior)
5. The Staking tab shows that there are 30 validators and 31 intentions (desired), yet there are 2 accounts displayed in the list of intentions 
<img width="1283" alt="screen shot 2018-10-25 at 12 46 12 am" src="https://user-images.githubusercontent.com/8264666/47466181-6ddb1f80-d7f0-11e8-98f3-77c01dadbd33.png">

**Comment by jacogr** [comment]
So the last point (item 4) is on purpose - the "next up" list is filtered by removing the actual active validators, i.e. they are already showing under "validators", so the intent behind the list of the right is to show the intentions that can enter the validation queue next. (So filtered instead of duplicated)

I am not sure why 30 + 2 = 31 here. I can only imagine it is a subscription/data refresh issue. Will need to take a look.

**Comment by jacogr** [comment]
Ok, lot of time since this one - for poc-3 we have reworked the API layers (complete replacement, actually), which which be much more stable with the new interfaces and not have the funny issues such as 30 + 2 = 31 as above.

Let's see when Alexander launches with validators slots for anybody (soon, really soon), if there are any funnies remaining on the UI or node side.
