### ISSUE TITLE
I registered a short address，But the transaction transfer was wrong.

### ISSUE THREAD

**Issue by xiazhiming** [polkadot-js/apps#3530]
I filled in the short address in the transfer, showing the correct address name. But the actual transfer address is wrong.
![image](https://user-images.githubusercontent.com/29635388/91331791-d553c300-e7fd-11ea-9b08-4859e5097473.png)

**Comment by jacogr** [comment]
Which chain?

**Comment by jacogr** [comment]
I'm really wondering why there are 2 of these questions today about AccountIndex registrations - it is not configured for use, not on Polkadot, not on Kusama. Since we've never seen these questions before it would mean that some incorrect info on the chain capabilities are spreading based on completely wrong understanding of mechanics.

**Comment by xiazhiming** [comment]
In Polkadot chain，Because the page resolved the correct account name, but the wrong account address.

**Comment by jacogr** [comment]
Closing. It is a non-supported feature and certainly should not be used on Polkadot/Kusama since it doesn't support indices  as destinations in transactions.

If a short vanity is to be used, add it via addressbook. (This UI will now also not allow indices in address fields elsewhere)
