### ISSUE TITLE
Impossible to send total amount of DOT from Polkadot wallet to another exchange

### ISSUE THREAD

**Issue by ptran32** [polkadot-js/apps#3681]
Hi,

I've created an account on [https://polkadot.js.org](url) 

I tried to send the total amount of my wallet (9.723 DOT) to an exchange platform, but when I did, an error message occurred on the UI and the transaction failed.

Error message from the failing block on [https://polkascan.io/](url):

**Module**:  balances
**Call**: transfer_keep_alive
**Description**:  Same as the [`transfer`] call, but with a check that the transfer will not kill the origin account. 99% of the time you want [`transfer`] instead. [`transfer`]: struct.Module.html#method.transfer # <weight> - Cheaper than transfer because account cannot be killed. - Base Weight: 51.4 µs - DB Weight: 1 Read and 1 Write to dest (sender is in overlay already) 
**Result**: Transfer/payment would kill account

1) I was charged with fees by Polkadot, even if the transaction failed. Is it the expected behavior?

2) How can I send ALL my DOT without getting an error (and be charged for nothing)

**The thread of this issue on Reddit**
[https://www.reddit.com/r/Polkadot/comments/isfmp5/impossible_to_send_dot_from_polkadot_wallet_to](url)

I will be happy to share more information if needed. Thank you!

**Comment by jacogr** [comment]
Thanks for logging.

To answer the first question: yes, all transactions, sucessful or not pay transaction fees since they interact with the state and store data. (e.g. even on failed transfers events are emitted)

On the transfer screen the default is always to use keep-alive transfers. In this case the transfer will fail when the balance drops too low and the account will be removed. In substrate if the account drops below the existential amount (showed on the transfer screen), the account gets removed. This is not expected by most users, hence the default is to ensure accounts are protected.

To switch to "remove when balance is to low behavior", the toggle for unprotected transfers should be set -

![image](https://user-images.githubusercontent.com/1424473/93174423-3a7c4380-f72e-11ea-9dca-86a7f385adbc.png)

So to transfer the full amount -

1. Swap the toggle above to send the unprotected version of transfers
2. Ensure that you send "full balance minus fees" to cover the executions costs (at this point there is no automatic "send max" option, so it is a manual process - it is in the queue enhancements, see https://github.com/polkadot-js/apps/issues/2739)

Fees are displayed on the signer, for Polkadot it is 15 mili DOT (for Kusama 2.5 milli KSM).

So If i had 2.345 DOT to transfer, covering fees -

1. Swap to the unprotected version
2. Send 2.345 - 0.015 = 2.33 DOT

**Comment by ptran32** [comment]
@jacogr Thank you for your explanation, it's really helpful.

I tried to send the full amount, following your steps -

1. Disable the toggle
2. Send 1.661 DOT. Which is equal to my current total amount of DOT, minus fees (1.676 - 0.015)

The transaction failed, but this time I didn't get charged any transaction fees. (my current balance is still at 1.676).

Below the truncated message I get from the failed transaction [https://polkascan.io](url)

```
**Description**: Transfer some liquid free balance to another account. `transfer` will set the `FreeBalance` of the sender and receiver. It will decrease the total issuance of the system by the `TransferFee`. If the sender's account is below the existential deposit as a result of the transfer, the account will be reaped. The dispatch origin for this call must be `Signed` by the transactor. # <weight> - Dependent on arguments but not critical, given proper implementations for input config types. See related functions below. - It contains a limited number of reads and writes internally and no complex computation. Related functions: - `ensure_can_withdraw` is always called internally but has a bounded complexity. - Transferring balances to accounts that did not exist before will cause `T::OnNewAccount::on_new_account` to be called. - Removing enough funds from an account will trigger `T::DustRemoval::on_unbalanced`. - `transfer_keep_alive` works the same way as `transfer`, but has an additional check that the transfer will not kill the origin account. --------------------------------- - Base Weight: 73.64 µs, worst case scenario (account created, account removed) - DB Weight: 1 Read and 1 Write to destination account - Origin account is already in memory, so no DB operations for them. # </weight>

**Result**: Balance too low to send value
```

Do you see what's wrong here?

**Comment by jacogr** [comment]
I wanted to mention that case where fees are _not_ charged above, but it may have been confusing in that context. So when the node gets the transaction, it does pre-validation in the pool (before execution) to ensure that things like the nonce is valid and the account can pay the fees.

The tricky bit with the fees are that they are variable based on chain conditions. So in this case it would seem the amount left for fees is not enough.

- Ensure you don't have  reserved/locked portion (i.e. the UI would show the transferrable, the rest remain locked)
- Check that your amount left for fees are >= the calculation shown on the signer dialog (where I saw 15m on my screen)

So when the account is removed, it is quite possible that the fees would be higher than the 15 (actually 14.9) indicated. so adjust that upwards.

... hence why a "calculate max" button is valuable and less fiddly than doing it manually.

**Comment by ptran32** [comment]
Thank you very much for this explanation. I understand now why I couldn't send all my DOTS.

I'll wait for the "send max" option :)

I'm closing this issue.
