### ISSUE TITLE
Add Ledger seed import mode

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#3703]
Because the derivation path is different in Ledger devices, recovering a Ledger seed into Polkadot JS Apps or the extension from the seed won't produce the same account as if the Ledger device were queried. In other words, Account 0, Path 0 on Add Ledger does not produce the same address as an import from seed with derivation paths //0, //1, /0/0, or /1/1. A switch "importing from Ledger" or a heads up on which derivation path to use during importing from seed would be useful, so people can use their Ledger wallets even when the Ledger app is not functioning correctly.

**Comment by jacogr** [comment]
Derivation in Substrate is very different (to say the least). Not against the idea, so PRs are welcome to utils/keyring for this type of support provided it has a no additional dependency overhead and a low maintenance overhead. Once that is available, can re-visit the UI aspects.

**Comment by jacogr** [comment]
Needs some info at https://github.com/Zondax/ledger-polkadot/issues/61

Been playing a bit and really cannot figure it out by myself here :)

The issue is obviously that users should really only use this as a last resort, i.e. I was without my Ledger for a couple of weeks (and luckily didn't need access). S there are def. recovery reasons, but certainly users should keep as much t the HW as possible.

Anyway, If I understand how, can pull it in.

**Comment by Tbaut** [comment]
@Swader I think it would be great, and very important to couple this feature with a wiki page on polkadot.wiki, explaining what users should do if they ever enter their ledger mnemonic on an online device. I'm not a heavy ledger user so you'll know better, but I guess this involves:
- transfering the funds asap to another account (suggest Signer?, at least on the extension?)
- Make sure there are no other coin associated with the ledger mnemonic that just went online, if any -> transfer elsewhere 
- create a new mnemonic from the ledger itself and make sure to never use the old one again
- transfer back all the funds

**Comment by jacogr** [comment]
It applies to stuff like the QR signer as well - anything where you store the keys in an offline device. (So we actually have that issue already where people can actually take cold keys and move it hot - so some guidance generally is actually a really good idea).

**Comment by Tbaut** [comment]
Indeed, this could be framed more generally. But something comprehensive for the less technical users would be very valuable. Users ending up in a situation where they don't understand why they can't access their funds and fear loosing them  become a particularly good target to scammer pretending to help them.

**Comment by Swader** [comment]
Yeah we'll handle that, no worries 👌

**Comment by jacogr** [comment]
Have a sample as to how it works from Ledger https://github.com/jacogr/sample-ledger-ed25519 

Took "some" time to figure out.

**Comment by jacogr** [comment]
So just an update - 

- the apps UI PR is ready for testing - it needs a bit still, but does do the trick
- the tool above https://github.com/jacogr/sample-ledger-ed25519 does operate via the command-line (So you can actually extract the `ed25519` seed and create a new account with that as a seed)

Basically on the above, one run and you have the `ed25519 seed`, 

- add an account in the apps UI
- select the type dropdown to `Raw` (changing it from mnemonic)
- Past the hex as tretieved from the tool
- click "advanced options" and select `ed25519`
- check that the addresses do match with expectation
- create account

**Comment by gorgos** [comment]
@jacogr Thank you! I just go the KSM back via offline computer. Would you mind sharing the gist of https://github.com/jacogr/sample-ledger-ed25519? I can't say I understand the code.

**Comment by jacogr** [comment]
Well, thanks to you since I ended up in dead-ends with 3 other approaches :)

So the Ledger used bip32+ed25519 derivation. So what it does in general terms is the following (it is a bit messy, it actually has been cleaned up but not pushed there) -

- starts off by path construction, which is `m/44'/{0x0162 or 0x01b2}'/{account}'/{address}'` (the second cointype is either for Kusama or Polkadot)
- then it gets the master key, which is actually translated from the Ledger Python code
- now it goes through each segment of the code (excluding `m`) and applies the hard derivation using that value (this I struggled a bit with the Python translation, but Cardono extraction code helped to make it more translatable)
- lastly it takes the output from the previous and feeds it into the ed25519 to create a pair (the from seed function uses the first 32 bytes of the output of the previous step)

**Comment by gorgos** [comment]
That's great. Thanks for the info. I was running the Python code directly after changing path and mnemonic inside the Python code, but had no idea what the tool with printing there.

Sounds like this task wasn't easy, so much appreciated, thanks again.

**Comment by jacogr** [comment]
It was more of a relief than anything else - I've been playing with it for the last 2 weeks now and couldn't figure it out with Google as my tool.
