### ISSUE TITLE
Contracts: I have multiple erc20 code hashes

### ISSUE THREAD

**Issue by yangwao** [polkadot-js/apps#3913]
I think I'm a corner case, but I've to use ink! 3.0-rc1 and 3.0-rc2 with the same contract name, but it generates different wasm. 
How I distinguish between them? Is there a way to read metadata to see which one erc20 is newer?

![image](https://user-images.githubusercontent.com/5887929/96876558-e412cb00-1478-11eb-8a35-8691b0ba9c0d.png)

**Comment by jacogr** [comment]
Not a corner case :) The edit name should be there, but it was horrible so removed for the time being.

So there is def a gap, it should show a link with the actual hash. Will push up the outstanding "display & copy hash" in a PR, sorry about that. (It is functionality that was there, but removed since it was not done properly... so still hanging)

**Comment by jacogr** [comment]
The linked PR will show the hashes. It is still going to be a slight issue to figure out "which is newer", since this is what is on-chain

![image](https://user-images.githubusercontent.com/1424473/96879417-4f11d100-147c-11eb-82f9-d093f1ae9d88.png)

Not sure we store a "when created" alongside the code in storage. (Also added that to the above, but not displayed atm and won't apply retrospectively)
