### ISSUE TITLE
Add council participation threshold to propose external motion

### ISSUE THREAD

**Issue by drewstone** [polkadot-js/apps#3965]
Right now there is a default selection but this has made proposals in Edgeware fail due to not have the right calculation of the minimum threshold. This would be a proposal to add a threshold to the UI where a user could specify how many votes are necessary to pass an external proposal.

**Comment by jacogr** [comment]
It is different for Kusama, Polkadot & Kulupu, see https://github.com/polkadot-js/apps/blob/master/packages/page-council/src/thresholds.ts

So I maintain Kusama/Polkadot, Wei maintains Kulupu. I would love to be able to do the same for all chains, but since it is not exposed anywhere, it is a losing battle.

PRs to the above to extend for additional chains welcome.

**Comment by drewstone** [comment]
Ah thanks I never knew about this!

**Comment by jacogr** [comment]
Closing. The config is available, PRs really welcome to add Edgeware to the list so the UI just fills in the details :)
