### ISSUE TITLE
How to decorate rpc methods

### ISSUE THREAD

**Issue by joelamouche** [polkadot-js/apps#3967]
@jacogr  I can't find in the documentation how to decorate rpc methods.
I'm on Moonbeam alphanet and I'm getting this error:
![Capture d’écran 2020-11-04 à 10 58 09](https://user-images.githubusercontent.com/16758383/98097043-b96b3e00-1e8c-11eb-9217-7a392cac9d37.png)
because the ethereum rpc methods are not decorated

**Comment by jacogr** [comment]
The API will work without, so it is more of a warning that a fatal error - however, those won't be usable at all until injected.

Here is the docs for that specifically - https://polkadot.js.org/docs/api/start/rpc.custom

**Comment by joelamouche** [comment]
Yes I saw that but I don't know what module to specify.
I added 
````
    const rpc= {
      firstModule: {
        eth_accounts: {
          description: 'Just a test method',
          params: [
            {
              name: 'index',
              type: 'u64'
            },
            {
              name: 'at',
              type: 'Hash',
              isOptional: true
            }
          ],
          type: 'Balance'
        },
      }}
````
to the ApiPromise call and I still get the warning

**Comment by jacogr** [comment]
````json
rpc: {
  eth: { // this is the module
    accounts: { // this is the method
     ..
  }
}
``

Be aware that for apps this is not supported, i.e. it is not done for any of the chains since there is no specific config section. (So all chains with custom methods currently don't get them exposed - https://github.com/polkadot-js/apps/issues/2162)

**Comment by joelamouche** [comment]
Ok thank you!

**Comment by jacogr** [comment]
It really has been hanging for a very long time now, there are nothing technical that stands in the way (the API allows it), but it means extending the config and adapting for each of the existing chains, those specified here only, those specified externally, those with types vs typeBundles, etc. 

Since the apps UI only uses the standard RPCs anyway, it doesn't have an impact anywhere apps-UI-wise. 

What it does mean is that the RPC section under developer is not comprehensive, so you cannot do anything and everything like you can with standard chains. Just from this perspective, it needs closing at some point.
