### ISSUE TITLE
Voting for council overwrites bonding amount

### ISSUE THREAD

**Issue by brenzi** [polkadot-js/apps#3997]
I'm trying to vote for council on Polkadot but polkadot-js/apps doesn't let me select the amount bonded for the vote. As soon as I enter a value it gets overwritten by the maximum. (using chrome 85.0)

**Comment by jacogr** [comment]
This seems to be a duplicate of https://github.com/polkadot-js/apps/issues/3937 which had a fix yesterday. At least the same thing as you explained here doesn't occur for me anymore in the current deployed version. (Still did since the above issue was reported). Will re-check against Polkadot/Kusama.

**Comment by jacogr** [comment]
Yes, cannot replicate this at this point.

**Comment by brenzi** [comment]
The problem seems to be solved. It now works
