### ISSUE TITLE
Recommend changing the staking landing page

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#4112]
The first page of Network -> Staking takes a long time to load and bombards the node it's connected to with arguably unnecessary calls (lots of data including identities). It would perhaps be more user-friendly if the first page were a "dashboard" instead on which one would see different cards like: "Payouts pending: 2", "Target vs minimum", and other basic info from the other tabs, but without the granularity of the information. Clicking on any of those cards then takes the user to the appropriate tab, making navigation around "Staking" more intuitive and faster to load. In addition to basic info cards, we could also add links to docs about staking here and other essential info.

**Comment by jacogr** [comment]
It would slow things down considerably, actually. The fastest page is actually the overview - well, actually "account actions", but that is not always there. Including useful info like payouts would slow things down to a crawl since you need the full staking state.

The reason why it is a bit sluggish is actually since it doesn't just load the overview page, there is extra info retrieved for eg actions, targets in the background. (This is actually an ongoing effort, hardly noticable imrpovements since each yields 1-2%, which overjoys nobody)

So as is described here, this is sadly a "wontfix", however the overall improvement of both data and ordering is high on the list of priorities and an ongoing effort.
