### ISSUE TITLE
Dots will not unbond/still staking after timer ran out.

### ISSUE THREAD

**Issue by DroolzZ** [polkadot-js/apps#4121]
I tried staking Dot on JS but only had a small amount to test the waters. I decided to give up and unbond them. It had the unbonding indicator and counted down but its been past the 28 days and now the indicator is gone. They are still locked and I can't find a way to unlock them so I can send them elsewhere. They are shown as locked and redeemable yet I cannot find an unlock icon anywhere. Any ideas?

![Screenshot (75)](https://user-images.githubusercontent.com/75265565/100634455-8fbb0080-32ec-11eb-8439-ef928e8d26e3.jpg)
![Screenshot1](https://user-images.githubusercontent.com/75265565/100634467-947fb480-32ec-11eb-8175-ab429bd2c7b9.jpg)

**Comment by jacogr** [comment]
This is one of those where I need to look at the state for the specific account before I can offer suggestions. 

(The withdraw, when available, is done via the controller account, so you'll need to have access to that, but I assume that you do have access to both the stash and controller).

**Comment by DroolzZ** [comment]
Thank you. So is there  a different screen shot I could send you?

**Comment by jacogr** [comment]
If you can send me the address, it would help :) Thee are a couple of state queries to do.

**Comment by DroolzZ** [comment]
14zmk4HbQ1j7UTo9zZv8oFwVPDpZdqWQrE3DyyMzVnMTq8eH

**Comment by jacogr** [comment]
Ok, this is weird, it is def there in the ledger, available after era 179.

Will go through a local test, but basically the logic to show is -

- are there active withdrawals?
- does the user have access to the controller to make transactions? (This could be an issue above since you also cannot change session keys on the dialog, which would mean the stash account is available, but not the controller - i.e. this transaction will be sent from `13MXkEsBxQFgZZSuE78Xxxbp2LNr98xEydakmUVxfebAUiVX`)

**Comment by DroolzZ** [comment]
There shouldn't be any active withdrawals.  It sure seems like I have access to send from the controller. 

![Screenshot (76)](https://user-images.githubusercontent.com/75265565/100661905-6791c880-3311-11eb-83d5-763130bd76ac.jpg)

**Comment by jacogr** [comment]
I replicated exactly what you had by removing my controller account. 

If you look at the first screenshot you posted of your accounts, you only have the stash account there. Te controller is missing so it cannot be used to sign transactions.

**Comment by DroolzZ** [comment]
ok, so how do I restore my controller account?

**Comment by jacogr** [comment]
With the seed you used to create it? It is def. an existing account, so ether use the seed you have for it or restore via the JSON backup file that was created when you created it initially.

If you don't have access to the controller seed anymore and cannot add it, you still need a controller before withdrawing. 

In that case you can change the controller (since changing the controller is a stash operation) to another account you do have access to (even the stash itself). Once changed and with that account as the controller the transaction can be send.

**Comment by DroolzZ** [comment]
It worked! Thank you sooooo much!!!

**Comment by DroolzZ** [comment]
I tried to tip you but it says you arent set up to accept bats
