### ISSUE TITLE
Auto-load custom type definitions

### ISSUE THREAD

**Issue by tomusdrw** [polkadot-js/apps#4187]
Working with multiple custom chains is a bit cumbersome currently, cause it requires submitting custom type definitions.
That's an extra step if you want to show off your work to external users, cause it requires them to:
1. Switch to your node
2. And then fetch custom types from the repo and copy&paste them to the setting directory.

I have two ideas how this experience for the user could be improved and I'm interested in what you think about it.

1. [ ] Support customizing WS endpoint in the URL - Am I right that this is supported via `?rpc` already?
2. [ ] Support fetching custom type definitions given in the URL as well - So similar to (1) we would add `?rpc=...&types=...` and the UI would fetch custom type definitions automatically. I guess CORS might make it much harder than expected, but maybe we could have custom types be a `.js` file, which calls some global function registering the types?
3. [ ] Support fetching custom type definitions URL (or content) from the node itself: - I imagine we can utilize `Offchain-DB` (and corresponding RPCs) to fetch custom type definitions from there. OffchainDB could be either populated by an offchain worker or on-chain Indexing API (i.e. the runtime would have the location of custom types hardcoded, but could update them).

The problem is most likely also alleviated by Andrew Jones' work on [`scale-info` integration](https://github.com/paritytech/substrate/compare/gui-macro-attribute...aj-metadata-vnext), but it's not likely it's going to be usable in a very near future.

**Comment by jacogr** [comment]
Yes, scale-info works really well for the contracts ABI, but it will be some time still before it lands.

I could have sworn I logged something to save multiple types and tie them to chains in the developer console, but it must have been a dream - can’t find it (only a simplified version dealing with addresses only)

With all that out of the way - not sure the OCW approach is worth the effort (since it ends up being throw-away after „some time“), but it is an interesting angle and application. Obviously UI wise it is actually almost the simplest. (Sharing via URL probably is the simplest)

**Comment by jacogr** [comment]
There is an option here - we used to share JS snippets via url (switched it off since it can create holes for attacks), however it was decent-ish -

- lz4 compressed
- base64 encoded

With minimal effort can actually create a shareable link in the same way on the dev types page. Basically once added it gives you are url to share.

**Comment by tomusdrw** [comment]
> With minimal effort can actually create a shareable link in the same way on the dev types page. Basically once added it gives you are url to share.

Yeah, I think it would be strictly better than what's required now (i.e. clicking + copy&pasting).

> not sure the OCW approach is worth the effort (since it ends up being throw-away after „some time“),

:100: While that would be the closest to ideal behaviour though, where you basically just switch the chains and it works™, if we can get a sharable link workaround much easier, I agree it's not worth the effort, especially if we have a better solution somewhere upon the horizon as you've mentioned.

**Comment by jacogr** [comment]
Ok, will see what effort it would be do have a sharable link - should really be straight-forward, however all that stuff in ancient so may end up with a bit of swearing.
