### ISSUE TITLE
balance mismatch in apps

### ISSUE THREAD

**Issue by chaosma** [polkadot-js/apps#4285]
In Substrate v2.0.0, the staking amount is 100 Dollars (in bin/node/cli/src/chain_spec.rs). However, the apps shows the staking balance is 9.99 (effectively 10).  There is a 10x difference. Which side should be changed? The substrate v2.0.0 or apps?

**Comment by jacogr** [comment]
See https://polkadot.js.org/docs/api/FAQ#on-a-non-current-non-substrate-20-branch-my-balances-are-wrong

The refCount types changes between pre-Substrate 2 and Substrate 2 - if your type definition doesn't match, the decoded values will be wrong.

**Comment by chaosma** [comment]
I have used tags/release version, commit=a200cdb93c6af5763b9c7bf313fa708764ac88ca.
However, after I added "RefCount": "u8", in developer tab. The free balance is changing to 16.7TUnit (not correct) and the staking balance stay the same as 9.99Unit(which should be 100Unit).

**Comment by jacogr** [comment]
Ok, so if the chain is based on Substrate 2, the `refCount` default (as u32) i correct. Chains that are older are u8.

So one thing to bear in mind is that the UI, unless instructed by the chain properties (as set in the chain spec) will apply a default value for decimals since it is not specified. If that doesn't match with your expectations, you should explicitly set the decimals in the spec.

See for instance https://raw.githubusercontent.com/paritytech/polkadot/master/node/service/res/kusama.json -

```
  "properties": {
    "ss58Format": 2,
    "tokenDecimals": 12,
    "tokenSymbol": "KSM"
  },
  ```

**Comment by chaosma** [comment]
I put this properties information into the customSpec.json and start the node with it, the frontend didn't change the token symbol or the correct decimal. The tokenDecimal is 14 which is the same as substrate v2.0.0. And the default decimal for apps is 15. 

```
{
  "name": "Local Testnet",
  "id": "local_testnet",
  "chainType": "Local",
  "bootNodes": [],
  "telemetryEndpoints": null,
  "protocolId": null,
  "properties": {
    "ss58Format": 2,
    "tokenDecimals": 14,
    "tokenSymbol": "TEST"
  },
  "forkBlocks": null,
  "badBlocks": null,
  "consensusEngine": null,
  "lightSyncState": null,
  "genesis": {
     //ignore
  }
}
```
