### ISSUE TITLE
Chain State tab only visible when accounts are present

### ISSUE THREAD

**Issue by JoshOrndorff** [polkadot-js/apps#4370]
It is a common use case that I open Apps to inspect the chain state with no intentions to submit transactions. In this case, clicking through the "add account" workflow costs several seconds.

**Comment by jacogr** [comment]
Indeed. This was added after your first issue where having no accounts renders wrong for items where an account selector is needed. As of now, it is unlikely to change since any rework to the account selector is not short-term on the table. At the same time doing the type inspection on all items for filtering the list will yield queries around "this is not showing" and be expensive to boot.

So the options atm are -

- having it half broken where accounts are required
- not having it account queries are in a large number of items

Currently it sits in the second bucket.
