### ISSUE TITLE
Failed to send DOT to another wallet

### ISSUE THREAD

**Issue by Sudargo** [polkadot-js/apps#4433]
Hello,

I sent a total amount of (DOT 228.2814257348) from Coin Hako exchange to Binance.
Coin Hako completed this transaction but the DOT crypto is still not deposited to Binance.

I tried to check the Hash ID in the site and it cannot be found:
https://polkadot.subscan.io/extrinsic/0x84bf0e31f7b41b0fe3c61e5377c0852b7b871704600efdc9bff651d0cb131499

Error details:
Time 2021-01-16 13:19:27 (+UTC)
Block 
Life Time immortal
Module -
Call -
Fee DOT NaN DOT (+NaN DOT tips)
Result Fail

Transaction Hash: 0x84bf0e31f7b41b0fe3c61e5377c0852b7b871704600efdc9bff651d0cb131499

I have attached some screenshot of transaction details from Coinhako and https://polkadot.subscan.io/
I will be happy to share other information that might help for this issue. Thank you!
![DOT3](https://user-images.githubusercontent.com/45379182/104813036-74c33200-5841-11eb-9b58-8da7212c53cb.JPG)
![DOT2](https://user-images.githubusercontent.com/45379182/104813041-768cf580-5841-11eb-9729-942d0ef124c0.JPG)
![DOT1](https://user-images.githubusercontent.com/45379182/104813042-768cf580-5841-11eb-82b0-2171a2c0a55d.JPG)

**Comment by jacogr** [comment]
I honestly cannot comment on the 3rd party sites - they all have their own SCALE codec parsing and their code is specific to them. So cannot comment on the details they do show.

**Comment by jacogr** [comment]
It could very well be that the sending wallet has the incorrect hash since it is not available on Polkascan. Once again, it refers to their wallet.

I would love to be of more help, but have no insights into their processes and how the stuff is build. Here really focussed on the polkadot-js wallet (and elsewhere API). So anything that falls out of that reals is a big black box to me.

So my suggestion would be to log it with the relevant wallet and explorer to take a look. Good luck and once again sorry I cannot help here.

**Comment by Sudargo** [comment]
I initially suspect that it's the wallet sender as well that is having the issue. I just received the deposit after almost 12 hours. Not really sure what went wrong there, but somehow that failed TrxHashID is replaced by another.

I had email polkascan as well, curious what will they reply. But thanks for the reply, I might try to use DEFI wallet

**Comment by jacogr** [comment]
Yes, I took a look at Polkascan and it didn't show up. so I think the Subscan display above is wrong, but it is basically what they show when they can't find anything.
