### ISSUE TITLE
“ transfer the full account balance, reap the sender” not displaying

### ISSUE THREAD

**Issue by yemidavis** [polkadot-js/apps#4456]
I'm looking to close my second DOT wallet and move my balance from that wallet to my main one. 

According to the instructions here: https://support.polkadot.network/support/solutions/articles/65000170293-how-to-send-all-of-your-funds-out-of-your-account, once I uncheck "transfer with keep-alive check", it should enable the "transfer the full account balance, reap the sender" option. However, this doesn't happen. I’m using a Ledger Nano X with Polkadot JS
![29404A80-7579-418F-AD1B-A4ACF14D47AB](https://user-images.githubusercontent.com/12338981/105169384-c1e22500-5b1b-11eb-92a2-3e1dc8a913c5.jpeg)

**Comment by jacogr** [comment]
The only reason why it should not show is if there is a reference on the account. However, it is not there or rather not displayed. Can you just do a query on the state for that account since it helps zooming in. Steps 

- Developer -> chain state
- select system.account
- select account you wish to reap
-click "+"

The output should have "refcount: 0" in there. (As well as reserved 0). Just need to track if it is a reference/reserved not diplaying issue of something else.

If the refcount/reserved is 0, the only thing I can think of at this point if that it may be account-type related, but don't believe there is specific type logic in there. Will have to check the logic to see if there is anything weird, the above will help to zoom in.

**Comment by yemidavis** [comment]
Hi @jacogr,

Thanks for getting back to me.

I have just given this a go and please see the attached screenshot.

Hope this helps with a resolution

![Screenshot_50](https://user-images.githubusercontent.com/12338981/105173424-48e5cc00-5b21-11eb-99bd-965077ac68f5.jpg)

**Comment by jacogr** [comment]
Ok, all clean above. Very small issue in the code. You have exactly existential and the check to allow for > existential, i.e. not exactly equal. So right on the edge.

I'll push a small update now and will alert here when available, will be around 15 mins until deployed. 

However, when toggling (like you have) and entering 1 it should just work anyway - since it will send balances.transfer that allows reaping. (Unless you get an error back from RPC?)

**Comment by jacogr** [comment]
So, in this case, the UI is actually 100% correct. I tested it by removing the > existential check.

The issue is that the fees are applied before the value - if at this point the balance drops below the existential, the transaction is rejected by the node and you would get "1010: Invalid Transaction: Inability to pay some fees , e.g. account balance too low"

So unless there is existential + fees available in the account, it is a bit difficult to reap. So to get rid of it, transfer a small amount > 0.015 DOT to that account to cover the transaction fees without dropping it below existential. In this case the correct toggles will show and the account can be reaped.

**Comment by yemidavis** [comment]
Awesome! That fixed it. Working all fine now> Fank you for your help!

**Comment by jacogr** [comment]
I'm just going to re-open this one - so I'll just remember to display a small warning in these cases (like it does with the refcount), just to help future users as well. Even I had to dig aroud and double-check the logic, so would like to prevent a repeat at some time :)
