### ISSUE TITLE
CSRF in https://polkadot.js.org/apps/#/settings [Security]

### ISSUE THREAD

**Issue by Shashank-In** [polkadot-js/apps#4465]
Description:
Cross-Site Request Forgery (CSRF) is an attack that forces an end user to execute unwanted actions on a web application in which they're currently authenticated. 
https://cwe.mitre.org/data/definitions/352.html

PoC: 
1. Go to https://polkadot.js.org/apps/#/settings?rpc=wss://someMaliciousNode.com:80
We will notice the application set the custom endpoint to the value of rpc parameter. 

Severity explanation:
There are other security issues I have reported which can be combined to make the attack easier. 
a) The Polkadot app is still vulnerable to clickjacking. A malicious user can simply set the URL (https://polkadot.js.org/apps/#/settings?rpc=wss://someMaliciousNode.com:80) behind an iframe to maliciously update the victim user's custom endpoint.

<iframe src="https://polkadot.js.org/apps/#/settings?rpc=wss://someMaliciousNode.com:80" style="width:0;height:0;border:0; border:none;"></iframe>

So anyone who visits the page would be presented with an invisible iframe and the endpoint would be updated silently 

b) The application never logout. I reported this before and it was discarded. Although I understand the reasons but since no user log's out from the application the attack vector increases as every active user is logged in to his browser.

**Comment by jacogr** [comment]
Thanks for reporting. Not 100% sure why somebody would try and hide it in an iframe since the apps UI does break out. So basically you will end up with `https://polkadot.js.org/apps/#/settings?rpc=wss://someMaliciousNode.com:80` - which is the same as clicking through on a link. So it is not hidden after the direct, it is indeed but very visible in the URL.

I suppose an enhancement could be to always break out of the frames without even getting to the apply, i.e. just move the actual location of breaking out.

On the second issue - what do you expect to be logged out of? There are no backends where data is stored that a user logs into. The endpoints are used for (a) queries of data and (b) submitting fully signed transactions.

**Comment by krzysztof-jelski** [comment]
As to logging out: perhaps we could trigger disabling the extension for the site?

![image](https://user-images.githubusercontent.com/430616/105399797-63549e00-5c24-11eb-9b04-8f68cc76de79.png)

**Comment by jacogr** [comment]
There are multiple extensions, it is not just 1 out there and not all have the same approve/deny, 1 of the 5 I track has it. Denying in the extension means the user will never have accounts and won't be prompted to re-enable. So that is a completely separate thing, which sits in the extension keystore.

So trying to understand what "logout means here" specifically since there is no server to logout from. (And for instance in the extension itself, not covered here, we don't do what other extensions do, like MM, we don't keep the accounts unlocked unless explicitly asked for - and then for a time period). Same in apps, unlock is per tx per account, unless the user explicitly extends. (And that is only per the session, when closed it disappears)

So, hence, I want to know "what does logout" mean. (None of this stuff is the same as what is normally applicable in websites, so trying to understand if this is a checklist items, i.e. this is what I check sites against (which is what the audits did as a start) or if there is a specific issue in the app.

**Comment by Shashank-In** [comment]
Hi @jacogr 
To your question 

>  100% sure why somebody would try and hide it in an iframe since the apps UI does break out

Sorry about that. Clickjacking was my report as well. I was unaware this was fixed. I noticed the frame breaks out now, so the CSRF attack vector reduces in this case. 


> Regarding logout.

CSRF won't make sense if the user is logged out and the feature is behind a login mechanism. No logged-in user the CSRF attacks goes blank. 

However, the threat of CSRF remains. These points were just catalysts for CSRF attacks. Irrespective of logout and clickjacking. The attack vector of CSRF remains.

**Comment by jacogr** [comment]
Agreed. The issue here is that there is not a login ;) However there is no actual central database where anything user-related is stored. 

For instance signing works with user keys that never leaves the local machine. The only thing the node receives is fully signed transactions, with the local (to the user) keys. The RPC nodes don’t do any storing of keys or anything user related. (Validator nodes are different, hence them not running RPC interfaces and why the public RPC nodes also don’t expose the unsafe RPCs, such as validator key rotation)

On queries via the RPC nodes it is for on-chain data. Current state or for the last 256 blocks which is the pruning period.

**Comment by jacogr** [comment]
Closing.

(a) it does break out of frames
(b) there are no user-credentials on a central server to log out of (no logins)

**Comment by Shashank-In** [comment]
I think the main point was completely missed. The attack vector here is if I send this link to a user. The victim will be connected to my fake node. As mentioned before, other points were just catalyst points. The bug here is that of a CSRF attack.  
https://polkadot.js.org/apps/#/settings?rpc=wss://someMaliciousNode.com:80

The fix would be to keep a unique generated anti-csrf token. And the check should be performed like.

https://polkadot.js.org/apps/#/settings?rpc=wss://someMaliciousNode.com:80&antiCSRF={SomeUniqueToken}

So when an attacker sends `https://polkadot.js.org/apps/#/settings?rpc=wss://someMaliciousNode.com:80` there won't be any valid `antiCSRF,` and the request will be rejected, and since the token is unique, an attacker cannot guess it.  


Ref: https://owasp.org/www-community/attacks/csrf

Rest I will leave the decision to the team. 

cc: @jacogr

**Comment by jacogr** [comment]
The Nodes don't have tokens.

They are all user-nodes. so for instance, you can just spin up your own `polkadot --chain kusama` locally and connect to it or provide it for the community. There is no central authority here that polices the nodes that are provided.

So what can a "fake node do" -

- it can provide different information for storage keys (since it is a query-only interface)
- it cannot modify any submitted transactions (those are all signed with local keys)

So when it does happen, it could mean -

- the user transactions are never submitted (cannot be modified, changes invalidates the non-deterministic signatures)
- the information display is wrong on a UI

Both these actually have happened with community-provided nodes on the list as well as well where they have not kept up with upgrades. It doesn't place any funds at risk.
