### ISSUE TITLE
UX concern - allowing users to send funds to validators on staking main page is oddly confusing

### ISSUE THREAD

**Issue by maplesyrupsucker** [polkadot-js/apps#4590]
Allowing users to send to validators on [staking homepage](https://polkadot.js.org/apps/#/staking) is a strange thing to put so front and center. Speaking from experience after accidentally sending DOT to a validators address when I thought I was sending funds into a staking pool. After joining the Polkadot discord I saw others have done the exact same thing. 

<img width="1427" alt="Screen Shot 2021-02-04 at 12 28 49 PM" src="https://user-images.githubusercontent.com/3764321/106849078-af074d00-66e4-11eb-8480-20a43d8b9006.png">

1. Staking homepage shouldn't unnecessarily provide users with the ability to move funds without more clear copy to explain to users what they're doing with their dot
2. Renaming the "send" button in the validator overview to what I assume is to tip validators could simply be renamed "Tip" in lieu of current button copy "Send", which is more obvious that it is nothing to do with Staking. 
3. Additional warnings to learn more, where users can read or watch videos on properly putting bonded funds with nominators.

**Comment by jacogr** [comment]
Thanks for logging. I'm sorry you find it confusing. For staking the best is to always refer to the wiki's if you don't know how the NPOS staking works. The account actions on staking, as referred to in these guides, is laid out to allow you to "+ Nominate" is a single step.

There is no staking-specific "tip" those only exists in the treasury, the popup you are referring to allows you to see information for any account on any part of the UI. The "send" there does exactly what is says, it is a transfer operation that you have access to on any part of the app for any account that you click on.

The apps UI is not really focussed on hand-holding, instead of being the simplest, the focus is on making it the most comprehensive tool in the ecosystem where you can access any part of a Substrate network and perform any operation. It really does not aim to protect users from themselves, but rather assumes they understand the operations they are performing.

Having said that, feedback is always good, and more hand-holding does get added sporadically, even if pure-UX is not a primary focus. 

In this specific case, the global popup is unlikely to change in terms of layout or naming. "Tip" has explicit context in terms of the treasury (where you can tip users from the treasury), "Send/Transfer" is consistent with the operation, but doesn't protect users which have not done reading on Substrate staking. Removing it from the UI detracts from the users who want to have access to any account info at any point as this affords.
