### ISSUE TITLE
timestamp: blockPeriod(): Moment

### ISSUE THREAD

**Issue by jiangfuyao** [polkadot-js/apps#462]
https://polkadot.js.org/apps/next/#/chainstate
timestamp => blockPeriod(): Moment,
result: Thu Jan 01 1970 08:00:05 GMT+0800.
maybe need echo: 5 second.
![_ _20181126142320](https://user-images.githubusercontent.com/34789555/48996827-82f8f480-f188-11e8-9ce8-cbaa598ad09e.png)

**Comment by jacogr** [comment]
Umpf, yes. This is a funny one since it is a `Moment`, so the type is the same as for e.g. `timestamp.now`. So in the one case you actually want to see the timestamp (a large number for `timestamp.now` doesn't have any value, however in this specific case, you actually want to see the value.

Aware of it, thanks for logging (since it was not logged), I don't have an brilliant ideas around solving it at this point.

**Comment by jacogr** [comment]
I am still not sure how to solve this at all - the UI does the exact right things based on the info and type received, i.e. it receives a `Moment` and it displays it as such. Unless we build in a specific override for this one - which is really not a good idea.

Alternatively - we could display both values in the case of Moment, the actual Date (not applicable here) and the raw value (which would be applicable here, but nowhere else Moment is found).

**Comment by jacogr** [comment]
Closing. Not applicable anymore, `Moment` now tracks the Rust u64 type.
