### ISSUE TITLE
Staking app is almost unusable 

### ISSUE THREAD

**Issue by rossbulat** [polkadot-js/apps#4742]
What are the maintainers of this repo doing to address the slowness of the staking app? 

The lack of design skill is now severely apparent, due to the design issues not being addressed when they should have been (years ago). 

Other blockchain apps, particularly in the DeFi space, are vastly outshining Polkadot JS in their speed, performance, ease-of-use and branding.

I bring this up as a stakeholder of DOT and Substrate, and want to see these issues resolved. 

The out of touch lack of design focus of this repo makes myself and other UX specialists apprehensive to submit PRs to fix issues here, highlighting management shortfalls that ultimately weaken the prospects of the app.

**Comment by jacogr** [comment]
Thanks for the comments.

PRs are always welcome.

There are a lot of effort being put in to the underlying derives, making use of batching where it is not done, the identities being cached between uses and investigation into alternative approaches for data retrieval specifically around staking. 

Nobody forces anybody to use this wallet - it attempts to address other need that "just general send stuff around" use, and some of the issues are slightly harder to get around due to the reliance only on the chain RPCs (with no pre-calculated central storage). So it will never be as optimal as centralized solutions that you use as comparison. 

I'm sorry you find the design out of date. It will never be shiny and is not meant to be that either, it is not the intent here. It is not meant to be the UX-beacon of decentralized solutions either. The intent is to create a comprehensive suite, anything pin-point is always going to be better suited to niche use-cases.

**Comment by jacogr** [comment]
Closeing, since there is no actionable reports or comments here at all.
