### ISSUE TITLE
The multi-currency balance is displayed incorrectly.

### ISSUE THREAD

**Issue by ntduan** [polkadot-js/apps#4785]
I have not found this issue before. But this problem has existed for a long time.

In the case of multiple currencies, the formatted string of balance is wrong.

![image](https://user-images.githubusercontent.com/7029338/110263770-87294300-801c-11eb-9782-5a3b0111e91c.png)

And between different currencies, they have the possibility to have different precision.

I don't know if this place should be without precision and units. There really isn't a good solution right now either.

**Comment by jacogr** [comment]
The above is logged on the API. It will only use the first. Atm has no concept of instances.

**Comment by jacogr** [comment]
This is where it gets tracked - https://github.com/polkadot-js/api/issues/3098

(It is not quite simple todo, in all honesty, don't have an idea as of "how" as of yet. Having said that, it is simpler on a per-instance basis as defined, so that is solvable, bu once again, not quite sure how to hook in yet. Not complaining, will get there trying to chew through it.)
