### ISSUE TITLE
Prepare for the release of the new election provider pallet

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#4830]
With the merge of https://github.com/paritytech/substrate/pull/8113, hopefully by runtime version 30, would mean that there's no longer a need to prevent staking actions during the election window. I think this is all that you need to do, and just remove that warning. 

But to be safe, maybe have a look the storage items that I am killing in this PR, and if you actively use any of them, then we need to do something. My guess is that you only use `EraElectionStatus` for the warning, which you won't need anymore. 

If you think suitable, we could keep the same warning, but this time it should read from `query.electionProviderMultiPhase.phase != Off`, and warn the user that votes that are submitted now will be reflected in the era after the one that is about to happen.

**Comment by jacogr** [comment]
When the storage entry is not available, it will just not appear since the flag won't be set - https://github.com/polkadot-js/apps/blob/master/packages/page-staking/src/index.tsx#L45

(Removal is harder since chains at at various phases of their evolution, so the check will remain for un-upgraded versions, the above check is optional because not all chains actually had it in the past)

**Comment by kianenigma** [comment]
True, I merely wanted to inform you about the changes going to polkadot and kusama.

**Comment by jacogr** [comment]
100% - really looking forward to it... scared as hell, but excited :)
