### ISSUE TITLE
Treasury tips page crashes without pallet utility

### ISSUE THREAD

**Issue by jak-pan** [polkadot-js/apps#5050]
Treasury tips page crashes if there is more than one tip present and there is no utility pallet in the chain because it tries to do tx.utility.batch() https://github.com/polkadot-js/apps/blob/bd78840d2142df121d182e8700b20308880dde0a/packages/page-treasury/src/Tips/index.tsx#L53 without checking if it exists. 

From quick search I found more places where this could be an issue like https://github.com/polkadot-js/apps/blob/bd78840d2142df121d182e8700b20308880dde0a/packages/page-accounts/src/Accounts/Account.tsx#L69
https://github.com/polkadot-js/apps/blob/bd78840d2142df121d182e8700b20308880dde0a/packages/page-staking/src/Payouts/Stash.tsx#L66

Some places handle this by checking if it exists.

**Comment by jacogr** [comment]
It should use the `useTxBatch` hook that caters for all iterations. See for instance https://github.com/polkadot-js/apps/blob/master/packages/page-parachains/src/Crowdloan/Refund.tsx#L31 (also applies in staking payouts as well a proxy setups, but nowhere else)

I am aware of the dangling bits mentioned, they have not been a priority since the focus is elsewhere and will be for quite some time until there is breathing room. Conversion is quick with the above hook, so PRs are always appreciated.
