### ISSUE TITLE
Cannot unbond KSM via Ledger Nano S

### ISSUE THREAD

**Issue by gunnertwin** [polkadot-js/apps#5089]
Hello,

I am trying to unbond KSM via my ledger and I'm running into this error `Txn version not supported` from the app browser extension.

My KSM app on ledger is on the latest version: 4.28.3

**Comment by nicolasochem** [comment]
Me too. Transfers appear to be broken as well. In fact, any kusama operation on the ledger returns this.

Polkadot works, though.

Trace: 
```
main.492c0ed5.js:19 signAndSend: error: Error: Txn version not supported
    at a (polkadot.02.fc401d16.js:1)
    at zr.value (main.492c0ed5.js:2)
    at /apps/async https:/polkadot.js.org/apps/main.492c0ed5.js:2
    at async zr.value (main.492c0ed5.js:2)
    at async lde.signPayload (main.492c0ed5.js:19)
    at async Object.value (polkadot.01.a30dbe3b.js:1)
    at async t.project (polkadot.01.a30dbe3b.js:1)
 ```

It looks like the new runtime upgrade has been enacted about 8 hours ago, this could be related:

https://kusama.polkassembly.io/motion/285

**Comment by sekram77** [comment]
the same for me, any operation with ledger returns this error "Txn version not supported"

**Comment by tededi** [comment]
Guys i cannot send my KSM to any other account using my ledger? Im using the most up to date version of Kusama on my ledger. Whats going on ?

**Comment by jaikoo** [comment]
I'm seeing this not just on my Ledger Nano X but also on my Safepal S1 too :(

**Comment by tededi** [comment]
Does anyone know where we go from here?

**Comment by nicolasochem** [comment]
New version of the Ledger Kusama app is being worked on:
https://github.com/LedgerHQ/app-kusama/pull/8

**Comment by sekram77** [comment]
I got this answer from Kusama support: "The problem seems to be caused by the runtime upgrade that Kusama underwent this weekend, which changed the transaction version. It seems that the Kusama Ledger app hasn't been updated to support the new transaction version yet, so it's incompatible at this point with the latest runtime version of the network.

I have contacted the Zondax team that develops the Ledger app about this, but haven't heard back yet. Hopefully they'll release a new version soon. Until that happens, though, there isn't much that can be done, I'm afraid."

**Comment by tededi** [comment]
thanks dude

**Comment by paradoxxx-tt** [comment]
Version 5.30 of the ledger app was released!

**Comment by peter1401maier** [comment]
Yes, many thanks to the developer. It works again!

**Comment by gunnertwin** [comment]
Closing issue, thanks!
