### ISSUE TITLE
Suggestion: When submitting extrinsic which generates an event, show that event on the same page

### ISSUE THREAD

**Issue by shawntabrizi** [polkadot-js/apps#515]
Right now, the only way to view events generated from a transaction is to switch between the **Extrinsics** tab and the **Explorer** tab.

Events can be used to determine the results of a transaction (beyond simply being finalized). If possible, it may make sense to show the events generated by a specific transaction right on the same page where you submit the transaction.

**Comment by jacogr** [comment]
There are currently 2 places where events are displayed - explorer & global. 

The explorer displays all (well, almost all - it filters the system events since it drowns out the rest). This is completely driven by metadata, so no special logic to display these, what is received is displayed based on the metadata types.

Globally we filter on 1 type "Transfer" and this shows a pop-up if we receive something to an account we own. The latter approach does need some work, both in adding more useful-to-the-user known types and cleaning up somewhat in terms of how it gets displayed. So here we have some hardcoding independent of the dynamic runtime metadata.

Going back to your suggestion - we actually don't have a way to determine (from metadata) that a specific extrinsic will generate a specific event. It could be "when submitting from section, display all events for said section" (although these are global and could/could not relate to what has been submitted) or hardcode (which goes against having flexible metadata from the runtime) extrinsics to metadata mappings. (Which caters for base Substrate chains, but not customised chains)

Open to any suggestions as to how this could play out.

**Comment by shawntabrizi** [comment]
Here is a specific scenario where I think this could help. Imagine performing a runtime upgrade on a test node, but selecting a user like Bob instead of Alice. Bob is not actually able to upgrade the runtime, but from the perspective of the Extrinsics UI, everything looks good, and we even get the green "finalized" notification.

Only if you go into the Explorer would you see that the event `Upgraded` was not emitted, and may hint to you that Bob does not have the permission to upgrade the chain.

> we actually don't have a way to determine (from metadata) that a specific extrinsic will generate a specific event

This is an obvious blocker to such an idea, but seems like something that would be valuable for scenarios like the one above and many others.

> Globally we filter on 1 type "Transfer" and this shows a pop-up if we receive something to an account we own

Can you share a link to the code for this? Would I be able to create a runtime module with an event "Transfer" and trick the UI to show your pop up?

**Comment by jacogr** [comment]
100% the Transfer gets emitted here - https://github.com/polkadot-js/apps/blob/next/packages/apps/src/Status.tsx#L41

I did say "some work remains" :) The status is very limited since it was orginally added to show info when something happened with an account - so it was appropriated to display transfer as well, however it is really not as generic as it should be at all. (In the case of transfers this fits, in the case of something like #516 - it would need to be tweaked)

For local dev chains listening on https://github.com/polkadot-js/api/blob/master/packages/types/src/Metadata/latest.json#L388 could be added globally (your specific example), since it is "interesting" - the only thing here would be the current hacky "value as recipient" above - so some tweaks required, and also for the one I linked to above. (But yes, the specific Upgrade one would make sense to display globally anyway)

**Comment by shawntabrizi** [comment]
Thanks for your responses. This helps frame things a lot. To be more clear, my specific example was one that I thought was immediately relatable, but not necessarily my final goal.

I am working on documentation to help new developers build Substrate runtimes, and part of that process is teaching them about Events, how to use them etc... For example, we know that runtime modules cannot panic, so in situations where a transaction "internally fails" we need to monitor the presence of an event, or lack-there-of.

As someone who is writing a module with a basic event, it struck me odd that I was unable to see the results of my extrinsic on the page where I submitted that transaction. I am not able to determine whether the extrinsic I sent was successful or not (in the eyes of the runtime) without going into other pages like the block explorer.

Your suggestion to add more pop-ups definitely make sense for the important events in the SRML, however from a developer perspective, it initially feels like this scenario has been missed. Albeit, I may have a misunderstanding of how events should be used and stretching them to do more than they should/can.
