### ISSUE TITLE
adding account via seed creates different account in Polkadot-JS vs browser plugin

### ISSUE THREAD

**Issue by colourful-land** [polkadot-js/apps#5237]
1. Create an account with the following seed phrase:

````
language message lizard valley submit excite scheme flee top oyster rocket joke
````

2. Observe that the resulting account in Polkadot-JS is `16ULbyZBmrgcoqnjDnmSTBB5RvVVEPuTCByNUSjxrJTz8Aty`

3. Create (restore) an account in Polkadot.{js} Firefox plugin using the same seed phrase

4. Observe that the resulting account is: `5HY3TeJ7v5R9NJnDG9iSK2LvaJVqY6MK7hEtK9kcJDSTwo4q`

**Comment by jacogr** [comment]
If you don't specify the chain, it will use the Substrate generic defual. Each chain had a different (human-only, underlying data the same), encoding format.

![image](https://user-images.githubusercontent.com/1424473/117561535-df6dd700-b097-11eb-8226-9c53fee83243.png)

As per above, since you expect a Polkadot address, you need to select Polkadot. The addresses match.
