### ISSUE TITLE
How should I configure my service interface? 

### ISSUE THREAD

**Issue by 99Kies** [polkadot-js/apps#5389]
polkadot.js/apps
![image](https://user-images.githubusercontent.com/45918704/120061947-2bf27400-c092-11eb-887b-b9f53be003f3.png)

nginx config
![image](https://user-images.githubusercontent.com/45918704/120061987-4fb5ba00-c092-11eb-8877-b8dbc3bc4e61.png)

substrate info
![image](https://user-images.githubusercontent.com/45918704/120062012-7116a600-c092-11eb-8ccb-8996787dfbaf.png)

**Comment by 99Kies** [comment]
What's the problem with my inability to find the interface.

**Comment by jacogr** [comment]
https://wiki.polkadot.network/docs/en/maintain-wss

**Comment by 99Kies** [comment]
![image](https://user-images.githubusercontent.com/45918704/120062796-8261b180-c096-11eb-8f3e-f1c107bdedc1.png)

This is the error I tracked down

**Comment by 99Kies** [comment]
WARN ThreadId(19) jsonrpc_ws_server::session: Blocked connection to WebSockets server with untrusted host: Some("my_url")

**Comment by jacogr** [comment]
No idea, this is completely out of my wheelhouse - never setup an RPC node.

**Comment by 99Kies** [comment]
> No idea, this is completely out of my wheelhouse - never setup an RPC node. (The apps UI and API only uses them, as setup)

Is it because of my version problem? I used sbustrate3.0

**Comment by jacogr** [comment]
As I mentioned, I cannot be help here - your node is not accepting the connection, so it is misconfigured. Since I have never configured a RPC node for use on public networks (there are operations teams that deal with infrastructure),, cannot be of any help.

This repo uses RPC nodes, it doesn't configure them. This is not related to the UI code at all, so cannot be of assistance here.

**Comment by 99Kies** [comment]
thx, U are right.
