### ISSUE TITLE
Account balance suddenly goes to 0?

### ISSUE THREAD

**Issue by VadneyK** [polkadot-js/apps#5487]
Hello, 

my test account seems to have 0 pld on the ui but I had abt 999kPLD yesterday and we can see that I do have ~999kPLD when I deploy a smart contract from the test address. Then When I re-deploy the program states I have 0 PLD. Does this just happen sometimes since the  UI is in development or is this a known issue with a solution? or did my PLD actually just dissapear? I'm not sure if this is a general polkadot ui or plasm problem so just posting here in case anyone is familiar with this issue.

More detail here since I don't know what's actually causing the issue so I'm cross-posting: 
https://github.com/patractlabs/redspot/issues/117#issuecomment-856321456

**Comment by jacogr** [comment]
The API always tracks the latest types for Substrate master by default. This is generally what is deployed in chains with a continuous upgrade cycle, such as Kusama and Polkadot - a number of chains are quite far behind in releases and therefore need additional type overrides. 

The developer console should point to which types fail to decode, for balances  it is generally an outdated AccountInfo types, i.e. no overrides specified for it. (I cannot comment on "PLD" since I actually have no idea which chain "PLD" refers to).

**Comment by VadneyK** [comment]
was burned by network owner
