### ISSUE TITLE
The latest web wallet cannot display the balance, how do I fix it

### ISSUE THREAD

**Issue by differs** [polkadot-js/apps#5488]
my node is substrate v3.0.0

can let us select a apps wallet version, when connect

**Comment by jacogr** [comment]
Substrate 3.0 is quite old at this point. Since then the interfaces has changed a lot. It is quite possible that in this case it is an `AccountInfo` mismatch where newer non-legacy chains (Substrate master, Kusama, Polkadot, etc.) have moved to an updated version.

Check the dev console, it should indicate which decoding are failing due to mismatched types. 

As I'm guessing it is the `AccountInfo` type, injecting the type for the legacy `"AccountInfoWithProviders": "AccountInfoWithDualRefCount"`may solve the issue.

**Comment by differs** [comment]
> Substrate 3.0 is quite old at this point. Since then the interfaces has changed a lot and the API will always track the latest interfaces for current chains. It is quite possible that in this case it is an `AccountInfo` mismatch where newer non-legacy chains (Substrate master, Kusama, Polkadot, etc.) have moved to an updated version.
> 
> Check the dev console, it should indicate which decoding are failing due to mismatched types.
> 
> As I'm guessing it is the `AccountInfo` type, injecting the type for the legacy `"AccountInfoWithProviders": "AccountInfoWithDualRefCount"`may solve the issue.

thanks for your reply, but not working. I want to know where I can find the mismatched types, in which file?
