### ISSUE TITLE
Polkadot claim went to unknown address - can someone take a look at what could have happened?

### ISSUE THREAD

**Issue by jacbond** [polkadot-js/apps#5867]
It's coming up to a year since I claimed DOTs and they went to an unknown address. I wrote [a post on Polkassembly](https://polkadot.polkassembly.io/post/21) about it which explains the steps I took and what happened. Essentially during the claiming process the DOTs went to an unknown address, one that doesn't appear in my Account in polkadot.js but unusually did appear in my Address Book there (see attached pic of how it looked at the time). To me, this would suggest there was an interaction between these addresses - but I didn't create the account with the claimed DOTs in, if I did I assume it would appear in my Account within the app, which it doesn't. 
![Photo from Jac (1)](https://user-images.githubusercontent.com/87807263/126622584-41ff9d22-ae91-4ca1-84e9-7a6bd3cdc028.jpg)

I've raised this issue with councillors but not had much luck receiving an explanation for what happened. I also raised directly with Gavin Wood and at the time he said if anyone could explain what happened it would be @jacogr who wrote nearly all the code for polkadot-js. Am hoping that @jacogr or someone could look into my case and hopefully provide insight into what happened. I was going to start a public referendum and raised the DOTs to do this but I’ve since found out I might not get the DOTs bond back if unsuccessful, so don't want to risk losing what I have. I appreciate these DOTs are likely to be unobtainable now but I’d appreciate if some explanation could be provided as to what could have gone wrong. Thanks in advance.

**Comment by jacogr** [comment]
While I didn't do the claiming for Polkadot (I did the initial version on Kusama, for Polkadot the process was expanded with attestations, which were not in Kusama), I did review the code. 

The TL;DR is that If the address is in contacts, it means the user copied in the address as the destination, instead of selecting one of their existing accounts as the destination for the allocation.

The process is, step-by-step -

1. select an address to claim to (either select one of your accounts or paste in a different address)
2. sign (with your ETH account) the fact that you want to transfer to this address (destination is part of the signed message)
3. attest & submit

On-chain this submitted & signed ETH message is used to determine where to make the allocation, i.e. the destination address is exacted from the message signed with the ETH key.

**Comment by jacbond** [comment]
Thanks for getting back to me, appreciate that. Can I ask, is it possible to create an account but it not appear in polkadot.js extention? It's just that if I had created the account the DOTs went to am sure it would be in the extention.

**Comment by jacogr** [comment]
The extension only shows accounts that have been created inside the extension itself.

All these account types can interact with the apps UI and will show up as available -

- Parity Signer or Stylo (accounts tied to mobile device)
- Ledger (accounts tied to physical device)
- Extension (accounts tied to browser instance)
- Apps UI itself (accounts tied to browser instance)

**Comment by alobaied** [comment]
@jacogr Hi 

I was trying to stake some dots and I sent them to you instead of staking them, could you please send them back to me ![image](https://user-images.githubusercontent.com/88791888/129435358-8e620e67-5002-4b09-b289-97e8d769a4a2.jpeg)

Regards
