### ISSUE TITLE
Errors on master, not present on IPFS versions

### ISSUE THREAD

**Issue by Swader** [polkadot-js/apps#5881]
The following error appears when trying to use polkadot.js.org/apps with Statemine. When using an IPFS version, everything works fine.

![image](https://user-images.githubusercontent.com/1430603/127151461-d45ad57a-d4b6-4fbe-b81f-7e688d856367.png)

**Comment by alice-und-bob** [comment]
I am having a similar issue, but when using the IPFS version too.

When trying to send tokens to a user, this errors appears in the console:

![image](https://user-images.githubusercontent.com/87834086/127272054-bccd1902-94d6-4cce-9c71-aa0755d664c1.png)

**Comment by jacogr** [comment]
This is from the node itself. It most-probably happens when connecting to an RPC node where the node version doesn't match the runtime version and it runs native execution or something similar. (We just went through a runtime upgrade)

So check the different RPC nodes, since it seemed to have worked on at least 1, would check all the 3 to find the working vs non-working providers.

**Comment by alice-und-bob** [comment]
@jacogr i deleted my comment since it was exactly that issue. I changed RPC node and it worked.

**Comment by jacogr** [comment]
Which node(s) are problematic?

**Comment by Swader** [comment]
OnFinality is the broken one

**Comment by jamesbayly** [comment]
We (OnFinality) are looking into it.

**Comment by AlexZhenWang** [comment]
Hi, @Swader may I ask how I can reproduce this error?

**Comment by jamesbayly** [comment]
@alice-und-bob  we have resolved this
