### ISSUE TITLE
How can I define `alias` in polkadotjs app for additional types?

### ISSUE THREAD

**Issue by frankli-dev** [polkadot-js/apps#5961]
I have type clashes so I want to define alias for additional types.

I tried in different ways but none works.

```
{
 "typeAlias": {
   ...
 },
 "types": {
   ...
 }
}
```

```
{
  "types": [
    {
      ...
    }
  ],
  "alias": {
    "palletname": {
      ...
    }
  }
}
```
Please help me. Any examples are welcome! Thanks

**Comment by jacogr** [comment]
You can't. It is also not something that will be added since the need for that goes away with Metadata v14 where all types are actually returned in the metadata, i.e. it makes specific-types specification unneeded. Basically any work on this area is bound to be short-lived and throw-away, so it is not something that will receive any enhancements.

(The Substrate/Polkadot/API PRs for this is ready for merge so it will go into Substrate soon)
