### ISSUE TITLE
Restoring account problem both via .json & seed

### ISSUE THREAD

**Issue by paulussus** [polkadot-js/apps#6341]
Good Day!

I've set up an account via polkadot.js chrome browser extension a couple of months ago, however it was dormant throughout this period. After doing some reading before deciding to post here - I probably created general Substrate account ("Allow use on any chain option"). Seed & password saved and stored safely.
Recently I decided to fund it with some DOT for upcoming parachain auctions.

1. After I tried to make a transfer on via wallet extension wallet I was getting notification that the password is wrong.
2. Decided to restore account, but realized I don't yet have .json
3. In browser extension clicked "+" => "Export all account" => entered SAME PASSWORD as above which was ACCEPTED=> received json file "batch_exported_account_123xyz..json".
4. Deleted original account and tried to restore via SEED (in order to be able to change password).
5. However the account restored via seed had different address and of course no funds.
6. This time I tried to restore via .json obtained as described above - correct account was restored with funds, but still I can't do anything because of not having the correct password.

Now I'm in this vicious circle - can't transfer funds because I can't change the password on funded account, because seed phrase restores some different account. 
I don't really recall changing any default settings when creating account (custom derivation path etc.) however it was created a few months ago. 

Is there any way to reset / change paasword to my DOT account in order to be able to move funds?

**Comment by Thezatiny** [comment]
I

> > Omg, I thought there was something wrong with me. I have the same problem, if I try to recover it using the seed phrase, it just creates a new account. And I still can't transfer DOT. Have you solved the problem? I have emailed the support team but have not received a response.
> 
> Hi Thezatiny,
> 
> Thanks for sharing the same issue. Unfortunately I haven't found any solution yet. Maby someone will finally look into the problem and suggest a solution.
> 
> If you get any response from the support team, pls. share here,

I've sent couple emails to the support team, but they said the answer will be after the 1st Nov.

**Comment by ogarralda** [comment]
TEngo el mismo problema escribo la contraseña y me dice que es invalida debo haberla anotado mal aunque me extraña sumamente porque habia que repetirla

**Comment by paulussus** [comment]
> I
> 
> > > Omg, I thought there was something wrong with me. I have the same problem, if I try to recover it using the seed phrase, it just creates a new account. And I still can't transfer DOT. Have you solved the problem? I have emailed the support team but have not received a response.
> > 
> > 
> > Hi Thezatiny,
> > Thanks for sharing the same issue. Unfortunately I haven't found any solution yet. Maby someone will finally look into the problem and suggest a solution.
> > If you get any response from the support team, pls. share here,
> 
> I've sent couple emails to the support team, but they said the answer will be after the 1st Nov.

Hi,

Any news from the support team?

**Comment by ogarralda** [comment]
Esta es la respuesta, que realice al pie de la letra en todas sus formas y no hay caso, ya les respondi correo, ahora esperando



¡Gracias por contactarnos!

Ha llegado al Soporte de la Fundación Web3. Podemos ayudarlo con preguntas relacionadas con Polkadot y Kusama y con cuestiones relacionadas solo con elcarteras listadas aquí<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwiki.polkadot.network%2Fdocs%2Fbuild-wallets%23supported-wallets&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312159171%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Fnghdz7cC%2FDcptrkPDwPfJn6Uv5kBjj8jGgrxRlWKkE%3D&reserved=0>.

Encuentre las respuestas a las siguientes preguntas más frecuentes directamente a través de los siguientes enlaces:

  *   Cómo destake/unbond tokens KSM/DOT<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.polkadot.network%2Fsupport%2Fsolutions%2Farticles%2F65000167902-how-can-i-unstake-my-tokens-again-&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312169133%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=u5nhCm19HKd8PXPLowUVUKA6J%2FQJ8GV3yEvGoDRuHMw%3D&reserved=0>
  *   Dónde comprar DOT<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.polkadot.network%2Fsupport%2Fsolutions%2Farticles%2F65000068701-where-to-buy-dot&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312179094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D1v3FhC1inh6Cg7OSCXKNmcY2HazMv%2BUrZ3GM6xSMaQ%3D&reserved=0>
  *   ¿Es el "Proyecto X" realmente<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.polkadot.network%2Fsupport%2Fsolutions%2Farticles%2F65000173908-is-project-x-really-part-of-the-polkadot-eco-system-&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312179094%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=nFwqvhSZqQq9hshf0klZWD8qxZVBp60ggcjOz8XwHGQ%3D&reserved=0> parte del ecosistema polkadot?
  *   Cómo enviar DOT/KSM desde la interfaz de usuario de Polkadot-JS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.polkadot.network%2Fsupport%2Fsolutions%2Farticles%2F65000170304-how-to-send-transfer-funds-out-of-your-dot-account-on-polkadot-js&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312189047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=%2BqesKi66Dv%2Fyj05t7m%2FiVmDaLu16XKKj9iZePlMCuRs%3D&reserved=0>
  *   Cómo restaurar mi cuenta<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.polkadot.network%2Fsupport%2Fsolutions%2Farticles%2F65000169952-how-to-restore-your-account-in-polkadot-js-and-the-polkadot-js-browser-plugin&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312189047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=JUds9A1PiSuTOImCbMpz3StWggNAfu7auv5TjOPIEgE%3D&reserved=0>
  *   ¿Cómo accedo al NFT que reclamé de la campaña parachains?<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.polkadot.network%2Fsupport%2Fsolutions%2Farticles%2F65000178939-how-do-i-access-the-nft-i-claimed-from-the-campaign-&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312198991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=rGLEdJorG2qHAXnUVZ0mmlc1rlRKRHaJjRDlXtwu6z0%3D&reserved=0>
  *   ¿HAY UN SORTEO DE POLKADOT EN MARCHA? NO. Hay muchos impostores y estafadores por ahí, por favoraprende aquí cómo<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwiki.polkadot.network%2Fdocs%2Fen%2Flearn-scams%23docsNav&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312198991%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=OwhpgFVhPnM49x7SOuSKxiDn3ZdKOk0iVoMI0wRCXqY%3D&reserved=0>protegerte. No importa cuán legítimo parezca, si ve una promesa "Envíenos x cantidad y le enviaremos 3x de regreso", ¡es una estafa!

Si su pregunta no se responde anteriormente, se le invita a buscar una solución en nuestra página de soporte.<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsupport.polkadot.network%2Fsupport%2Fhome&data=04%7C01%7C%7C9ea41e8804ec48f478e708d9a090a12e%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717365312208955%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bH%2FYKpfozaGGfQT5%2FJHptWapg0zYKMdrY6kJF0CVnuI%3D&reserved=0> Simplemente escriba una palabra clave en el campo Buscar y lo más probable es que encuentre su respuesta.

Para cualquier pregunta relacionada con:

- otros proyectos en el ecosistema Polkadot (Acala, ChainX, Edgeware, Plasm, etc.)
- carteras de terceros o cuentas de intercambio y transacciones entre ellas
- otras cadenas de bloques, como Ethereum o BSC

póngase en contacto directamente con sus respectivos equipos de atención al cliente. Para cualquiera de estos problemas o preguntas respondidas en las preguntas frecuentes anteriores, probablemente no nos responderemos a usted. De lo contrario, haremos todo lo posible para responder dentro de las 48 horas de lunes a viernes.

Actualmente estamos lidiando con una mayor carga de solicitudes de soporte y puede llevar más tiempo responderle.

Si encontró una respuesta o su problema se resolvió mientras tanto, háganoslo saber respondiendo a este correo electrónico.

________________________________
De: paulussus ***@***.***>
Enviado: sábado, 6 de noviembre de 2021 03:28
Para: polkadot-js/apps ***@***.***>
Cc: ogarralda ***@***.***>; Comment ***@***.***>
Asunto: Re: [polkadot-js/apps] Restoring account problem both via .json & seed (Issue #6341)


I

Omg, I thought there was something wrong with me. I have the same problem, if I try to recover it using the seed phrase, it just creates a new account. And I still can't transfer DOT. Have you solved the problem? I have emailed the support team but have not received a response.

Hi Thezatiny,
Thanks for sharing the same issue. Unfortunately I haven't found any solution yet. Maby someone will finally look into the problem and suggest a solution.
If you get any response from the support team, pls. share here,

I've sent couple emails to the support team, but they said the answer will be after the 1st Nov.

Hi,

Any news from the support team?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpolkadot-js%2Fapps%2Fissues%2F6341%23issuecomment-962403094&data=04%7C01%7C%7C645c2c6480e54be404a808d9a0eea0ca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717769027576524%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=KLNlSfoorU0GdhMvFH8sXBhz6V0Mc2Z4iZV%2B0paDPi4%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FANOOFTWU42VSH7AVUJCWJI3UKTDIJANCNFSM5GJSDVJA&data=04%7C01%7C%7C645c2c6480e54be404a808d9a0eea0ca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717769027586478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=IvkqE9D5xAjiJOHyKOOLOiLBir6wYsEZk6kcRZ3qwyc%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C645c2c6480e54be404a808d9a0eea0ca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717769027586478%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Hhd3PG3vDUq%2Bqdl6Vvf5c2TNxrGg%2F0JbL4jqax3OBg8%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C645c2c6480e54be404a808d9a0eea0ca%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637717769027596440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=FYpHFVXToe9L2gL48yNufCl%2BJCZctunJ0UzdcUJBhic%3D&reserved=0>.

**Comment by paulussus** [comment]
Jeez, bumping it up.
The problem still exist.
NOT a single dev / eng can solve this issue?

Have I done something wrong and need to accept loosing my funds? Seriously guys? DEVs?
