### ISSUE TITLE
undefined.undefined in Events panel

### ISSUE THREAD

**Issue by vyorkin** [polkadot-js/apps#6468]
I'm using the `master` branch of this repo.
My node is using the `polkadot-v0.9.11`/`release-v0.9.11`-branch for substrate/cumulus/polkadot dependencies.
Here is the event I see after successful transfer:

![image](https://user-images.githubusercontent.com/988849/140062069-1b1c435e-da65-4cc6-b77e-47d1b9bef900.png)

The error message and a stack trace:

```
Uncaught error. Something went wrong with the query and rendering of this component. Please supply all the details below when logging an issue, it may help in tracing the cause.

value.typeDef is undefined
EventDisplay@webpack://@polkadot/apps/../react-components/src/Event.tsx?:37:18
```

Possibly related to #6223

**Comment by jacogr** [comment]
With metadata v14, it is "tricky" finding the events, i.e. they are named different between runtimes. So for instance you have `NodeRuntimeEvent`, `PolkadotRuntimeEvent`, ... etc.

The linked issue was because of `node_template_runtime::Event` not being correctly detected as `NodeTemplateRuntimeEvent` and thus mapping to events. (These do work correctly now, so not quite the same)

This _may_ be similar with some other spec_name throwing out the ability to find the events, but at this point the only way to check is that you supply the decoded metadata from the RPC calls section (state.getMetadata)
