### ISSUE TITLE
extrinsics page and others hidden without extension loaded

### ISSUE THREAD

**Issue by mochet** [polkadot-js/apps#6625]
Problem: if you load https://polkadot.js.org/ without the extension installed/loaded it hides the extrinsics page and other parts of the interface. This means if you're browsing through various chains you either have to manually activate the extension or create a key for each chain.

This is an annoying design, if a user just wants to explore what a chain can do they have to load in an extension even if they have no intention of actually using the chain at all.

Suggestion: enable the view of all pages, regardless of extension being active/installed, and just show on those pages that no transactions can be performed until the extension is installed or a key is created.

**Comment by jacogr** [comment]
This won't change.
Yes, the logic can certainly be reworked to detect anything where an account is needed - which, well, is everything under extrinsics, aka the result would be exactly the same - a blank page since there is no account to be selected to submit from. Under state this is more nuanced, so everything needs to be parsed first to detect account usage before displays.

In-short, this won't be "fixed", there is a maintenance cost and this greatly adds complexity.
