### ISSUE TITLE
Accounts page always shows Create Account tab active

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#664]
When I go to https://poc-3.polkadot.io/#/accounts, and choose "Accounts", and choose a tab other than Create Account (i.e. Restore Account or Vanity Address), it still shows Create Account as being active

<img width="1064" alt="screen shot 2019-01-31 at 10 17 11 am" src="https://user-images.githubusercontent.com/6226175/52019379-b61d8280-2541-11e9-8970-f484ee9b85a7.png">

**Comment by jacogr** [comment]
This is due to mucking about with the hidden (no edit on first, so create becomes default) and the fact that `create` can take a param (to pass the seed from vanity).

https://github.com/polkadot-js/apps/blob/master/packages/app-accounts/src/index.tsx#L52

via

https://github.com/polkadot-js/apps/blob/master/packages/ui-app/src/Tabs.tsx#L45

So above `exact` flag can be tweaked for first-tab, however then when the seed is passed from vanity the tab won't be active. The correct would be to have the initial path to `/accounts/create` when nothing there. (Instead of tweaking paths in Tabs)

(* Marked as addresses as well since it has the same hide (so any fix should be working against both)

**Comment by jacogr** [comment]
Minimal workaround -

- hide vanity with edit (i.e. not available on first create, so no seed passed)
- check for exact/strict becomes `{!hasParams || index === 0}` (not pretty, but minimal)

Exact path fix -

- `Redirect` on bare to a named path (i.e. `/accounts` -> `/accounts/create`, instead of the `Switch` component map, also in addresses)
- Remove `index === 0` path override in Tabs
