### ISSUE TITLE
`Fast track` button should not be disabled for `SuperMajorityAgainst` external proposals

### ISSUE THREAD

**Issue by ghzlatarev** [polkadot-js/apps#6751]
Hi, currently this button is greyed out like for proposals created with `democracy.externalProposeDefault()` like so:
![disabled](https://user-images.githubusercontent.com/45011053/147667753-d37bf9ce-1b16-4667-bef3-f7e548f247f9.PNG)

However looking at the [substrate code](https://github.com/paritytech/substrate/blob/master/frame/democracy/src/lib.rs#L844
) we can see it should only be disabled for `VoteThreshold::SuperMajorityApprove` To sanity check `democracy.fastTrack` can manually be submitted successfully for proposals created with `democracy.externalProposeDefault`

I think [this line](https://github.com/polkadot-js/apps/blob/master/packages/page-democracy/src/Overview/Fasttrack.tsx#L158) needs to be changed to `isDisabled={threshold.isSuperMajorityApprove}` but there might be some other places, not too familiar with the code base.

**Comment by jacogr** [comment]
There is a reason for this - it is the only codepath that is actually tested. Since I (and I extend this to a "we" on what is used in the fast-track proposals I'm involved in), only use the other form, have never hit this path, nor looked at it. There are actually a number of these things sprinkled around, i.e. Substrate allows it, but it is not something ever tested or actively looked at, so disallowed.

**Comment by ghzlatarev** [comment]
Gotcha.

**Comment by jacogr** [comment]
Will mark for an investigation and test through with Substrate master.
