### ISSUE TITLE
Staking not working for older substrate versions

### ISSUE THREAD

**Issue by JelliedOwl** [polkadot-js/apps#6763]
It looks like a recent change has broken the staking pages for some of the old substrate version chains.  For example https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmainnet.edgewa.re (but I've seen other chains it's also not working for).

As far as I can tell, the format for the response to staking --> erasValidatorsPrefs has changed and the old format isn't being parsed any more.  Is there any possibility of a fix to make it work with the old and new format (assuming that's really the issue)?

**Comment by jacogr** [comment]
This is actually not related to the UI at all and nothing that can be fixed here. The teams themselves are managing the types, in this case it seems that the `ValidatorPrefs` structure is incorrect. It doesn't seem like there is any definition for it in https://github.com/hicommonwealth/edgeware-node-types/blob/master/src/interfaces/definitions.ts

There could be a breakage introduced by the API, but it won't be re-instated. In the past the API did it's best to try and detect types in various fashions, however it was not always spot-on. Since metadata v14 was introduced that problematic path was removed.

**Comment by JelliedOwl** [comment]
Thanks @jacogr.  Does that mean the only fix would require an upgrade on the Edgeware side, or is it something we can update without needing to change the on-chain executable?  Sorry, I'm decidedly vague on how it works.

**Comment by jacogr** [comment]
The package I linked to needs to specify the correct `ValidatorsPrefs` type, it would probably be -

```js
ValidatorPrefs: { commission: 'Compact<Perbill>' }
```

**Comment by JelliedOwl** [comment]
Ah, and then it gets pulled in from here: https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/edgeware.ts

Thanks - I'll see if I can get it updated on the Edgeware end.
