### ISSUE TITLE
Incorrect metadata decoding for genesis runtime of CC

### ISSUE THREAD

**Issue by emielvanderhoek** [polkadot-js/apps#680]
I have connected the Polkadot-UI to my own archive node to determine the decoded JSON object for the metadata specification of current and previous runtimes of the Alexander network and the Charred Cherry network.

The genesis runtime (first runtime) of the Charred Cherry network does not decode to a proper JSON format (toolbox function in UI).

The following gist shows the input of 'state_getMetadata' and the formatted JSON output provided by the UI. https://gist.github.com/emielvanderhoek/eb543bbc72ad8c25c6a0e9c05a5a49c6

Line (437) in the gist shows one example of improper decoding: https://gist.github.com/emielvanderhoek/eb543bbc72ad8c25c6a0e9c05a5a49c6#file-charredcherry_01_decoded-json-L437

**Comment by jacogr** [comment]
It is pre defaults. I can see it breaks straight after a default definition. Not much that can be done here, sadly. The defaults were a breaking change, done in a non-backwards compatible manner and had to be carefully coordinated with chain rollout. 

Since the old format is not supported, not sure it warrants an API fix. 

@amaurymartiny thoughts? 

(The issue obviously in new syncs or archive retrieval)

**Comment by amaurymartiny** [comment]
I believe `@polkadot/api` might actually not be 100% suited for block explorers, the target users are more "regular" dapps who play around the top of the chain. Maintaining all possible versions of the metadata (and the exact point where each of them start/end) in `@polkadot/api` is a huge task, and I'm not sure it's a feature most dapp developers would use, so I'd argue to not implement it in `@polkadot/api`.

**Comment by jacogr** [comment]
As much as I hate not having _everything_, going to close as "wontfix".

The only good news is that going forward, since we actually have versioning now, this won't be an issue to have multiple incompatible version support.
