### ISSUE TITLE
Feature request: Button to 'Open in JS Console' from extrinsics/chain state panes

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/apps#6846]
We all loved the VBA record macro button as a kid. Would be great to have polkadot js have the same:

Use case:
1. First we create some extrinsic or ask for some storage or query some constant:

![Screenshot(17)](https://user-images.githubusercontent.com/803976/149977126-f7a8a368-65ff-41d2-b086-be1fc031e314.png)
Button here: **'Open in JS Console'** 

2. Then we press the button:  'Open in JS Console' and hey presto some javascript appears:

![Screenshot(16)](https://user-images.githubusercontent.com/803976/149977139-5d662946-a2b7-4836-b1f1-beb26a1c23f7.png)

Wouldn't this be cool? I have a hunch we have all the pieces to do this but just have not wired them together yet. Would be a cool project for someone to do and might turn out to not be too tricky to get a beta version working... even if it is not perfect at first it would likely save people time and point people in the right direction.

**Comment by gilescope** [comment]
how does it get labelled as an enhancement?

**Comment by jacogr** [comment]
The query/extrinsics interfaces are vastly different. It is certainly possible to, with the params, create a JS version. (Some things would be easier than others since you need to convert the internal params formats into something JS-code-like before passing it, but it certainly is nowhere close to "wiring it up")

While this could be nice, there are certainly an overflowing queue of "must have enhancements" which always gets priority - and this is only one repo of many in this org which gets appropriate sliced time. So not going to add this to the queue, although would certainly look at any PRs that does implement things like this (and others that are not logged at all).
