### ISSUE TITLE
multisig account in different networks

### ISSUE THREAD

**Issue by pserg1** [polkadot-js/apps#6908]
Steps to reproduce: 

1. Go to https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/accounts
2. Add msig participants to the Address book. 
3. Add msig account on the Accounts tab. 
4. Switch network / project ( I tried  https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fapi-ivy-elastic.clover.finance#/accounts)
5. Perform steps 2 and 3
6. Msig account and list of its participants disappears from https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/accounts

**Comment by jacogr** [comment]
It is expected. There is no way to associate the same multisig to different networks, so the genesis will be set to the last network used.

**Comment by bLd75** [comment]
Hi @jacogr does that mean that for an organization like a DAO, each participant should each use a different address for different networks.
I know this is the historical recommendation but since parachains arrived, this becomes out of human manageable to do so and most parachain introduced same address use on different chains which is working quite fine actually.

Addresses derivation being just a different representation of the same key, shouldn't we shift the paradigm of 1 address per network now that we have some experience on it?
