### ISSUE TITLE
Block search always shows latest block, not the block being searched

### ISSUE THREAD

**Issue by nazar-pc** [polkadot-js/apps#6998]
With our testnet I see a strange issue (not reproduced on Polkadot) when regardless of what block is supposed to be rendered (via search or just by clicking one of the recently produced blocks), it always renders last produced block.

For instance, opening block 0x66a8f43b5af9fb2117b8dd98ef831944e20346bc766b99bb943aeb6fa0041099 (420_272) always renders the latest block: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ffarm-rpc.subspace.network#/explorer/query/0x66a8f43b5af9fb2117b8dd98ef831944e20346bc766b99bb943aeb6fa0041099

**Comment by jacogr** [comment]
The issue lies here - https://github.com/polkadot-js/apps/blob/master/packages/apps-config/src/api/spec/subspace.ts#L104

The top information is displayed from the `derive.getHeader(<blockHash>)` details. On your chain that derive always returns  the current header, not the header for the requested hash.

**Comment by nazar-pc** [comment]
Thanks for the hint, @1devNdogs we need to correct that.
