### ISSUE TITLE
Prevent / warn about sending to known test addresses on mainnet(s).

### ISSUE THREAD

**Issue by gilescope** [polkadot-js/apps#7008]
There is a known set of accounts that if you send funds to them they will likely be swept instantly. It would be nice if there was a warning should you try to accidentally send to a well known test account on main-net. 
(I mean no one would be that silly right? right? but remember copy and paste can be tricky on linux... 
Bots are sweeping those accounts because people do occasionally accidentally do it, so let's try and be nice to them.)

(Metamask should do this too but currently does not)

**Comment by gilescope** [comment]
oh no you don't.

**Comment by gilescope** [comment]
needs labeling as enhancement.

**Comment by jacogr** [comment]
The keyring doesn't inject the dev addresses (which is very different based on network, i.e. Moonbeam has their own specific derivations not Alice/Bob/etc.)

PRs welcome, but unlikely I'll queue it otherwise since you should not add these manually in either way, they get assigned in the keyring when dev chains are detected.

**Comment by gilescope** [comment]
I just don't want someone having a copy paste accident and accidentally try and send to Alice.
Alternatively we could warn that this is a new address that you have not sent to before. That might be more useful.
