### ISSUE TITLE
Broken layout of extrinsic that accepts a param of Vec type

### ISSUE THREAD

**Issue by siman** [polkadot-js/apps#729]
For extrinsic function (Rust) `fn set_council(accounts: Vec<T::AccountId>) {...}`.
It would be more user friendly to have an each param of Vec on a separate line.

![image](https://user-images.githubusercontent.com/153928/53004178-50822f00-3439-11e9-9c43-d895886cd528.png)

**Comment by jacogr** [comment]
I broke that recently fixing something else - thought I looked at _all_ angles, obviously not

Introduced here - https://github.com/polkadot-js/apps/pull/727

**Comment by jacogr** [comment]
I actually believe it was fixed in #727

<img width="1440" alt="polkadot apps portal 2019-02-19 14-24-06" src="https://user-images.githubusercontent.com/1424473/53018231-1f622880-3452-11e9-94d4-aadfe1ec2214.png">

The mismatch is that https://poc-3.polkadot.io is a managed manual deploy, where https://polkadot.js.org/apps/ is done by merge, so the latter always runs the latest master here.

(Next deploy cycle for poc-3 is close, there are a couple of low-hanging fruits left to address)
