### ISSUE TITLE
Wrapping shows up twice when swapping

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#733]
<img width="586" alt="polkadot apps portal 2019-02-20 07-44-12" src="https://user-images.githubusercontent.com/1424473/53071720-5896a900-34e3-11e9-85da-a9ee16b5e824.png">

To reproduce -

https://youtu.be/Ge8nLazGgJ8

I also had the selected one show up blank, it item selected, no code shows - but cannot quite reliably reproduce the steps for that, it seems züfallig?

**Comment by Stefie** [comment]
Yeah... I introduced a bug here yesterday... tought I fixed it with the  small PR I merged, but apparently I did not do the trick. I‘ll have a look

**Comment by Stefie** [comment]
All the imports for the component happen once when the component is first loaded, then all the imports seem to be cached. I never really thought about that... 
Is that a custom setting in apps or is that React default behaviour?

The Bug is that I only referenced the snippets import, I didn't deep clone it, that's why the wrapper got added multiple times the the component was re-mounted. 

Do you have any better better solution for deep cloning arrays than this:

`snippets: Array<Snippet> = JSON.parse(JSON.stringify(snippets));`

...or do we maybe even have a utility function for that? :)

We could use Lodash https://lodash.com/docs/4.17.11#cloneDeep , but you're not using it anywhere else atm.

The JSON dance is working perfectly fine, I just feel like there could be a nicer solution somewhere out there...

**Comment by jacogr** [comment]
As long as the snippets only contain primitives (string, number and friends), we are ok. No the prettiest, but I think it is ok here. The alternative is just to apply the `makeWrapper` stuff in the snippets itself, so when loaded, it has what it needs.
