### ISSUE TITLE
Invalid Host header

### ISSUE THREAD

**Issue by ygit1** [polkadot-js/apps#7337]
$ yarn run start
>>> Invalid Host header 

I use VPS. tried 0.0.0.0 but no

**Comment by jacogr** [comment]
You need to be _very_ specific when logging issues - without 

(a) what you are trying to do
(b) how you are doing it
(c) what you are accessing

There is absolutely nothing that can be done.

**Comment by ytytgo** [comment]
Sorry for the lack of explanation. I launched this app in my local environment, osx m1, and it works fine.
I want to run this on aws.
$ yarn run start
and then if I access to

mydomain.com:3000

the result is,

Invalid Host headers

**Comment by ytytgo** [comment]
Why do I want to run substrate on aws? Because I don't think it makes sense to run a para chain locally. when I close my Macbook, it closes the chain too.  I found a way to configure https and nginx settings etc, but it was unusually difficult. So I am thinking of using AWS for this. Am I right in my thinking...?

**Comment by ygit1** [comment]
I found the solution on yarn help page
