### ISSUE TITLE
Failed to vote

### ISSUE THREAD

**Issue by JayJay1024** [polkadot-js/apps#7367]
<img width="1540" alt="image" src="https://user-images.githubusercontent.com/21007682/163135497-ef4a0b1e-8102-4f82-899a-e2bd4320b8c8.png">

`apps v0.112.2-9`

**Comment by jacogr** [comment]
The above doesn't have much information -

1. which chain?
2. which referendum?

For instance on Kusama/Polkadot this would point to something broken in the voting itself, on other chains it points to wrong types specifications (assuming it is pre-v14 where the types are injected).

**Comment by JayJay1024** [comment]
it is on pangolin testnet now:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpangolin-rpc.darwinia.network#/democracy

**Comment by jacogr** [comment]
It can't be supported -

![image](https://user-images.githubusercontent.com/1424473/163144150-f62cb541-a0f0-430e-a30e-d3ed477dcd1e.png)

This is the standard Substrate Vote -

![image](https://user-images.githubusercontent.com/1424473/163144311-52c99957-c0bc-480a-a8a0-247b482f1421.png)

Will figure out a way to disable the democracy interface on apps where non-standard types are being used since we cannot construct the call correctly for that.
