### ISSUE TITLE
Min yarn/node versions?

### ISSUE THREAD

**Issue by moh-eulith** [polkadot-js/apps#7377]
According to the README, Yarn >=1.10.1 and Node >=10.13.0 are required.

It didn't work for me with:
```
Yarn version: 
  1.15.2

Node version: 
  10.15.3

Platform: 
  win32 x64

Trace: 
  SyntaxError: Unknown token: { line: 3, col: 2, type: 'INVALID', value: undefined } 3:2 in C:\projects\eulith\code\polkadot-js\yarn.lock
```
I upgraded to latest (yarn 3.2.0, node 16.14.2) and it works now.

**Comment by jacogr** [comment]
Node >= 14 required - Node < 12 has been deprecated, not supported by the Node.js foundation (support for Node 12 was dropped start of April). 

Yarn should be fine since it will use the local version, but keeping that updated to the latest 1.2x is always advisable.

**Comment by mohrezaei** [comment]
@jacogr thanks. I was just pointing out that the README needs an update.

**Comment by moh-eulith** [comment]
I would recommend updating the docs with the correct min versions.

**Comment by jacogr** [comment]
PRs always welcome. As suggested above, we cannot quite keep track of actual Node deprecations as well here (this is an own project), so that is up to the user to ensure they have something workable and supported. 

I would actually suggest as a co tributes PR to just remove all of it - bad use of the above tracking external projects issues.
