### ISSUE TITLE
AccountId dropdown does not allow enter new account address directly

### ISSUE THREAD

**Issue by xlc** [polkadot-js/apps#742]
I want to enter a new account in AccountId dropdown but in ends up been a filter and give me no results. I should be able to enter and able to use the address I pasted.

**Comment by jacogr** [comment]
Yes, this is problematic - it happens when using standard components with some enhancements, it doesn't quite do what you would expect it to when done from scratch.

I would appreciate if you could just post a step-by-step of what you are seeing, exactly how you get to where it doesn't quite fit the bill for you. (Just makes it slightly easier to capture and allowing anybody to pick up on it)

**Comment by xlc** [comment]
Start with transfer page

Click recipient address
![screen shot 2019-02-21 at 10 07 09 pm](https://user-images.githubusercontent.com/1201310/53156861-25f4c980-3625-11e9-99e9-1a7e695437b8.png)

Paste an address
![screen shot 2019-02-21 at 10 07 24 pm](https://user-images.githubusercontent.com/1201310/53157042-8edc4180-3625-11e9-9e67-65efad4e4f8a.png)
It show up in the recent field, not fully expected, but acceptable.

Hit enter
![screen shot 2019-02-21 at 10 07 32 pm](https://user-images.githubusercontent.com/1201310/53157123-b7643b80-3625-11e9-9451-619cc7a143b3.png)
The old recipient is selected. It should select the address I just entered.

Click on the recipient input again
![screen shot 2019-02-21 at 10 07 40 pm](https://user-images.githubusercontent.com/1201310/53157172-d06cec80-3625-11e9-9143-2727e7ca76a1.png)
Notice the position of the cursor is not correct

**Comment by Stefie** [comment]
I'm actually having a similar problem in app-js with the example dropdown. The <Dropdown> component seems to be a bit buggy when adding options dynamically in different phases of the react lifecycle.

**My Bug:**
There's a prop `selectedIndex` on `<Dropdown>` which you can't set programatically. If you're setting a defaultValue in the constructor and then change that in componentDidMount or componentDidUpdate, the `Dropdown` does update the option, but it's keeping the old index. Once the <Dropdown> looses focus, it switches back to the option that's selected with selectedIndex (which was set in the constructor of the component)

Maybe my findings help when debugging this one

**Comment by Stefie** [comment]
Ah, damned.... the original component from Semantic UI is using the soon to be deprecated `componentWillReceiveProps` and `componentWillMount` to update the internal state values. That might the problem.

https://github.com/Semantic-Org/Semantic-UI-React/blob/b8f5002220ba1f5cc1bf8bb5dabf5d95cb3c49f9/src/modules/Dropdown/Dropdown.js#L385

**Comment by Stefie** [comment]
Ah, ok, so it wasn't the same cause, which is good, because the root of my bug really is the fact that Semantic UI is using `componentWillMount` instead of `componentDidMount`. It's gone when I switch to `componentWillMount` in app-js. 
Worth keeping that in mind since it will probably not only affect this MUI component but could cause a number of bugs...

**Comment by jacogr** [comment]
They should convert... just add a FIXME to improper use with a why and we can track.

**Comment by Stefie** [comment]
They had a PR in October that changed the lifecycle methods for <Dropdown>, but that was closed, I'm just tracking down what happened. Might open one myself if it got lost since it looks like sth. that's already being worked on

**Comment by Stefie** [comment]
I left a comment, it's too much work to fix it on the fly now https://github.com/Semantic-Org/Semantic-UI-React/issues/3088#issuecomment-466010041
