### ISSUE TITLE
Raw payload wrapping error in QR generation for Signer

### ISSUE THREAD

**Issue by Slesarew** [polkadot-js/apps#7455]
When generating "sign raw payload" message (https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.polkadot.io#/signing), payload is wrapped in `<Bytes>` / `</Bytes>` but not scale-encoded. Parity Signer does not support signing non-scaled payloads (as undeclared arbitrary length of payload opens potential to pass scale-encoded payloads as something else). Thus, payload should be scale-encoded on top of <Bytes> wrap.

By the way, should `<Bytes>` wrapping be undone before signing? It is a bit not obvious from the interface whether the wrapping is always there.

For further details see https://github.com/paritytech/parity-signer/issues/1014

**Comment by jacogr** [comment]
Thanks for the heads-up will remove the functionality for QRs.

**Comment by mustermeiszer** [comment]
Hi @jacogr, 

I submitted the issue on the signer repo. Can I be of any help here? Not sure, I get what you are meaning on the above.

**Comment by jacogr** [comment]
So where do you sign from? As mentioned above, the apps UI signing page doesn't support QRs, so now sure what I should "fix" on the apps UI.

**Comment by jacogr** [comment]
Ok, but as I mentioned above -

1. Not sure where this appears in the apps UI at all?
2. There now seems to be 2 QRs out in the wild - that supported by Stylo (which used to work in the extension) and the new one which is not compatible. (That never transferred SCALE info, so at least on the extension will rip out support for since I cannot support 2 different interfaces via a single QR presentation)

**Comment by Slesarew** [comment]
Signer and Stylo both support "sign message" payload propetly - and that *is* scale-encoded. This non-scaled thing just started popping up recently - never seen anyone getting those issues before recently.

**Comment by chevdor** [comment]
One of the use case are people going thru identity verification and trying to sign the challenges they receive from the registrar.

**Comment by jacogr** [comment]
Ok, so how does this "start popping up recently" when the extension has not had a release to the stores since 0.42.2 https://github.com/polkadot-js/extension/releases/tag/v0.42.2 (10 Dec 2021).

**Comment by Slesarew** [comment]
This means that people started using this just now.

**Comment by mustermeiszer** [comment]
> How did you generate QR code in the screenshot?

**Comment by jacogr** [comment]
Ok, so it is not apps UI functionality, it is the extension functionality. That makes sense, I thought I was losing my mind.

For the extension have this logged https://github.com/polkadot-js/extension/issues/1052 will disable the functionality in https://github.com/polkadot-js/extension/pull/1053 which will make it into the next release.

**Comment by mustermeiszer** [comment]
Just for clarity: Does this mean there will be no possibility to sign raw-payloads or messages with parity-signer?

**Comment by jacogr** [comment]
Since there are 2 interpretations of https://github.com/maciejhirsz/uos#substrate-payload specifically -

As implemented it is, as described above, simply a string. The Parity signer assumes it is a SCALE-encoded message. We cannot support both when presenting a QR. So we end up with an implementation doesn't work for at least the Parity Signer and if the encoding has to change it will be broken elsewhere. So either way, issues get logged. 

So unless it can be verified as working in all QR-consuming devices (whichever is the presentation format for the QR), it is not something that is workable from an implementation perspective atm. I would however suggest moving extension-specific discussions on this to the extension itself since QR signing functionality for raw messages doesn't exist in the apps UI. (And sadly it is 2 very different beasts, so unless it is visible where it applies, it always gets lost)

**Comment by jacogr** [comment]
Closing, not apps UI related functionality, rather refer to https://github.com/polkadot-js/extension/issues/1052
