### ISSUE TITLE
Council motions' display start to look weird recently

### ISSUE THREAD

**Issue by GopherJ** [polkadot-js/apps#7790]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request (please bear the comments above in mind)
  - [ ] Other

* **What is the current behavior and expected behavior?**

![image](https://user-images.githubusercontent.com/33961674/175232502-93491808-bb09-4866-b834-81853a8614aa.png)
![image](https://user-images.githubusercontent.com/33961674/175232547-a061deee-813b-42b9-9fd1-918721814bf8.png)

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version:
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments available)

  - Language:

    - [x] JavaScript
    - [ ] TypeScript
    - [ ] Other

**Comment by jacogr** [comment]
Which chain?

**Comment by GopherJ** [comment]
@jacogr it happened on our live chain Parallel and Heiko network

**Comment by jacogr** [comment]
On parallel, there is something in the queue where the indexes moved and it cannot be decoded - the JS console throws up this.

`polkadot.02.08f676df.js:1 2022-06-23 14:31:44             DRR: Unable to decode storage generalCouncil.proposalOf: entry 0:: createType(Call):: Call:: Decoded input doesn't match input, received 0x32076500000000a89c1346020000000000000000000000d0ed902e0000000000000000000000 (38 bytes), created 0x32076500000000019c1346020000000000000000000000d0 (24 bytes)`

Once that happens, none of the proposals will be decoded until the offending proposal is removed. It is this one `0xd29fe1d599e3fe818d680751194226933d38c2ee1b772a762898f4047efbb3ff` (the second one is decodable)

**Comment by GopherJ** [comment]
@jacogr we seem didn't do anything special, it happened after upgrading to polkadot-v0.9.22

**Comment by jacogr** [comment]
You can see the issue here if you try and decode-

[#/extrinsics/decode/0x32076500000000019c1346020000000000000000000000d0](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparallel.api.onfinality.io%2Fpublic-ws#/extrinsics/decode/0x32076500000000a89c1346020000000000000000000000d0ed902e0000000000000000000000)

The data has extra contents, 10 bytes unused. which you can see in the re-encoding there. The API has no idea if this is mean to be or corrupted. Something changed oin-chain -

- the call signature changed in the runtime
- the indexes moved around in the runtime
- etc.

The API is 100% correct here is refusing to deal with it.

**Comment by jacogr** [comment]
It is most probably this PR - the call signature had been changed, so in-flight extrinsics before and after are not the same - https://github.com/parallel-finance/parallel/pull/1801

**Comment by jacogr** [comment]
No, the data is retrieved from the on-chain state.

**Comment by GopherJ** [comment]
@jacogr A few seconds ago I created a new motion for upgrading our chain but it looks still cannot be decoded. It's a new motion generated in runtime v187

**Comment by GopherJ** [comment]
@jacogr thanks! and I'm sorry that I missed that comment, I'll try it and thanks for your patience
