### ISSUE TITLE
Javascript dev console : previous error not getting cleared from output console 

### ISSUE THREAD

**Issue by muddlebee** [polkadot-js/apps#7799]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request (please bear the comments above in mind)
  - [ ] Other

* **What is the current behavior and expected behavior?**

Js dev console : https://polkadot.js.org/apps/#/js

Step 1 . Make some error in the js script and run it. The appropriate error shows in output console.

![Screenshot 2022-06-25 at 9 17 47 PM](https://user-images.githubusercontent.com/8139783/175781187-b2fd9d56-ca0f-46b8-bd5a-933bf26a3cc2.png)

Step2. Fix the error and run the script. The previous error message with the successful output gets appended together.

![Screenshot 2022-06-25 at 9 18 01 PM](https://user-images.githubusercontent.com/8139783/175781211-38ff4384-9d50-4c0c-b9d8-994e4a5102b7.png)

 
Clear previous output states before running the script again..

**Comment by jacogr** [comment]
There is an explicit user-drive clear button on the output,

![image](https://user-images.githubusercontent.com/1424473/175922742-bfec289e-7ada-40ab-be54-00699da0a02a.png)

This is intentional - specifically for the way I use it, I compare different outputs between changes. It would break horribly if this was auto-cleared. Obviously this does not fit all workflows, i.e. people may not want to clear manually via the supplied button, but since it would completely destroy my specific workflow (it was actually in an auto-clear mode right when it went in around 2-3 years ago), this won't change.
