### ISSUE TITLE
Update the display logic of the slashing page

### ISSUE THREAD

**Issue by kianenigma** [polkadot-js/apps#7920]
... IFF needed, since one storage items is being removed an the defintion of the keys in `UnappliedSlashes` is slightly changing, as per https://github.com/paritytech/substrate/pull/11823/files

**Comment by jacogr** [comment]
Removed here - https://github.com/polkadot-js/api/pull/5118/files#diff-fa159c3aa82e1d4780a5038af75643716aaaf0531ca608b31ce47199833a8159L1326

Used here - https://github.com/polkadot-js/apps/blob/master/packages/react-hooks/src/useAvailableSlashes.ts#L23

Dual support required.

**Comment by jacogr** [comment]
Logic is very different, so indeed 2 code-paths are to be used. Previous keyed on era-where-slash-occurred, now keyed on era-where-slash-is-applied which would mean the logic to determine the range is very different between the two (it would also need display adjustments since there is shows when the slash occurred)
