### ISSUE TITLE
Crash with new version of referenda pallet

### ISSUE THREAD

**Issue by valentunn** [polkadot-js/apps#8241]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/70131744/196100283-d67713dc-d2b9-4473-b05d-20e9f271cfce.png">

When connected to governance2-testnet, which uses new version of `referenda` pallet, referenda page crashes.
Crash seems to happen [here](https://github.com/polkadot-js/apps/blob/62262e9aafd1486e6eaa712d141b28bc731700c2/packages/page-referenda/src/Referenda/RefOngoing.tsx#L33) when accessing `ongoing.proposalHash` - `proposalHash` no longer exists in new versions of [ReferendumStatus definition](https://github.com/paritytech/substrate/blob/0ee03277c33b6334ddba7434e014fa637dcb6107/frame/referenda/src/types.rs#L178)

Testnet URL: wss://governance2-testnet.litentry.io

* **What is the motivation for changing the behavior?**

* **Please tell us about your environment:**

  - Version: v0.121.2-104-x
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by jacogr** [comment]
This is known, i.e. the new metadata highlights it as indicated in https://github.com/polkadot-js/api/issues/5266

It will probably only be addressed with the new API release that pulls in the new types from Substrate master. (There are some far-reaching issues that have been introduced in the API derives, apps UI, etc. due to the use of the new bounded calls, submission is another very problematic part)
