### ISSUE TITLE
How to generate the  MortalEra ? How tocalcute the period and phase?

### ISSUE THREAD

**Issue by LXHLeaner** [polkadot-js/apps#8495]
like this :
 era: {
          MortalEra: {
            period: 32
            phase: 0
          }
        }
=========>
{
        isSigned: true
        method: {
          args: {
            dest: {
              Id: acgQop9A8qdUq7J6N9oLYtMUszi2R3dFSFfxn7oWsRp4MX8
            }
            value: 1,000,000,000,000,000,000
          }
          method: transferKeepAlive
          section: balances
        }
        era: {
          MortalEra: {
            period: 32
            phase: 0
          }
        }
        nonce: 0
        signature: 0xce919aa73a2b5c256ec24d7ee404d0494102eeefe4c3134e894f8c0acec3a512166c16c155064a900ad50c458af453389680d032fb0209c07505427a9d5de48a
        signer: {
          Id: YwLrZHBegavW3S1m9WnmKEUW2bPrWdmNVQVB7cpsRC33yty
        }
        tip: 0
      }

**Comment by jacogr** [comment]
1. Could you please re-format the above, it is not readable
2. Consider moving this to another repo for the toolset you use (this is the apps UI, not the API)
3. I have seen an issue posted like this on Stackexchange in the last day - have not looked into that (if a duplicate, this wwill just be marked as such, i.e. linked to the SE post. SE is always better since it is the community, but we certainly don't double-answer here)

**Comment by jacogr** [comment]
Duplicate of SE question - https://substrate.stackexchange.com/questions/6243/how-to-generate-the-mortalera
