### ISSUE TITLE
Multisig dialog box not as expected

### ISSUE THREAD

**Issue by abhath-labs** [polkadot-js/apps#8549]
**Issue** : We are not seeing the expected multisig dialog box as expected.

When using a multisig wallet for a transaction we expect to see this dialog box :

<img width="1245" alt="Screenshot 2022-12-15 at 3 58 45 PM" src="https://user-images.githubusercontent.com/99468748/207853756-f60e4742-3fea-4313-98e0-33cf50baa0df.png">

But in our parachain we are seeing this dialog box instead :

<img width="1201" alt="Screenshot 2022-12-15 at 4 00 46 PM" src="https://user-images.githubusercontent.com/99468748/207854113-044977c3-333a-44e2-af45-af4e4a845bc5.png">

These are separate multisig accounts created in each parachain, not sure if this is a parachain config issue or polkadotjs issue, not seeing any errors in console when opening the dialog box.

**How to reproduce :**

You can observe this behaviour in the accounts page here : https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Ftestnet.bitgreen.org#/accounts

**Version :**

api v9.10.2
apps v0.122.3-117

**Comment by jacogr** [comment]
The apps UI cannot detect a valid multisig pallet. This is due to the pallet has been renamed on the chain, see

![image](https://user-images.githubusercontent.com/1424473/207881486-783a570d-01aa-426f-9726-839648acc5cc.png)

vs

![image](https://user-images.githubusercontent.com/1424473/207881833-5e6c035b-4f8f-4460-a41f-ebfa2a48413d.png)

So basically the api looks for the extrinsics in the `multisig` pallet, however that name is not exposed by the metadata.

**Comment by abhath-labs** [comment]
Thankyou, changing the name fixed it.
