### ISSUE TITLE
blocktimes widget not working

### ISSUE THREAD

**Issue by andresvsm1** [polkadot-js/apps#8745]
Currently it seems like the Latency -> Blocktimes widget is not working correctly. I thought it might be due to my chain version, but it seems that all chains are affected.

![Captura de pantalla 2023-01-10 a las 10 52 52](https://user-images.githubusercontent.com/36670229/211519436-32b34e37-f89c-458a-b039-d243b832c42d.png)

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
      ✅ It should display the blocktimes widget correctly.
      ❌ It returns an Uncaught error due to an `undefined` property.

* **What is the motivation for changing the behavior?**
    The blocktimes is useful to see if the block is being closed on time, therefore I think this bug/issue needs to be fixed.

* **Please tell us about your environment:**
    I'm using chrome with the following version: 108.0.5359.124 (Build oficial) (arm64)

  - Version: 108.0.5359.124
  - Environment:

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by andresvsm1** [comment]
It seems to only happen in chrome, as with Firefox and Safari works fine 🤷🏻‍♂️

**Comment by jacogr** [comment]
Ok, so current status - still no idea. This error is thrown from inside a plugin to the charts, so it has some underlying issue which seems to randomly occur... and then not occur. (In previous times I did dig through that plugin code to see if I can submit a fix upstream, however didn't get very far)

In this specific case all the charts are rendered at exactly the same time (which seemed to be an issue with the previous report on the same thing), so I'm left without any specific levers to pull on this side of the fence. Having said that, I did add specific rendering React keys to each chart as well as ensuring the chart options stay consistent, but that would most-probably do diddly-squat to improve your case.

Are other charts working for you?

- those on Kusama referendums, i.e. expanding an ongoing referendum on Kusama
- those on validator stats, i.e. clicking on a validator chart info
- does only the first chart on this page show the issue or do they all have traces?

(Based on the 2 reports now on the same random thing, I'm pulling out my hair since I would expect the plugin to "just work")

**Comment by andresvsm1** [comment]
Hi! Regarding those charts:

* Kusama referendums works fine
* Validator Stats also works fine

Currently a new chart seems to also fail, but now it gets interesting.

If I open the Latency tab for Kusama (or any other) the following charts fail:

![Captura de pantalla 2023-01-12 a las 14 02 31](https://user-images.githubusercontent.com/36670229/212073394-ca87d022-20fc-4d2e-b577-673da5c8b10d.png)

Opening dev tools, this is what I get:

![Captura de pantalla 2023-01-12 a las 14 03 21](https://user-images.githubusercontent.com/36670229/212073563-08228892-f9f8-4c08-9630-86d1b212e7ad.png)

However, if I open the same tab while having the developer tools open, it seems to load fine (no errors/warnings emitted, the ones that you see are from the previous screenshot)

![Captura de pantalla 2023-01-12 a las 14 03 54](https://user-images.githubusercontent.com/36670229/212073650-f48b654f-13db-48a5-bf8d-bcc7f251beab.png)

**Comment by jacogr** [comment]
The dev tools opening is the same as reported in the other issue. It is weird indeed.

I'll do one last hail-Mary and explicitly render 1, then 2, then 3 and then 4. (i.e. manage the state in order to try and work around whatever issue the plugin has). If that fails, out of ideas to try and work around this library bug.

**Comment by jacogr** [comment]
The hail-mary has been deployed - so would appreciate you checking on apps v0.122.3-266 to see if it is better or if we are out of ideas.

**Comment by andresvsm1** [comment]
It seems to work fine now with version v0.122.3-271! 

Feel free to close this issue, thanks!

**Comment by jacogr** [comment]
Thank fuck. Dunno what else to say.

(As much as the patch is a major PITA hack around the charts to workaround the chart plugin issues, at least it gives something to do elsewhere if this does show up)
