### ISSUE TITLE
Error UseReferanda

### ISSUE THREAD

**Issue by masterdubs** [polkadot-js/apps#8820]
* **I'm submitting a bug report about an update made during the weekend**

  - [ x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

When connect to a node it search the ws endpoint ( https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fws.swapdex.network#/explorer ), load the metadata then goes blank, seem a trouble with referanda rendering ( see screenshot ) 
![image](https://user-images.githubusercontent.com/3204905/212611998-afa1e63b-b2b7-4da6-a8b6-3fe3b935ac05.png)

This was loading perfectly last week, but not just goes blank. 

We have the same problem if we try to use a local node for development update.

Thank you

**Comment by masterdubs** [comment]
last used version was apps v0.122.3-274

**Comment by jacogr** [comment]
Ok, will have to add another check to disable referenda on those types of chains. The issue is that it is missing some critical information that makes old/current/new efforts quite difficult.

![image](https://user-images.githubusercontent.com/1424473/212617945-767ebffa-b3cf-44d0-8c90-f34fb1937374.png)

vs

![image](https://user-images.githubusercontent.com/1424473/212618084-5e25c095-9b27-48d4-80c0-3d7cd1354b4f.png)

**Comment by masterdubs** [comment]
Thank you @jacogr !
