### ISSUE TITLE
Incorrect batch size for 'Payout all' in Vara Network

### ISSUE THREAD

**Issue by EugenWay** [polkadot-js/apps#8917]
ISSUE:

Network:  Vara network https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.vara-network.io#/
Problem: Doesn't works the 'Payout All' functionality. 

Producing an error type: 1010: Invalid Transaction: Transaction would exhaust the block limits.

<img width="382" src="https://user-images.githubusercontent.com/5233530/215831251-1a4b4bf1-3ab6-4ab2-8b88-8bf0e9a51706.png">

This happens because the block in Vara is much smaller than it is in standard Substrate networks. And when forming a batch, it takes 65% of the maxBlock parameter as a basis.

SUGGESTION

When forming a batch, calculate batchSize not based on maxBlock limit, but get it directly from the const system.blockWeights: FrameSystemLimitsBlockWeights from maxExtrinsic

**Comment by EugenWay** [comment]
@jacogr Hello, how is it going with this issue? I saw you created the PR

**Comment by jacogr** [comment]
PR seems to get to the correct sizes on Polkadot, Kusama & Westend. (After some tweaking, this is dangerous since the "obvious way" actually creates batches that could be delayed in being included)

Without testing on other networks, there is no way to know if it does the right thing. (And if it would actually solve the specific issue reported.)

The above along with a proper review means it is not ready.
