### ISSUE TITLE
AccountId20 on Frontier Template Node

### ISSUE THREAD

**Issue by bernardoaraujor** [polkadot-js/apps#9355]
Frontier recently received support for Moonbeam's `AccountId20`: https://github.com/paritytech/frontier/pull/1019

When trying to visualize the `Accounts` tab of PolkadotJS Apps on a local Frontier Template Node (which is using `AccountId20` by default now), I run into this:
![image](https://user-images.githubusercontent.com/9698228/233403633-bf458f40-d737-4aed-a2ad-f880c5466e6b.png)

What are the necessary modifications (either on this repository or on frontier) in order to make this work out of the box?

**Comment by bernardoaraujor** [comment]
after some poking around, I discovered that adding the following JSON to `Settings`/`Developer` cleared up the error:
```
{
  "AccountId": "EthereumAccountId",
  "Address": "AccountId"
}
```

however, now PolkadotJS is picking up Moonbeam's pre-funded accounts (`Alith`, `Baltathar`, etc):
![image](https://user-images.githubusercontent.com/9698228/233481045-5d32f52e-91b7-4bf3-91c6-9f58796ce81b.png)

While the prefunded accounts for Frontier Template Node are simply `Alice`, `Bob`, etc.

**Comment by jacogr** [comment]
The API tries to detect the `AccountId` type based on stuff it knows about. This basically means it will follow this logic to try and determine if it has an `AccountId20` type. https://github.com/polkadot-js/api/blob/abdc50f405e6d7b64c8a5f9c98371595a7d47c8f/packages/types/src/metadata/PortableRegistry/PortableRegistry.ts#L402-L433

It is quite possible that the template maps from a different type, so it just has something it doesn't know about and thus falls back to `AccountId32`.

As for the funded addresses - for all Ethereum chains it will just use the Alith/... development accounts on the keyring since that is what it knows is funded on general Ethereum-like chains. This is determined by the keyring itself in https://github.com/polkadot-js/common/blob/e3b11360ab381a51bb05544cf2872646037d3579/packages/keyring/src/testing.ts#L132-L136

**Comment by bernardoaraujor** [comment]
Thanks for the insights @jacogr 

I updated the endowed accounts on the template, so now they're showing up with the correct funds (only if I add the extra JSON to `Settings`/`Developer` as mentioned previously.

However, when trying to make a balance tx, or submit some simple extrinsic, I run into the following:
![image](https://user-images.githubusercontent.com/9698228/233838066-ff0f31d7-664d-4f78-8ec1-e03bdc607424.png)

**Comment by bernardoaraujor** [comment]
solved by following the advice from this SE answer: https://substrate.stackexchange.com/a/7347/494
```
diff --git a/template/runtime/src/lib.rs b/template/runtime/src/lib.rs
index e12e21eb..8101a28f 100644
--- a/template/runtime/src/lib.rs
+++ b/template/runtime/src/lib.rs
@@ -181,7 +181,7 @@ impl frame_system::Config for Runtime {
        /// The identifier used to distinguish between accounts.
        type AccountId = AccountId;
        /// The lookup mechanism to get account ID from whatever is passed in dispatchers.
-       type Lookup = AccountIdLookup<AccountId, ()>;
+       type Lookup = sp_runtime::traits::IdentityLookup<AccountId>;
        /// The header type.
        type Header = generic::Header<BlockNumber, BlakeTwo256>;
        /// The ubiquitous event type.
@@ -438,7 +438,7 @@ impl fp_rpc::ConvertTransaction<opaque::UncheckedExtrinsic> for TransactionConve
 }
 
 /// The address format for describing accounts.
-pub type Address = sp_runtime::MultiAddress<AccountId, ()>;
+pub type Address = AccountId;
 /// Block header type as expected by this runtime.
 pub type Header = generic::Header<BlockNumber, BlakeTwo256>;
 /// Block type as expected by this runtime.
```

balance tx is working without no JSON added to `Settings`/`Developer`
