### ISSUE TITLE
Polkadot{.js} extension not findable via Chrome Store search

### ISSUE THREAD

**Issue by laboon** [polkadot-js/apps#9394]
This isn't really a Polkadot-JS Apps bug, but I figured this was the best place to put it so that you were aware.

While the Polkadot{.js} extension still exists on the Google Chrome Store ([here](https://chrome.google.com/webstore/detail/polkadot%7Bjs%7D-extension/mopnmbcafieddcagagdcbnhejhlodfdd)), it is not findable via the search. I tried "polkadot", "polkadot{.js}", etc. and could not get it to appear in search results.

**Comment by jacogr** [comment]
This should be logged in the extension, it has nothing to do with apps.

It is published unlisted.

Without it the cycle to get it published is around 2 weeks. For sanity purposed, since the 3-4 day reviews are such a nightmare that I don't publish regularly, making it 2 weeks like we had at the start is not worth it, there is just not enough time to try and pay attention to it.
