### ISSUE TITLE
 Incorrect block number displayed when withdrawing tokens from Westend pool

### ISSUE THREAD

**Issue by AMIRKHANEF** [polkadot-js/apps#9397]
I initiated an unbonding process on a Westend pool three days ago and attempted to withdraw tokens. However, PJS/apps displays a negative block number, indicating that the unlocking period has already passed. This issue prevents me from withdrawing my tokens and needs to be addressed. I'd like to mention that this issue also occurs on other extension wallets.
![Screenshot (24)](https://user-images.githubusercontent.com/75857984/235665078-e02ac876-ebc9-4b48-b424-de10238cd237.png)

Here is the account address: 5HVgyb9jcYvAtCrSeu2RvnHz4vVZfHZeJPVffWUUGYQZbzUC

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**
I expected to be able to withdraw my tokens, but instead a negative block number was displayed.

* **Please tell us about your environment:**

  - Version: apps v0.129.2-3
  - Environment:

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [x] Other

**Comment by jacogr** [comment]
It is due to the era being stalled -

![image](https://user-images.githubusercontent.com/1424473/235837521-ce1fa9bd-7d76-4395-a7f9-f4359edabd61.png)

The issue is that your funds will be available in era 6433 (it is currently 6431) and the era is way overdue.

**Comment by AMIRKHANEF** [comment]
Thank you for your response, now I understand the issue. My intention was to report the problem I encountered.

**Comment by jacogr** [comment]
Made some small changes in the linked PR, which may make it less confusing -

1. It explicitly mentions that the era has stalled in the tooltip
2. Obviously the calcs are not accurate in this case, but negative times makes it more so. So currently it will convert the overflow value into positive values. However, that will obviously be incorrect since it really only would come into play when the stalling is resolved.

So it should be "less confusing", but in this specific case, the timings will still be inaccurate since it just cannot progress while eras are not flowing.
