### ISSUE TITLE
Assertion error in the "Extrinsic tab page" when user selects "timestamp" from the selection box labelled "from extrinsic section"

### ISSUE THREAD

**Issue by ltfschoen** [polkadot-js/apps#94]
When select the "Extrinsics tab" and then choose "timestamp" from the selection box under the "from extrinsic section" label it crashes with `Error: Assertion failed`. See screenshots below:

![screen shot 2018-06-13 at 10 42 46 am](https://user-images.githubusercontent.com/6226175/41340253-39652f46-6ef7-11e8-8e7f-2fd47f68dd33.png)

![screen shot 2018-06-13 at 10 43 18 am](https://user-images.githubusercontent.com/6226175/41340263-3d81389a-6ef7-11e8-99de-66c6be036515.png)

**Comment by jacogr** [comment]
poc-1 chain I see... It could be that something broke in my last `types` (or even `util`) update - not sure what, will have to dig :(

**Comment by jacogr** [comment]
Aha, just dawned on me what the issue is - for type `Timestamp` we allocate a new Date object, here we try to work with a BN. 

However, this one shouldn't be visible, it is an inherent extrinsic - the hidden flag is set, so the filtering is not checking for these to hide them - 

https://github.com/polkadot-js/types/blob/master/packages/extrinsics/src/timestamp.js#L14

**Comment by ltfschoen** [comment]
@jacogr In the file https://github.com/polkadot-js/apps/blob/master/packages/ui-app/src/InputStorage/options/key.tsx, it doesn't contain `type: 'private' | 'public'` in the `creationOptions` function. Should we change it so it considers methods values that are contained within both the `private` and `public` keys, as can be seen performed in https://github.com/polkadot-js/apps/blob/master/packages/ui-app/src/InputExtrinsic/options/method.tsx?
