### ISSUE TITLE
Gov1. Can't delegate to an account I don't own.

### ISSUE THREAD

**Issue by juanweb3** [polkadot-js/apps#9479]
* **I'm submitting a ...**

  - [x] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

I would like to use the 'Delegate democracy votes' option within my Polkadot-JS UI account to delegate my votes to an external account that I do not own.

However, I am facing an issue where the drop-down menu for the 'delegated account' does not display any accounts saved in my Address book, and it also does not allow me to manually enter or paste any other account.

Polkadot. Gov1.

* **Please tell us about your environment:**

  - Version: Parity Polkadot v.0.42. API v10.6.1. Apps v.0130.1
  - Environment: Google Chrome

    - [ ] Node.js
    - [x] Browser
    - [ ] Other (limited support for other environments)

**Comment by jacogr** [comment]
This has been discussed in detail in the past.

As of now, since Gov 2 is the new direction for Substrate (which does have any-delegation support), we also don't want to expend any effort on the older generation - even though it will be in use for some time. (Even just testing new functionality is exceedingly difficult for the older version since we need a specialist config to enable it)
