### ISSUE TITLE
Polkadot.js not showing identities of stashes on parachain rpc server

### ISSUE THREAD

**Issue by stakeworld** [polkadot-js/apps#9532]
Also asked this question on [stackechange](https://substrate.stackexchange.com/questions/8742/polkadot-js-not-showing-identities-of-stashes-on-parachain-rpc-server) but did not find an answer there.

We are running public relaychain rpc endpoints and are further deploying polkadot-parachain endpoints, starting with statemine/statemint/westmint.  

Everything works but when using our endpoints in polkadot.js they don't show the identities of stashes but only the stash itself while in other endpoint the stashed translate to identities. 

So ours only show "HPUEzi4v3YJmhBfSbcGEFFiNKPAGVnGkfDiUzBNTR7j1CxT" while the other endpoints show "LUCKYFRIDAY.IO". See also [stakeworld rpc](https://polkadot.js.org/apps/?rpc=wss://ksm-rpc.stakeworld.io/statemine#/collators) versus [parity rpc](https://polkadot.js.org/apps/?rpc=wss://statemine-rpc.polkadot.io#/collators).

Same issue for [statemint](https://polkadot.js.org/apps/?rpc=wss://dot-rpc.stakeworld.io/statemint#/explorert#/explorer) and  [westmint](https://polkadot.js.org/apps/?rpc=wss://wnd-rpc.stakeworld.io/westmint#/explorer)

It could be that this lookup only works when our node get's included in polkadot.js but I doubt thats the problem?

The nodes are running on dedicated updated ubuntu 22.04 servers, latest `polkadot-parachain` running via systemctl, open p2p/ws/wss ports, nginx proxy, no errors in the logs. Besides the identity problem everything works perfectly. 

What i've tried so far: 
* checked that all ports are open, logs, etc
* direct connection vs load balancer
* node url with and without subdirectory (/statemine vs /)
* relaychain connection via rpc `--relay-chain-rpc-urls=` vs running relaychain native via `polkadot-parachain` binary
* relaychain archive node vs pruned node
* downgraded binary (so tried v0.9.420 and v0.9.400)
* Looked at chrome developer tool/console to see if there are specific errors (no difference)

**Comment by stakeworld** [comment]
After merge in polkadot.js the identity lookups started working so apparently it is linked. Closing.

**Comment by jacogr** [comment]
The identities are retrieved from the relay. This means it needs to determine which relay the parachain is connected to.

The only way this works is when the config is in the apps UI itself i.e. pasting a URL and accessing it via custom config won't work, it literally needs to be in the apps-config package. This is because the app trawls through the config, finds the endpoint and then for that endpoint sees which relay it is connected to. And then makes another API connection to that relay to retrieve identities. (At this point it can still fail since it randomly picks an endpoint and it may be unreachable at that point - although the relay providers have been stable/reachable for the most part, aka we have almost no issues with them in here)
