### ISSUE TITLE
Keeping wiki and polkadotjs/apps in sync

### ISSUE THREAD

**Issue by lsaether** [polkadot-js/apps#967]
The [Polkadot wiki](https://wiki.polkadot.network) aims to be a complete knowledge base for Polkadot and its users (builders, users, node operators). 

Polkadot-JS apps is the most extensive user interface for Polkadot that reflects all the latest upstream changes to the Rust code. Recently, Polkadot-JS integrated a help button which provides additional information to the staking page. This content was helpful to answer user questions but should not be needed, instead we can coordinate efforts between the wiki and Polkadot-JS. The goal of the effort is to always keep `apps` and the `wiki` in sync and reduce the amount of manual work made to answer questions on individual basis.

## Motivation

w3f/polkadot-wiki#102 and #922 

## Propositions

- When Polkadot-JS is going to merge a substantial UI change that introduces concepts which need explanation, track the change on the wiki repository (https://github.com/w3f/polkadot-wiki) or in a joint Riot channel.
- PRs are preferred, but issues will be watched and resolved by wiki maintainers / contributors. 
- If there is a need to include help information on the page, sync it with the wiki. This can be done either through use of an external link or more complicated set-up of pulling the latest markdown page from the wiki repo.

## Justification

We shouldn't duplicate Polkadot content in two different places. The wiki is an open and curated knowledge base that will be maintained by w3f and the community. There can be a coordinated effort to make it the central place of truth in regards to Polkadot.

**Comment by jacogr** [comment]
Sadly, users don't click around, they only click in what they see. The addition was done so I could personally could stop answering the same questions over and over and over in the chats as the seemingly only support channel for apps. 

So there is no plan to remove it, rather to add the same basic "get started" to each of the apps, e.g. https://github.com/polkadot-js/apps/issues/946. However, the intent is that the in-app info should only contain -

- the bare basics of terms used
- specific to actual use, don't want anybody lost since the concepts aren't self-explanatory
- external links to the wikis to learn more (don't have this - PR to actual links welcome)

Happy to pull a bare-bones summary from elsewhere if it meets the needs of taking the user-by-the-hand and not creating even more confusion out there in the wild.

**Comment by Tbaut** [comment]
Closing as this issue isn't actionable. We'll all do our best to keep things in sync.
