### ISSUE TITLE
Transferable balance is incorrect

### ISSUE THREAD

**Issue by michalisFr** [polkadot-js/apps#9988]
* **I'm submitting a ...**

  - [X] Bug report
  - [ ] Feature request
  - [ ] Support request
  - [ ] Other

* **What is the current behavior and expected behavior?**

Transferable balance seems to be calculated incorrectly. After the merging of [this PR](https://github.com/paritytech/substrate/pull/12951), `reducible` is calculated as indicated [here](https://github.com/paritytech/polkadot-sdk/blob/3069b0af398e5a0374802c31201637e97f4a530a/substrate/frame/balances/src/impl_fungible.rs#L44).

It seems transferable is calculated with the deprecated:
`transferable = free - reserved - max(feeFrozen, miscFrozen)`

* **What is the motivation for changing the behavior?**

Display transferable balance properly. 

Perhaps `free` balance should also be displayed because it can be used for holds (aka reserves) even if transferable is insufficient.

* **Please tell us about your environment:**

  - Version: apps v0.132.2-134
  - Environment:

    - [ ] Node.js
    - [X] Browser
    - [ ] Other (limited support for other environments)

  - Language:

    - [ ] JavaScript
    - [ ] TypeScript (include tsc --version)
    - [ ] Other

**Comment by Albertpolkadot** [comment]
Hello @IkerAlus & @TarikGul ,

Today, I encountered a critical issue while attempting to submit a proposal. After creating a pre-image, I noticed that my transferrable balance was showing as 0 DOT.

In an attempt to rectify this, I initiated a transaction of 20 DOT from another wallet to my identified wallet. However, even after completing the transaction, my transferrable balance remains unchanged. Subscan indicates that the transaction was successfully processed, as seen [here](https://polkadot.subscan.io/extrinsic/20409079-2).

![Captura de pantalla 2024-04-19 122056](https://github.com/polkadot-js/apps/assets/144892919/d5fd60f1-a897-4f99-b3fe-4528df407a40)

This issue is particularly urgent as I urgently need to submit two proposals on Polkassembly and create and sign child bounties within the next 10 days. Unfortunately, my account is currently frozen, preventing me from proceeding with these crucial tasks.

Thanks!

**Comment by Albertpolkadot** [comment]
Hi @IkerAlus,

Yes, this is the problem, I sent 20 Dots to my wallet, but I can't see these 20 DOTS that they should be free...

![image](https://github.com/polkadot-js/apps/assets/144892919/3d3c3950-e6b3-4c80-b816-b5aebda7b2d2)

**Comment by TarikGul** [comment]
@Albertpolkadot Hey I am looking into this now. Can you post a picture of the UI where it says your transferable balance is zero. I am currently trying to trace down the root of this and that would help a lot.

**Comment by TarikGul** [comment]
This has been fixed in the API level and will be fixed in apps this week.
